---
permalink: windows/concept_what_snapmanager_for_oraclefor_sap_is.html
sidebar: sidebar
keywords: snapmanager, tools, perform, policy-driven, data, management, schedule, create, database, backup, restore, primary, storage, post-process, sap
summary: SnapManager provides the tools required to perform policy-driven data management, schedule and create regular database backups, restore data from these backups in the event of data loss or disaster, and create database clones. You can create backups on primary storage and create protected backups on secondary storage by using post-processing scripts.
---
= What SnapManagerfor SAP is
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager provides the tools required to perform policy-driven data management, schedule and create regular database backups, restore data from these backups in the event of data loss or disaster, and create database clones. You can create backups on primary storage and create protected backups on secondary storage by using post-processing scripts.

SnapManager leverages NetApp technologies when integrating with the latest database releases. SnapManager is integrated with the following NetApp applications and technologies:

* SnapDrive automates storage provisioning tasks and simplifies the process of creating error-free, host-consistent Snapshot copies of the storage.
* Snapshot (a feature of Data ONTAP) creates point-in-time copies of the database.
* SnapVault (a licensed feature of Data ONTAP) leverages disk-based backups for reliable, low-overhead backup and recovery of databases.
* SnapMirror (a licensed feature of Data ONTAP) replicates database data across a global network at high speeds in a simple, reliable, and cost-effective manner.
* SnapRestore (a licensed feature of Data ONTAP) recovers an entire database in seconds, regardless of the capacity or the number of files.
* FlexClone (a licensed feature of Data ONTAP) helps to create fast, space-efficient clones of databases from the Snapshot backups.

SnapManager operates across SAN (FC and iSCSI) protocols.
