---
permalink: windows/concept_database_restore_by_using_brrestore_and_brrecover.html
sidebar: sidebar
keywords: 
summary: 'The BRRESTORE and BRRECOVER commands work only with backups created using BRBACKUP.'
---
= Database restore by using BRRESTORE and BRRECOVER
:icons: font
:imagesdir: ../media/

[.lead]
The BRRESTORE and BRRECOVER commands work only with backups created using BRBACKUP.

See the SAP documentation for specific instructions and syntax for the BRRESTORE and BRRECOVER commands.

If the SnapManager profile name is different from the SAP database system identifier, you must specify the name of the parameter file that contains the SnapManager profile name. You can do this in one of the following ways:

* Specify the backup utility parameter file (initSID.utl) using the-r option in the BRBACKUP command.
* Specify the parameter file in the BR*Tools initialization file (initSID.sap).

NOTE: Backups (data files, control files, or online redo log files) that are created by using BRBACKUP can be restored from secondary or tertiary storage systems by using the smsap restore command. However, it is recommended to back up the other SAP configuration files, for example, SAP log files, kernel files, and transports requests by using BRBACKUP with SAP_DIR, and restore by using BRRESTORE.
