---
permalink: windows/concept_prerequisites_for_performing_rolling_upgrade.html
sidebar: sidebar
keywords: 
summary: 'Before performing a rolling upgrade, you must ensure that your environment meets certain requirements.'
---
= Prerequisites for performing rolling upgrades
:icons: font
:imagesdir: ../media/

[.lead]
Before performing a rolling upgrade, you must ensure that your environment meets certain requirements.

* If you are using any version earlier than SnapManager 3.1 and want to perform a rolling upgrade to SnapManager 3.3 or later, you need to first upgrade to 3.2 and then to the latest version.
+
You can directly upgrade from SnapManager 3.2 to SnapManager 3.3 or later.

* External scripts that are used to perform any external data protection or data retention must be backed up.
* The SnapManager version to which you want to upgrade must be installed.
+
NOTE: If you are upgrading from any version earlier than SnapManager 3.1 to SnapManager 3.3 or later, you must first install SnapManager 3.2 and perform a rolling upgrade. After upgrading to 3.2, you can then install SnapManager 3.3 or later and perform another rolling upgrade to SnapManager 3.3 or later.

* The SnapDrive for Windows version supported with the SnapManager version to which you want to upgrade must be installed.
+
The SnapDrive documentation contains details about installing SnapDrive.

* The repository database must be backed up.
* The amount of SnapManager repository utilization should be minimum.
* If the host to be upgraded is using a repository, SnapManager operations must not be performed on the other hosts that are using the same repository.
+
The operations that are scheduled or running on the other hosts wait for the rolling upgrade to finish.
+
NOTE: It is recommended that you perform a rolling upgrade when the repository is least busy, such as over the weekend or when operations are not scheduled.

* Profiles that point to the same repository database must be created with different names in the SnapManager server hosts.
+
If you use profiles with the same name, the rolling upgrade involving that repository database fails without warning.

* SnapManager operations must not be performed on the host that is being upgraded.

NOTE: The rolling upgrade runs for longer as the number of backups of the hosts being upgraded together increases. The duration of the upgrade can vary depending on the number of profiles and backups associated with a given host.

*Related information*

xref:task_installing_snapmanager_for_oracle_snapmanager_for_sap.adoc[Installing SnapManager for SAP]

http://mysupport.netapp.com/[Documentation on the NetApp Support Site: mysupport.netapp.com]
