---
permalink: windows/concept-snapmanager-security.html
sidebar: sidebar
keywords: perform, snapmanager, operation, credential, govern, authentication, maintain, security
summary: "You can perform SnapManager operations only if you have the appropriate credentials. Security in SnapManager is governed by user authentication."
---
= How SnapManager maintains security
:icons: font
:imagesdir: ../media/

[.lead]
You can perform SnapManager operations only if you have the appropriate credentials. Security in SnapManager is governed by user authentication.

SnapManager maintains security by requesting user authentication through password prompts or by setting user credentials. An effective user is authenticated and authorized with the SnapManager server.

SnapManager credentials and user authentication differ significantly from SnapManager 3.0:

* In SnapManager versions earlier than 3.0, you would set an arbitrary server password when you install SnapManager. Anyone who wants to use the SnapManager server would need the SnapManager server password. The SnapManager server password would need to be added to the user credentials by using the `smsap credential set -host` command.
* In SnapManager (3.0 and later), the SnapManager server password has been replaced by individual user operating system (OS) authentication. If you are not running the client from the same server as the host, the SnapManager server performs the authentication by using your OS user names and passwords. If you do not want to be prompted for your OS passwords, you can save the data to your SnapManager user credentials cache by using the `smsap credential set -host` command.
+
NOTE: The `smsap credential set -host` command remembers your credentials when the `host.credentials.persist` property in the `smsap.config` file is set to *true*.

*Example*

User1 and User2 share a profile called Prof2. User2 cannot perform a backup of Database1 in Host1 without permission to access Host1. User1 cannot clone a database to Host3 without permission to access Host3.

The following table describes different permissions assigned to the users:

[options="header"]
|===
| Permission type| User1| User2
a|
Host Password
a|
Host1, Host2
a|
Host2, Host3
a|
Repository Password
a|
Repo1
a|
Repo1
a|
Profile Password
a|
Prof1, Prof2
a|
Prof2
|===
In the case where User1 and User2 do not have any shared profiles, assume User1 has permissions for the hosts named Host1 and Host2, and User2 has permissions for the host named Host2. User2 cannot run even the nonprofile commands such as `dump` and `system verify` on Host1.
