---
permalink: windows/concept_accessing_snapmanager.html
sidebar: sidebar
keywords: access, snapmanager, command-line, interface, cli, graphical, user, interface, gui
summary: You can access SnapManager by using either the command-line interface \(CLI\) or graphical user interface \(GUI\).
---
= Accessing SnapManager
:icons: font
:imagesdir: ../media/

[.lead]
You can access SnapManager by using either the command-line interface (CLI) or graphical user interface (GUI).

You can perform different SnapManager operations in the following ways:

* By entering commands in the CLI on a host that is in the same network as the database host.
+
For a list of all the commands and an explanation of their options and arguments, see the Command Reference chapter.
+
To access the CLI, click *Start* > *All Programs* > *NetApp* > *SnapManager for SAP* > *Start SMSAP command-line interface (CLI)*.

* By accessing the GUI on a host in the same network as the database host.
+
The GUI provides simple and easy-to-use wizards to help you perform different operations.

* By using SAP BR*Tools commands.

*Related information*

xref:concept_snapmanager_for_oraclefor_sap_command_reference.adoc[SnapManager for SAP command reference]
