---
permalink: windows/concept-cloning-database-backup.html
sidebar: sidebar
keywords: clone, database, task, test, upgrade, affect, production, duplicate, master, installation, train, system, duplicate, master, base, server, requirement, clone
summary: "If you clone a database, you can perform tasks such as test an upgrade to a database without affecting the database in production, duplicate a master installation to several training systems, or duplicate a master installation as a base installation to other servers, which have similar requirements."
---
= Cloning database backup
:icons: font
:imagesdir: ../media/

[.lead]
If you clone a database, you can perform tasks such as test an upgrade to a database without affecting the database in production, duplicate a master installation to several training systems, or duplicate a master installation as a base installation to other servers, which have similar requirements.

You can perform the following tasks related to cloning:

* Clone a database from an existing backup.
* Clone a database in its current state, which enables you to create the backup and the clone in one procedure.
* Clone a database and use custom plug-in scripts, which run before or after the clone operation.
* Clone a database to the same host on which the database resides.
* Clone a database by using archive log files from the external archive log location.
* Clone a database to an alternate host.
* View a list of clones.
* View detailed clone information.
* Delete clones.
