---
permalink: windows/concept_profile_usage_for_br_tools_backups.html
sidebar: sidebar
keywords: br, tools, command, backint, interface, interface, snapmanager, profile, repository, credential, user, run, backup
summary: When you run a BR\*Tools command that uses the BACKINT interface, SnapManager uses a profile from the repository. The repository is determined by the SnapManager credentials of the user running the BR\*Tools command.
---
= Profile usage for BR*Tools backups
:icons: font
:imagesdir: ../media/

[.lead]
When you run a BR*Tools command that uses the BACKINT interface, SnapManager uses a profile from the repository. The repository is determined by the SnapManager credentials of the user running the BR*Tools command.

By default, SnapManager uses the profile with the same name as the SAP database system identifier.

== About creating credentials to access the repository

You can use the smsap credential set command to set the repository credentials for the BR*Tools user.

== About specifying a different SnapManager profile name

As long as the system identifier is unique for all hosts whose SnapManager profiles are in a given repository, the default profile name is sufficient. You can create the SnapManager profile and name it by using the database system identifier value.

However, if the same system identifier is used on different hosts, or if you want to specify more than one SnapManager profile for use with BR*Tools on a given SAP instance, then you need to define the profile name for BR*Tools commands.

Database operations scheduled within the SAP application run as user. BR*Tools operations scheduled within the SAP applications run as SAPServiceSID. These users must have access to the repository and the profile.

The SAP service user SAPServiceSID does not allow the user to log in locally. To change this, you must modify the Local Security Policy by performing the following steps:

. Click *Start* > *Programs* > *Administrative Tools* > *Local Security Policy*.
. Expand *Local Policies* and select**User Rights Assignment**
. Search for the *Deny log on locally* policy.
. Right-click and select *Properties*.
. Delete *SAP Service user* from this list.

== About creating the backup utility parameter file

The BR*Tools command can optionally pass a backup utility parameter (.utl parameter) file to the BACKINT interface. By default, the name of this file is initSID.utl, where SID is the system identifier of the database.

By default, BR*Tools uses the parameter file specified by the util_par_file parameter in the initSID.sap file. The backup utility parameter file is normally stored in the same directory as the initSID.sap file.

Add profile_name = <profile> to the .utl file and save. The profile is the name of the SnapManager profile you want to use for the BR*Tools commands.

The following table lists additional backup utility parameters included in the .utl file for operations like backup retention, fast restore, and data protection:

|===
| Operations| Backup utility parameters
a|
Backup retention
a|

* Key: retain
* Value: unlimited | hourly | daily | weekly | monthly

|===
The following table describes the different backup utility parameters for these operations:

|===
| Operation| Key| Value
a|
Backup retention
a|
fast=
a|
fallback
|===

== Adding the backup utility parameter to the BR*Tools initialization file

SAP creates a backup profile file named initSID.sap for each SAP database instance in $ORACLE_HOME\database\. You can use this file to specify the default backup utility parameter (.utl) file used for BR*Tools commands.

. Edit the initSID.sap file and locate the line starting with `util_par_file =`.
. Uncomment this line and add the path to the backup utility parameter file that contains the name of the profile, for example, `util_par_file = initSA1.utl`.
. If you specify a value for the util_par_file, be sure that the file exists.
+
If the file is not found, the BRBACKUP commands fail because they attempt to include that file in a backup.

If any of the following error conditions are found, then you need to use the -u option as the profile name:

* Parameter files does not exist
* No profile_name entry

Both orasid and sidadm need access to the profile that would be used for creating or managing backups created with BR*Tools.

== Specifying the backup utility parameter file name on the BR*Tools command

You can optionally specify the backup utility parameter (.utl parameter) file on the BR*Tools commands using the -r option. The value on the command line overrides the value specified in the SAP initialization file.

BR*Tools searches for the parameter file in the $ORACLE_HOME\database\ directory. If you store the file in another location, you need to supply the full path with the -r option. For example:

`+brbackup -r C:\Oracle\NetApp_fcp_price_10g_enterprise_inst_vol1\database\initCER.utl ...+`
