---
permalink: windows/concept-database-backups-created-using-brbackup-and-brarchive.html
sidebar: sidebar
keywords: brbackup, command, create, backup, database, snapshot, copy, storage, system, host, command-line, interface, cli, graphical, user, interface, gui, offline, redo, log, file, brarchive
summary: "The BRBACKUP command creates a backup of the SAP database using Snapshot copy on the storage system. You can run the BRBACKUP command from the SAP host’s command-line interface (CLI), or BR*Tools CLI or graphical user interface (GUI). To back up the offline redo log files, you can use the BRARCHIVE command."
---
= Database backups created using BRBACKUP and BRARCHIVE
:icons: font
:imagesdir: ../media/

[.lead]
The `BRBACKUP` command creates a backup of the SAP database using Snapshot copy on the storage system. You can run the `BRBACKUP` command from the SAP host's command-line interface (CLI), or BR*Tools CLI or graphical user interface (GUI). To back up the offline redo log files, you can use the `BRARCHIVE` command.

`BRBACKUP` backs up the data files, control files, and online redo log files of the SAP database. You should back up the other SAP configuration files, for example, SAP log files, kernel files, and transports requests using `BRBACKUP` with the `SAP_DIR` option, and restore using `BRRESTORE`.

If the value of the `_SQLNET.AUTHENTICATION_SERVICES_` parameter in the `sqlnet.ora` is set to *NONE*, ensure that the Oracle database user (system) has sysoper privileges. The system is the default user created during the creation of the Oracle database. To enable SYSOPER privileges, run the following command: `grant sysoper to system;`

You should use either the BR*Tools commands or the SnapManager commands to manage the archive log files.

You should not use the combination of SnapManager profiles and the BR*Tools commands for managing the archive log backups with respect to the following operations:

* Creating separate backups of data files and archive log files using the `BRBACKUP` and `BRARCHIVE` commands with the SnapManager profile (created using the option to separate archive log backups)
* Pruning archive log files while creating the backup using the SnapManager profile

NOTE: SnapManager does not display any warning or error message when you use a combination of SnapManager for SAP profiles and the BR*Tools commands for managing the archive log files.

You should create a profile without using the option to separate archive log backups and use this profile for regular BR*Tools operations.

You can restore the backup by using `BRRESTORE`. For database backups (backups include data files, control files, or online redo log files) created by using BRBACKUP with the `-m all` or `-m full` option, you can also restore the backup by using the SnapManager CLI or GUI.

For more information about how SnapManager handles backing up, see _Backing up databases_.

See the SAP documentation for the specific instructions and syntax for the `BRBACKUP` and `BRARCHIVE` commands. Before using the BRBACKUP and BRARCHIVE command with a storage system, ensure that the following conditions are met:

* If the SnapManager profile name is different from the SAP database system identifier, specify the name of the parameter file that contains the SnapManager profile name.
+
You can do so in one of the following ways:

 ** Specify the backup utility parameter file (`initSID.utl`) using the `-r` option with the `BRBACKUP` command.
 ** Specify the parameter file in the initialization file (`initSID.sap`). For more information, see _Specifying the profile for BR*Tools backups_.

* If it is appropriate for your environment, create additional backups of your SAP data using a different medium, such as tape. Snapshot copies are intended for rapid backup and restoration. They are stored on the same physical media as the data being backed up and are not intended for disaster recovery unless copied to other storage devices.
