---
permalink: windows/concept-configuring-e-mail-notification.html
sidebar: sidebar
keywords: snapmanager, enable, email, notification, completion, status, profile-executed, database, operation, profile, execute, generate, status, configure
summary: "SnapManager enables you to receive an email notification about the completion status of the profile-executed database operations. SnapManager generates the email and helps you to take appropriate action based on the database operation completion status. Configuring email notification is an optional parameter."
---
= Configuring an email notification
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager enables you to receive an email notification about the completion status of the profile-executed database operations. SnapManager generates the email and helps you to take appropriate action based on the database operation completion status. Configuring email notification is an optional parameter.

You can configure an email notification for an individual profile as a profile notification and for multiple profiles on a repository database as a summary notification.

*Profile notification*

For an individual profile, you can receive an email for either or both the successful and failed database operations.

NOTE: By default, email notification is enabled for failed database operations.

*Summary notification*

Summary notification enables you to receive a summary email about database operations performed using multiple profiles. You can enable hourly, daily, weekly, or monthly notifications.

NOTE: From SnapManager 3.3, summary notifications are sent only if you specify the host server that has to send the notification. If you upgrade SnapManager from a version earlier than 3.3, the summary notifications might not be sent if you had not specified the host server in the summary notifications configuration.

NOTE: If you create a repository in one node of a database that is on a Real Application Clusters (RAC) environment and enable summary notification, later when you add the same repository to another node of the database, the summary notification email is sent twice.

You can use either profile-level notification or summary notification at a time.

SnapManager enables email notification for the following profile-executed database operations:

* Create backup on primary storage
* Restore backups
* Create clones
* Verify backups

After you create or update profiles with the email notification enabled, you can disable it. If you disable the email notification, you no longer receive email alerts for those profile-executed database operations.

The email that you receive contains the following details:

* Name of the database operation, for example, backup, restore, or clone
* Profile name used for the database operation
* Name of the host server
* System identifier of the database
* Start and end time of the database operation
* Status of the database operation
* Error message, if any
* Warning messages, if any

You can configure the following:

* Mail server for a repository
* Email notification for a new profile
* Email notification for an existing profile
* Summary email notification for multiple profiles under a repository

NOTE: You can configure email notification from both the command-line interface (CLI) and the graphical user interface (GUI).
