---
permalink: windows/concept_what_snapmanager_for_oraclesnapmanager_for_sap_does.html
sidebar: sidebar
keywords: snapmanager, sap, simplify, simplifies, automate, database, backup, recovery, cloning, clone, leverage, snapshot, copies, copy, snaprestore, flexclone, technology, technologies
summary: SnapManager for SAP simplifies and automates database backup, recovery, and cloning by leveraging the Snapshot copies, SnapRestore, and FlexClone technologies.
---
= What SnapManager for SAP does
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager for SAP simplifies and automates database backup, recovery, and cloning by leveraging the Snapshot copies, SnapRestore, and FlexClone technologies.

SnapManager provides the following benefits to database administrators (DBAs):

* Working with Database profiles
 ** You can organize and retain host and database information in profiles.
+
When you initiate a backup based on a profile, you can reuse the information rather than having to reenter it for every backup. SnapManager also enables you to monitor operations quickly by using profiles.

 ** In the profile, you can define the Snapshot copies naming patterns and enter custom (prefix or suffix) text, so that all the Snapshot copies can use the same naming convention that meets business policies.
 ** You do not need to know the storage system name because database files are automatically mapped to the associated storage.
 ** When you create a new profile, you can specify the option to separate the archive log backup from the data file backup.
+
You can also update the existing profile to separate the archive log backup from the data file backup.
* Performing the database backup operation
 ** Backup of full and partial databases
  *** You can create a full or partial backup quickly in a space-efficient way, which allows you to perform backups more frequently.
+
The full database backup contains all the data files, control files, and archive log files in a single backup.
+
The partial database backup contains specified data files or tablespaces, all the control files, and all the archive log files.

  *** You can protect backups to secondary storage by using post-processing scripts.
  *** You can schedule backups on an hourly, weekly, daily, monthly, or unlimited basis.
 ** Separate back up of data files and archive log files
  *** SnapManager (3.2 or later) enables you to back up the data files and archive log files separately. To perform this operation, you must specify the option to separate the archive log files while creating or updating the profile.
  *** You can specify the count and duration for which the data file backups will be retained, in the retention policy.
  *** You can specify the duration for the archive log file backups to be retained in archive log retention duration.
  *** SnapManager (3.2 or later) also consolidates the archive log backups to a minimum number of backups by freeing the archive log backups with duplicate archive log files and retaining only the archive log backups with unique archive log files. However, this consolidation can be optionally disabled.
* Managing the archive log files
 ** SnapManager (3.2 or later) enables you to prune the archive log files from the archive log destinations.
+
The space occupied by the pruned archive log files is freed when the archive log backups containing these archive log files are purged.

 ** SnapManager ensures that the archive log files are backed up before pruning them from the archive log destinations.
+
The archive log files, which are not backed up are not pruned.

 ** SnapManager ensures that the archive log files are shipped to the Data Guard Standby database while pruning archive log files from a Data Guard Primary database.
 ** SnapManager ensures that the archive log files are captured by Oracle's Streams Capture process, if any.
 ** Recommendation
  *** To manage archive log destination space effectively, you must create the archive log backups, and prune the archive log files along with it.
 ** SnapManager consolidates the archive log backups to contain minimum number of backups by freeing the archive log backups with duplicate archive log files and retaining only the archive log backups with unique archive log files.
+
However, this consolidation can be optionally disabled. The archive log backups, which contain duplicate archive log files are freed and a single backup with unique archive logs is retained.
* Performing the database restore operation
 ** You can perform file-based restore operations.
+
You can also preview restore operations and obtain a file-by-file analysis of restore operations before the operation is performed.

 ** You can reduce the mean time to restore a database by using SnapRestore.
 ** SnapManager (3.2 or later) enables you to recover the database automatically by using the archive log files from the backup even if the archive log files are not available in the archive log destination.
+
SnapManager (3.2 or later) also provides a way to recover the database by using the archive log files from the external location to a certain extent.
* Performing database cloning for testing and development
 ** You can create a clone of a database so that the database can be set up outside the production environment.
+
For example, you can clone in the development and test environments for testing upgrades to vital systems.

 ** You can clone a database on a primary storage system.
 ** SnapManager (3.2 or later) enables you to clone the data file backups with the archive log files available in the backup.
  *** You can clone the data file backups only when the archive log backup is taken along with it.
  *** You can also clone the data file backups if the archive log files are available in the archive log backups made separately to a certain extent.
  *** You can also clone the data file backups of a standalone database to a certain extent with archive log files from any external location accessible by Oracle.
  *** If the backups are available from an external location, you can specify the external location during cloning for recovering the cloned database to a consistent state.
 ** Cloning of the archive log-only backups is not supported.
* General
 ** Integrate with SAP's BR*Tools.
+
The BR*Tools package provides SAP tools such as BRARCHIVE, BRBACKUP, BRCONNECT, BRRECOVER, BRRESTORE, BRSPACE, and BRTOOLS.

SnapManager provides the following benefits to storage administrators:

* Supports different SAN protocols.
* Enables you to optimize backups based on the type of backup (full or partial) that works best in your environment.
* Creates space-efficient database backups.
* Creates space-efficient clones.

SnapManager also works with the following Oracle features:

* SnapManager can catalog its backups with Oracle's RMAN.
+
If using RMAN, a DBA can make use of SnapManager backups and preserve the value of all RMAN functions, such as block-level restore. SnapManager lets RMAN use the Snapshot copies when it performs recovery or restore. For example, you can use RMAN to restore a table within a tablespace and to perform full database and tablespace restores and recoveries from Snapshot copies made by SnapManager. The RMAN recovery catalog should not be in the database that is being backed up.
