---
permalink: windows/concept_protecting_database_backups_by_using_post_scripts.html
sidebar: sidebar
keywords: 
summary: 'SnapManager enables you to protect database backups by using postscripts when SnapMirror or SnapVault relationship is established between the primary and secondary storage systems. You can use the default postscripts for post-processing activity of the backup operation from both the SnapManager CLI and GUI.'
---
= Protecting database backups by using postscripts
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager enables you to protect database backups by using postscripts when SnapMirror or SnapVault relationship is established between the primary and secondary storage systems. You can use the default postscripts for post-processing activity of the backup operation from both the SnapManager CLI and GUI.

You can use the following default postscripts available at default_install_directory\plugins\backup\create\post:

* The SnapMirror postscript, Mirror_the_backup.cmd if you are using Data ONTAP operating in 7-Mode
* The SnapVault postscript, Vault_the_backup.cmd if you are using Data ONTAP operating in 7-Mode
* The SnapMirror postscript, Mirror_the_backup_cDOT.cmd if you are using clustered Data ONTAP
* The SnapVault postscript, Vault_the_backup_cDOT.cmd if you are using clustered Data ONTAP

For more information, see the readme.txt available at default_install_directory\plugins.

SnapManager 3.1 or earlier provides preprocessing or post-processing scripts only for clone operations. SnapManager 3.2 or later provides preprocessing and post-processing scripts for backup and restore operations. You can use these scripts to run before or after the backup or restore operations.

NOTE: The scripts are provided for reference only. They have been tested with SnapDrive 7.0 for Windows or later or later but may not work in all environments. You should customize the scripts based on your secondary protection requirements. The scripts do not work with SnapDrive versions earlier than 6.2.
