---
permalink: windows/concept_restore_backups_from_an_alternate_location_overview.html
sidebar: sidebar
keywords: restore, database, backup, alternate, location, section, overview
summary: To restore a database backup from an alternate location, use the following major steps, each of which is further described in this section.
---
= Restore backups from an alternate location overview
:icons: font
:imagesdir: ../media/

[.lead]
To restore a database backup from an alternate location, use the following major steps, each of which is further described in this section.

* Do one of the following, depending on your database layout and what needs to be restored:
 ** Restore the required data files from tape, SnapVault, SnapMirror, or any other media to any file system mounted on the database host.
 ** Restore the required file system and mount it on the database host.
 ** Connect to the required raw devices that exist in the local host.
* Create a restore specification Extensible Markup Language (XML) file that includes the mappings that SnapManager requires to restore from the alternate location to the original location. Save the file in a location that SnapManager can access.
* Use SnapManager to restore and recover the data using the restore specification XML file.
