---
permalink: windows/concept_requirements_for_running_snapmanager.html
sidebar: sidebar
keywords: deploy, snapmanager, environment, requirement, run
summary: "Before deploying SnapManager in your environment, you should know the different requirements."
---
= Requirements for running SnapManager
:icons: font
:imagesdir: ../media/

[.lead]
Before deploying SnapManager in your environment, you should know the different requirements.

Before using SnapManager, you must review the compatibility matrices for all the required products. You must also review the following:

* SnapManager and SnapDrive compatibility matrix in the interoperability section for the latest version and patch information for all hosts, storage systems, and other components listed in this section.
* The Configuration Guide for NetApp FCP and iSCSI products.

NOTE: SnapManager requires specific Oracle versions on some platforms.

See the documentation kit for more information about the recommended configurations for the host and storage systems.

NOTE: Contact your sales representative if you need a SnapManager configuration that is not mentioned in the documentation kit.

*Related information*

http://support.netapp.com/NOW/products/interoperability/[Interoperability Matrix: support.netapp.com/NOW/products/interoperability^]
