---
permalink: windows/concept_advantages_of_using_snapmanager.html
sidebar: sidebar
keywords: 
summary: 'You can use SnapManager for SAP to perform different tasks on the databases and manage data efficiently.'
---
= Advantages of using SnapManager
:icons: font
:imagesdir: ../media/

[.lead]
You can use SnapManager for SAP to perform different tasks on the databases and manage data efficiently.

SnapManager for SAP works with storage systems and enables you to perform the following tasks:

* Create space-efficient backups to the primary or secondary storage and schedule backups.
+
You can create full and partial database backups and apply retention duration policies.SnapManager (3.2 or later) enables you to create backups of only the data files and archive logs.

 ** SnapManager (3.2 or later) enables you to perform preprocessing or post-processing before or after the backup and restore operations.
 ** SnapManager (3.2 or later) enables you to protect backups by using the postprocessing scripts.

* Restore full or partial databases by using the file-based restore operation.
* Restore and recover database backups automatically.
+
SnapManager (3.2 or later) enables the restoration and recovery of database backups automatically. SnapManager automatically recovers the restored database by discovering, mounting, and applying the archive log files from the backups.

* Prune archive log files from the archive log destinations when creating backups for only the archive logs.
* Retain the minimum number of archive log backups automatically by retaining only the backups with unique archive log files.
* Track operation details and produce reports by host, profile, backup, or clone.
* Verify the backup status.
* Maintain the history of SnapManager operations associated with a profile.
* Create space-efficient clones of backups on the primary storage.
