---
permalink: windows/concept_managing_security_and_credentials.html
sidebar: sidebar
keywords: 
summary: 'You can manage security in SnapManager by applying user authentication. The user authentication method allows you to access resources such as repositories, hosts, and profiles.'
---
= Security and credential management
:icons: font
:imagesdir: ../media/

[.lead]
You can manage security in SnapManager by applying user authentication. The user authentication method allows you to access resources such as repositories, hosts, and profiles.

When you perform an operation using either the command-line interface (CLI) or graphical user interface (GUI), SnapManager retrieves the credentials set for repositories and profiles. SnapManager saves credentials from previous installations.

The repository and profiles can be secured with a password. A credential is the password configured for the user for an object, and the password is not configured on the object itself.

You can manage authentication and credentials by performing the following tasks:

* Manage user authentication either through password prompts on operations or by using the smsap credential set command.
+
Set credentials for a repository, host, or profile.

* View the credentials that govern the resources to which you have access.
* Clear a user's credentials for all resources (hosts, repositories, and profiles).
* Delete a user's credentials for individual resources (hosts, repositories, and profiles).

NOTE: If the repository database is on a Windows host, then both local or administrator user and the domain user must have the same credentials.
