---
permalink: windows/concept_limitations.html
sidebar: sidebar
keywords: aware, scenario, limitation, environment, work, snapmanager
summary: "You must be aware of the scenarios and limitations that might affect your environment."
---
= Limitations when working with SnapManager
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of the scenarios and limitations that might affect your environment.

*Limitations related to database layouts and platforms*

* SnapManager supports control files on a file system and does not support control files on raw devices.
* SnapManager operates in a Microsoft clustering (MSCS) environment but does not recognize the state of the MSCS configuration (active or passive) and does not transfer active management of a repository to a standby server in an MSCS cluster.
* The repository database might exist on a host that can be accessed by using more than one IP address.
+
If the repository is accessed by using more than one IP address, then the schedule file is created for each of the IP addresses. If the schedule backup is created for a profile (for example, profile A) under one of the IP addresses (for example, IP1), then the schedule file for only that IP address gets updated. If profile A is accessed from another IP address (for example, IP2), the scheduled backup is not listed because the schedule file of IP2 does not have an entry for the schedule that was created under IP1.
+
You can wait for the schedule to be triggered from that IP address and the schedule file to be updated, or you can restart the server.

*Limitations related to SnapManager configuration*

* SnapManager supports databases on MultiStore storage systems with the following requirements:
 ** You must configure SnapDrive to set passwords for MultiStore storage systems.
 ** SnapDrive cannot create a Snapshot copy of a LUN or file residing in a qtree in a MultiStore storage system if the underlying volume is not in the same MultiStore storage system.
* SnapManager does not support accessing two SnapManager servers running on different ports from a single client (both from the CLI or GUI).
+
The port numbers should be the same on the target and remote hosts.

* SnapManager operations fail and you cannot access the GUI when the repository database is down.
+
You must verify that the repository database is running when you perform any SnapManager operations.

* SnapManager does not support Live Partition Mobility (LPM) and Live Application Mobility (LAM).
* SnapManager does not support Oracle Wallet Manager and Transparent Data Encryption (TDE).
* SnapManager does not support MetroCluster configurations in raw device mapping (RDM) environments because MetroCluster configurations are yet to be supported by Virtual Storage Console (VSC).

*Limitations related to profile management*

* If you update the profile to separate the archive log backups, then you cannot perform a rollback operation on the host.
* If you enable a profile from the GUI to create archive log backups, and later try to update the profile by using the Multi Profile Update window or Profile Update window, then you cannot modify that profile to create a full backup.
* If you update multiple profiles in the Multi Profile Update window and some profiles have the *Backup Archivelogs separately* option enabled and other profiles have the option disabled, then the *Backup Archivelogs separately* option is disabled.
* If you update multiple profiles and some profiles have the *Backup Archivelogs separately* option enabled and other profiles have the option disabled, then the *Backup Archivelogs separately* option in the Multi Profile Update window is disabled.
* If you rename the profile, then you cannot roll back the host.

*Limitations related to rolling upgrade or rollback operations*

* If you try to install an earlier version of SnapManager for a host without performing the rollback operation on the host in the repository, you might not be able to do the following:
 ** View the profiles that were created in earlier or later versions of SnapManager for the host.
 ** Access backups or clones that were created in earlier or later versions of SnapManager.
 ** Perform rolling upgrade or rollback operations on the host.
* After you separate the profiles to create archive log backups, you cannot perform a rollback operation on the related host repository.

*Limitations related to backup operations*

* During recovery, if the backup is already mounted, SnapManager does not mount the backup again and uses the already mounted backup.
+
If the backup is mounted by a different user and you do not have access to the previously mounted backup, then the other user must provide you the permission.
+
All archive log files have read permission for users assigned to a group; you might not have the access permission to the archive log file, if the backup is mounted by a different user group. Users can give permission to the mounted archive log files manually, and then retry the restore or recovery operation.

* SnapManager sets the backup state as "`PROTECTED`", even when one of the Snapshot copies of the database backup is transferred to the secondary storage system.
* You can use the task specification file for scheduled backup only from SnapManager 3.2 or later.
* If the repository database is pointing to more than one IP address and each IP address has a different host name, then the backup scheduling operation is successful for one IP address but fails for the other IP address.
* In ONTAP environments, SnapManager does not support multiple secondary destinations for a source volume.

*Limitations related to restore operations*

* SnapManager does not support restoring database backups by using fast restore or volume-based restore operations in Windows.
+
SnapManager 3.3 displays an error message when you try to perform a fast restore operation from the SnapManager CLI.

*Limitations related to clone operations*

* SnapManager 3.3 or later does not support using the clone specification XML file created in the releases before SnapManager 3.2.
* If temporary tablespaces are located in a different location from the datafiles location, a clone operation creates the tablespaces in the datafiles location.
+
However, if temporary tablespaces are Oracle Managed Files (OMFs) that are located in a different location from the datafiles location, the clone operation does not create the tablespaces in the datafiles location. The OMFs are not managed by SnapManager.

* SnapManager fails to clone a RAC database if you select the `-resetlogs` option.

*Limitations related to archive log files and backups*

* SnapManager does not support pruning of archive log files from the flash recovery area destination.
* SnapManager does not support pruning of archive log files from the standby destination.
* The archive log backups are retained based on the retention duration and default hourly retention class.
+
When the archive log backup retention class is modified by using the SnapManager CLI or GUI, the modified retention class is not considered for backup because archive log backups are retained based on retention duration.

* If you delete the archive log files from the archive log destinations, the archive log backup does not include archive log files older than the missing archive log file.
+
If the latest archive log file is missing, then the archive log backup operation fails.

* If you delete the archive log files from the archive log destinations, the pruning of archive log files fail.
* SnapManager consolidates the archive log backups even when you delete the archive log files from the archive log destinations or when the archive log files are corrupted.

*Limitations related to changing of target database host name*

The following SnapManager operations are not supported when you change the target database host name:

* Changing the target database host name from the SnapManager GUI.
* Rolling back of the repository database after updating the target database host name of the profile.
* Simultaneously updating multiple profiles for a new target database host name.
* Changing the target database host name when any SnapManager operation is running.

*Limitations related to the SnapManager CLI or GUI*

* The SnapManager CLI commands for the `profile create` operation that are generated from the SnapManager GUI do not have history configuration options.
+
You cannot use the `profile create` command to configure history retention settings from the SnapManager CLI.

* SnapManager does not display the GUI in Mozilla Firefox when there is no Java Runtime Environment (JRE) available on the Windows client.
* SnapManager 3.3 does not display the SnapManager GUI in Microsoft Internet Explorer 6 on Windows Server 2008 and Windows 7.
* While updating the target database host name using the SnapManager CLI, if there are one or more open SnapManager GUI sessions, then all of the open SnapManager GUI sessions fail to respond.
* When you install SnapManager on Windows and start the CLI in UNIX, the features that are not supported on Windows are displayed.

*Limitations related to SnapMirror and SnapVault*

* In some scenarios, you cannot delete the last backup associated with the first Snapshot copy when the volume has a SnapVault relationship established.
+
You can delete the backup only when you break the relationship. This issue is because of an ONTAP restriction with base Snapshot copies. In a SnapMirror relationship the base Snapshot copy is created by the SnapMirror engine, and in a SnapVault relationship the base Snapshot copy is the backup created by using SnapManager. For each update, the base Snapshot copy points to the latest backup created by using SnapManager.

*Limitations related to Data Guard Standby databases*

* SnapManager does not support Logical Data Guard Standby databases.
* SnapManager does not support Active Data Guard Standby databases.
* SnapManager does not allow online backups of Data Guard Standby databases.
* SnapManager does not allow partial backups of Data Guard Standby databases.
* SnapManager does not allow restoring of Data Guard Standby databases.
* SnapManager does not allow pruning of archive log files for Data Guard Standby databases.
* SnapManager does not support Data Guard Broker.

*Related information*

http://mysupport.netapp.com/[Documentation on the NetApp Support Site: mysupport.netapp.com^]
