---
permalink: windows/reference_the_smosmsapprofile_update_command.html
sidebar: sidebar
keywords: 
summary: 'You can run the profile update command to update the information for an existing profile.'
---
= The smsap profile update command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the profile update command to update the information for an existing profile.

== Syntax

----

        smsap profile update 
-profile profile
\[-new-profile new_profile_name\]
\[-profile-password profile_password\]
[-database  
-dbname db_dbname 
-host db_host 
\[-sid db_sid\] 
[-login 
\[-username db_username -password db_password -port db_port\] 
 ]   
[\{-rman  \{-controlfile \| \{\{-login  
-username  rman_username  
-password  rman_password \} 
\[-tnsname  tnsname\]\}\}\} \| 
-remove-rman\] 
 
 
[-retain 
\[-hourly \[-count n\] \[-duration m\]\] 
\[-daily \[-count n\] \[-duration m\]] 
\[-weekly \[-count n\] \[-duration m\]] 
\[-monthly \[-count n\] \[-duration m\]]]] 
-comment comment 
-snapname-patternpattern 
[] 
[-summary-notification] 
[-notification 
\[-success 
-email email_address1,email_address2 
-subject subject_pattern\] 
\[-failure  
-email email_address1,email_address2 
-subject subject_pattern]
[-separate-archivelog-backups
-retain-archivelog-backups
-hours  hours |
-days days |
-weeks weeks |
-months months
[]
[-include-with-online-backups \| -no-include-with-online-backups]]
[-dump] 
\[-quiet \| -verbose\]
----

== Parameters

* *-profile profile*
+
Specifies the name of the profile. This name can be up to 30 characters long and must be unique within the host.

* *-profile-password profile_password*
+
Specifies the password for the profile.

* *-new-profile new_profile_name*
+
Specifies the new name that you can provide for a profile.

* *-database*
+
Specifies the details of the database that the profile describes. This is the database that will be backed up, restored, and so on.

* *-dbname db_dbname*
+
Specifies the name of the database that the profile describes. You can use either the global name or the system identifier.

* *-host db_host*
+
Specifies the name or IP address of the host computer on which the database runs.

* *-sid db_sid*
+
Specifies the system identifier of the database that the profile describes. By default, SnapManager uses the database name as the system identifier. If the system identifier is different from the database name, you must specify it using the -sid option.

* *-login*
+
Specifies the repository login details.

* *-username repo_username*
+
Specifies the user name required to access the repository database.

* *-port repo_port*
+
Specifies the TCP port number required to access the repository database.

* *-database*
+
Specifies the details of the database that the profile describes. This is the database that will be backed up, restored, or cloned.

* *-dbname db_dbname*
+
Specifies the name of the database that the profile describes. You can use either the global name or the system identifier.

* *-host db_host*
+
Specifies the name or IP address of the host computer on which the database runs.

* *-login*
+
Specifies the database login details.

* *-username db_username*
+
Specifies the user name required to access the database that the profile describes.

* *-password db_password*
+
Specifies the password required to access the database that the profile describes.

* *-port db_port*
+
Specifies the TCP port number required to access the database that the profile describes.

* *-retain [-hourly [-countn] [-duration m]] [-daily [-count n] [-duration m]] [-weekly [-count n][-duration m]] [-monthly [-count n][-duration m]]*
+
Specifies the retention class (hourly, daily, weekly, monthly) for a backup.
+
For each retention class, a retention count or a retention duration or both can be specified. The duration is in units of the class (for example, hours for hourly or days for daily). For instance, if the user specifies only a retention duration of 7 for daily backups, then SnapManager will not limit the number of daily backups for the profile (because the retention count is 0), but SnapManager will automatically delete daily backups created over 7 days ago.

* *-comment comment*
+
Specifies the comment for a profile.

* *-snapname-pattern pattern*
+
Specifies the naming pattern for Snapshot copies. You can also include custom text, for example, HAOPS for highly available operations, in all Snapshot copy names. You can change the Snapshot copy naming pattern when you create a profile or after the profile has been created. The updated pattern applies only to Snapshot copies that have not yet occurred. Snapshot copies that exist retain the previous Snapname pattern. You can use several variables in the pattern text.

* *-summary-notification*
+
Specifies that summary email notification is enabled for the existing profile.

* *-notification  [-success-email  e-mail_address1,e-mail address2  -subject  subject_pattern]*
+
Enables email notification for the existing profile so that emails are received by recipients when the SnapManager operation succeeds. You must enter a single email address or multiple email addresses to which email alerts will be sent and an email subject pattern for the existing profile.
+
You can change the subject text while updating the profile or include custom subject text. The updated subject applies only to the emails that are not sent. You can use several variables for the email subject.

* *-notification  [-failure  -email  e-mail_address1,e-mail address2  -subject  subject_pattern]*
+
Enables email notification for the existing profile so that emails are received by recipients when the SnapManager operation fails. You must enter a single email address or multiple email addresses to which email alerts will be sent and an email subject pattern for the existing profile.
+
You can change the subject text while updating the profile or include custom subject text. The updated subject applies only to the emails that are not sent. You can use several variables for the email subject.

* *-separate-archivelog-backups*
+
Separates the archive log backup from datafile backup. This is an optional parameter you can provide while creating the profile. After you separate the backups are separated using this option, you can create either data files-only backup or archive logs-only backup.

* *-retain-archivelog-backups -hours hours | -daysdays | -weeksweeks| -monthsmonths*
+
Specifies that the archive log backups are retained based on the archive log retention duration (hourly, daily, weekly, monthly).

* *-include-with-online-backups | -no-include-with-online-backups*
+
Specifies that the archive log backup is included along with the online database backup.
+
Specifies that the archive log backups are not included along with the online database backup.

* *-dump*
+
Specifies that the dump files are collected after the successful profile create operation.

* *-quiet*
+
Displays only error messages in the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages in the console.

== Example

The following example changes the login information for the database described by the profile and the email notification is configured for this profile:

----
smsap profile update -profile SALES1 -database -dbname SALESDB
 -sid SALESDB -login -username admin2 -password d4jPe7bw -port 1521
-host server1 -profile-notification -success -e-mail Preston.Davis@org.com -subject success
Operation Id [8abc01ec0e78ec33010e78ec3b410001] succeeded.
----

*Related information*

xref:task_changing_profile_passwords.adoc[Changing profile passwords]

xref:concept_how_snapmanager_retains_backups_on_the_local_storage.adoc[How SnapManager retains backups on the local storage]
