---
permalink: windows/reference_the_smosmsapclone_show_command.html
sidebar: sidebar
keywords: run, clone, show, command, display, information, database, profile, smsap
summary: You can run the clone show command to display information about the database clones for the specified profile.
---
= The smsap clone show command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the clone show command to display information about the database clones for the specified profile.

== Syntax

----

        smsap clone show
-profile profile_name
\[-id  guid \| -label clone_name\]
\[-quiet \| -verbose\]
----

== Parameters

* *-profile profile_name*
+
Specifies the list of clones associated with the profile. The profile contains the identifier of the database and other database information.

* *-id guid*
+
Shows information about the clone with the specified GUID. The GUID is generated by SnapManager when you create a clone. You can use the smsap clone show command to display the GUID for each clone.

* *-label label_name*
+
Shows information about the clone with the specified label.

* *-quiet*
+
Displays only error messages in the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages in the console.

== Example

The following example displays information about the clone:

----
smsap clone show -profile SALES1 -label full_backup_sales_May -verbose
----

The following output shows information about a clone of a backup on primary storage:

----
Clone id: 8abc013111b916e30111b916ffb40001
Clone status: SUCCESS
Clone SID: hsdbc
Clone label: hsdbc
Clone comment: null
Clone start time: 2007-04-03 16:15:50
Clone end time: 2007-04-03 16:18:17
Clone host: Host1
Filesystem: E:\ssys1\data_clone\
File: E:\ssys1\data_clone\hsdb\sysaux01.dbf
File: E:\ssys1\data_clone\hsdb\undotbs01.dbf
File: E:\ssys1\data_clone\hsdb\users01.dbf
File: E:\ssys1\data_clone\hsdb\system01.dbf
File: E:\ssys1\data_clone\hsdb\undotbs02.dbf
Backup id: 8abc013111a450480111a45066210001
Backup label: full_backup_sales_May
Backup SID: hsdb1
Backup comment:
Backup start time: 2007-03-30 15:26:30
Backup end time: 2007-03-30 15:34:13
Backup host: server1
----

*Related information*

xref:task_viewing_detailed_clone_information.adoc[Viewing detailed clone information]
