---
permalink: windows/reference_the_smosmsapbackup_delete_command.html
sidebar: sidebar
keywords: run, backup, delete, command, remove, automatic, create, clone, fail, retention, unlimited, basis, class, smsap
summary: "You can run the backup delete command to remove backups that are not automatically removed, such as backups that were used to create a clone or backups that failed. You can delete backups retained on an unlimited basis without changing the retention class."
---
= The smsap backup delete command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the `backup delete` command to remove backups that are not automatically removed, such as backups that were used to create a clone or backups that failed. You can delete backups retained on an unlimited basis without changing the retention class.

== Syntax

----

        smsap backup delete
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id guid \| -all\]
-force
\[-dump\]
\[-quiet \| -verbose\]
----

== Parameters

* *`-profile _profile_name_`*
+
Specifies the database associated with the backup you want to remove. The profile contains the identifier of the database and other database information.

* *`-id _guid_`*
+
Specifies the backup with the specified GUID. The GUID is generated by SnapManager when you create a backup. You can use the `smsap backup list` command to display the GUID for each backup.

* *`-label _label_`*
+
Specifies the backup with the specified label. Optionally, specify the scope of the backup as data file or archive log.

* *`-data`*
+
Specifies the data files.

* *`-archivelogs`*
+
Specifies the archive log files.

* *`-all`*
+
Specifies all backups. To delete only specified backups instead, use the `-id` or `-label` option.

* *`-dump`*
+
Collects the dump files after a successful or failed backup delete operation.

* *`-force`*
+
Forces the removal of the backup. SnapManager removes the backup even if there are problems in freeing the resources associated with the backup. For example, if the backup was cataloged with Oracle Recovery Manager (RMAN), but the RMAN database no longer exists, including `-force` deletes the backup even though it cannot connect with RMAN.

* *`-quiet`*
+
Displays only error messages in the console. The default is to display error and warning messages.

* *`-verbose`*
+
Displays error, warning, and informational messages in the console.

== Example

The following example deletes the backup:

----
smsap backup delete -profile SALES1 -label full_backup_sales_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----
