---
permalink: windows/reference_the_smosmsapclone_delete_command.html
sidebar: sidebar
keywords: 
summary: 'You can run the clone delete command to delete a clone. You cannot delete a clone if the clone is use by any operation.'
---
= The smsap clone delete command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the clone delete command to delete a clone. You cannot delete a clone if the clone is use by any operation.

== Syntax

----

        smsap clone delete 
-profile profile_name 
\[-id guid \| -label clone_name\]
[-login 
\[-username db_username -password db_password -port db_port\] 
 ]   
\[-syspassword syspassword\]
-force 
\[-dump\]
\[-quiet \| -verbose\]
----

== Parameters

* *-profile profile_name*
+
Specifies the name of the profile containing the clone being deleted. The profile contains the identifier of the database and other database information.

* *-force*
+
Deletes the clone even if there are resources associated with the clone.

* *-id guid*
+
Specifies the GUID for the clone being deleted. The GUID is generated by SnapManager when you create a clone. You can use the smsap clone list command to display the GUID for each clone.

* *-label name*
+
Specifies the label for the clone being deleted.

* *-syspassword syspassword*
+
Specifies the password for the sys privileged user.
+
NOTE: You must provide the password for the sys privileged user if the database credentials provided are not the same for sys privileged user.

* *-login*
+
Allows you to enter the database login details.

* *-username db_username*
+
Specifies the user name required to access the database.

* *-password db_password*
+
Specifies the password required to access the database.

* *-port db_port*
+
Specifies the TCP port number used to access the database that the profile describes.

* *-dump*
+
Specifies to collect the dump files after the clone delete operation.

* *-quiet*
+
Displays only error messages in the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages in the console.

== Example

The following example deletes the clone:

----
smsap clone delete -profile SALES1 -label SALES_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----
