---
permalink: windows/reference_the_smosmsapbackup_free_command.html
sidebar: sidebar
keywords: run, backup, free, command, snapshot, copies, copy, removing, remove, metadata, repository, smsap
summary: You can run the backup free command to free the Snapshot copies of the backups without removing the backup metadata from the repository.
---
= The smsap backup free command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the backup free command to free the Snapshot copies of the backups without removing the backup metadata from the repository.

== Syntax

----

        smsap backup free
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id guid \| -all\]
-force
\[-dump\]
\[-quiet \| -verbose\]
----

== Parameters

* *-profile profile_name*
+
Specifies the profile associated with the backup you want to free. The profile contains the identifier of the database and other database information.

* *-id guid*
+
Specifies the resources of the backup with the specified GUID. The GUID is generated by SnapManager when you create a backup. You can use the smsap backup list command to display the GUID for each backup. Include the -verbose option to display the backup IDs.

* *-label label*
+
Specifies the backup with the specified label.

* *-data*
+
Specifies the data files.

* *-archivelogs*
+
Specifies the archive log files.

* *-all*
+
Specifies all backups. To delete specified backups instead, use the -id or -label option.

* *-force*
+
Forces the removal of the Snapshot copies.

* *-quiet*
+
Displays only error messages in the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages in the console.

== Example

The following example frees the backup:

----
smsap backup free -profile SALES1 -label full_backup_sales_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----

*Related information*

xref:task_freeing_backups.adoc[Freeing backups]
