---
permalink: windows/reference_the_smosmsap_repository_rollingupgrade.html
sidebar: sidebar
keywords: command, perform, roll, upgrade, host, multiple, target, database, associate, version, smsap, rollingupgrade
summary: This command performs rolling upgrade on a single host or multiple hosts and their associated target databases from a lower version of SnapManager to a higher version. The upgraded host is managed only with the higher version of SnapManager.
---
= The smsap repository rollingupgrade command
:icons: font
:imagesdir: ../media/

[.lead]
This command performs rolling upgrade on a single host or multiple hosts and their associated target databases from a lower version of SnapManager to a higher version. The upgraded host is managed only with the higher version of SnapManager.

== Syntax

----

        smsap repository rollingupgrade
-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port
-upgradehost host_with_target_database
[-force] [-noprompt]
\[-quiet \| -verbose\]
----

== Parameters

* *-repository*
+
The options that follow -repository specify the details of the database for the repository.

* *-dbname repo_service_name*
+
Specifies the name of the database that stores the repository. Use either the global name or the SID.

* *-host repo_host*
+
Specifies the name or IP address of the host computer the repository database runs on.

* *-login*
+
Starts the repository login details.

* *-username repo_username*
+
Specifies the user name needed to access the database that stores the repository.

* *-upgradehost host_with_target_database*
+
Specifies the name of the host which will be rolling upgraded from a lower version of SnapManager to a higher version.

* *-port repo_port*
+
Specifies the TCP port number used to access the database that stores the repository.

* *-force*
+
Attempts to force the update of the repository. SnapManager prompts you to make a backup of the current repository before updating.

* *-noprompt*
+
Does not display the prompt before updating the repository database. Using the -noprompt option ensures the prompt does not appear, making it easier to update repositories using a script.

* *-quiet*
+
Displays only error messages on the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages on the console.

== Example command

The following example updates the repository in the SALESDB database.

----
smsap repository rollingupgrade -repository -dbname SALESDB
-host server1 -login -username admin -port 1521 -upgradehost hostA
----
