---
permalink: windows/reference_the_smosmsapbackup_verify_command.html
sidebar: sidebar
keywords: run, backup, verify, command, valid, format, oracle, smsap
summary: "You can run the backup verify command to see if the backup is in a valid format for Oracle."
---
= The smsap backup verify command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the `backup verify` command to see if the backup is in a valid format for Oracle.

== Syntax

----
smsap backup verify
-profile profile_name
[-label backup_name | [-id guid]
[-retain {-hourly | -daily | -weekly | -monthly | -unlimited}]
[-force]
[-dump]
[-quiet | -verbose]
----

== Parameters

* *`-profile _profile_name_`*
+
Specifies the profile for which you want to verify a backup. The profile contains the identifier of the database and other database information.

* *`-id _guid_`*
+
Verifies the backup with the specified GUID. The GUID is generated by SnapManager when you create a backup. You can use the `smsap backup list` command to display the GUID for each backup.

* *`-label _label_name_`*
+
Verifies the backup with the specified label.

* *`-dump`*
+
Collects the dump files after the successful or failed backup verify operation.

* *`-force`*
+
Forces the database into the necessary state to perform the verify operation.

* *`-quiet`*
+
Displays only error messages in the console. The default is to display error and warning messages.

* *`-verbose`*
+
Displays error, warning, and informational messages in the console.

== Example

The following is an example of verifying the backup:

----
smsap backup verify -profile SALES1 -label full_backup_sales_May -quiet
----

----
DBVERIFY - Verification starting : FILE = C:\SnapManager_auto_mounts\H-2012071400592312_0\smsap\datafile\data
----
