---
permalink: windows/reference_the_smosmsap_history_set_command.html
sidebar: sidebar
keywords: 
summary: 'You can run the history set command to configure the operations for which you want to view the history.'
---
= The smsap history set command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the history set command to configure the operations for which you want to view the history.

== Syntax

----

        smsap history set 
-profile \{-name profile_name \[profile_name1, profile_name2\] \| -all
-repository 
-login \[password repo_password\]
-username repo_username
-host repo_host 
-dbname repo_dbname 
-port repo_port}
-operation \{-operations operation_name \[operation_name1, operation_name2\] \| -all\} 
-retain
{-count retain_count \| -daily daily_count \| -monthly monthly_count \| -weekly weekly_count}
[-quiet | -verbose]
----

== Parameters

* *-profile profile*
+
Specifies the name of the profile. The name can be up to 30 characters long and must be unique within the host.

* *-repository*
+
Specifies the details of the database that stores the profile.

* *-dbname repo_dbname*
+
Specifies the name of the database that stores the profile. You can use either the global name or the system identifier.

* *-host repo_host*
+
Specifies the name or IP address of the host where the repository database resides.

* *-login*
+
Specifies the repository login details.

* *-username repo_username*
+
Specifies the user name required to access the repository database.

* *-port repo_port*
+
Specifies the Transmission Control Protocol (TCP) port number used to access the repository database.

* *-operation {-operationsoperation_name [operation_name1, operation_name2] | -all*
+
Specifies the SnapManager operations for which you want to configure the history.

* *-retain {-countretain_count | -dailydaily_count | -monthly-monthly_count | -weeklyweekly_count}*
+
Specifies the retention class of the create backup, verify backup, restore and recover, and create clone operations. The retention class is set based on the operation count number, number of days, weeks, or months.

* *-quiet*
+
Displays only error messages in the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages in the console.

== Example command

The following example displays information about the backup operation:

----
smsap history set -profile -name PROFILE1 -operation -operations backup -retain -daily 6
 -verbose
----
