---
permalink: windows/reference_the_smosmsapbackup_update_command.html
sidebar: sidebar
keywords: 
summary: 'You can run the backup update command to update the backup retention policy.'
---
= The smsap backup update command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the backup update command to update the backup retention policy.

== Syntax

----

        smsap backup update 
-profile profile_name 
[-label label \[-data \| -archivelogs\] \| \[-id guid\] 
\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\}\]
\[-comment comment_text\] 
[-quiet | -verbose] 
----

== Parameters

* *-profile profile_name*
+
Specifies the profile for which to update backups. The profile contains the identifier of the database and other database information.

* *-id guid*
+
Verifies the backup with the specified GUID. The GUID is generated by SnapManager when you create a backup. You can use the smsap backup list command to display the GUID for each backup.

* *-label label*
+
Specifies the backup label and scope of the backup as data file or archive log.

* *-data*
+
Specifies the data files.

* *-archivelogs*
+
Specifies the archive log files.

* *-comment comment_text*
+
Enter text (up to 200 characters) about the backup update. You can include spaces.

* *-quiet*
+
Displays only error messages in the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages in the console.

* *-retain {-hourly | -daily | -weekly | -monthly | -unlimited}*
+
Specifies whether the backup should be retained on an hourly, daily, weekly, monthly, or unlimited basis. If -retain is not specified, the retention class defaults to -hourly. To retain backups forever, use the -unlimited option. The -unlimited option makes the backup ineligible for deletion.

== Example

The following example updates the backup to be set the retention policy to unlimited:

----
smsap backup update -profile SALES1 -label full_backup_sales_May
-retain -unlimited -comment save_forever_monthly_backup
----

*Related information*

xref:task_changing_the_backup_retention_policy.adoc[Changing the backup retention policy]

xref:task_retaining_backups_forever.adoc[Retaining backups forever]

xref:task_freeing_or_deleting_retention_policy_exempt_backups.adoc[Freeing or deleting retention policy exempt backups]
