---
permalink: windows/reference-running-multiple-parallel-operations-fail-in-snapmanager.html
sidebar: sidebar
keywords: multiple, run, parallel, operation, seperate, database, reside, storage, system, igroup, lun, associate, delete, snapmanager, display, error, message
summary: "When you run multiple parallel operations on separate databases that reside on the same storage system, the igroup for LUNs associated with both the databases might get deleted because of one of the operations. Later, if the other operation attempts to use the deleted igroup, SnapManager displays an error message."
---
= Running multiple parallel operations fails in SnapManager
:icons: font
:imagesdir: ../media/

[.lead]
When you run multiple parallel operations on separate databases that reside on the same storage system, the igroup for LUNs associated with both the databases might get deleted because of one of the operations. Later, if the other operation attempts to use the deleted igroup, SnapManager displays an error message.

For example, if you are running the backup delete and backup create operations on different databases almost at the same time, the backup create operation fails. The following sequential steps show what happens when you run backup delete and backup create operations on different databases almost at the same time.

.Steps

. Run the `backup delete` command.
. Run the `backup create` command.
. The `backup create` command identifies the already existing igroup and uses the same igroup for mapping the LUN.
. The `backup delete` command deletes the backup LUN, which was mapped to the same igroup.
. The `backup delete` command then deletes the igroup because there are no LUNs associated with the igroup.
. The `backup create` command creates the backup and tries to map to the igroup that does not exist, and therefore the operation fails.

*What to do*

You must create igroup for each storage system used by the database by using the following command: `*sdcli igroup create*`
