---
permalink: windows/reference-the-smosmsapcredential-set-command.html
sidebar: sidebar
keywords: command, credential, user, access, secure, resource, host, repository, repositories, database, profile, password, snapmanager, option, smsap
summary: "This command lets you set the credentials for users to access secure resources, such as hosts, repositories, and database profiles. The host password is the user’s password on the host on which SnapManager is running. The repository password is the password of the Oracle user that contains the SnapManager repository schema. The profile password is a password that is made up by the person who creates the profile. For the host and repository options, if the optional -password option is not included, you will be prompted to enter a password of the type specified in the command arguments."
---
= The smsap credential set command
:icons: font
:imagesdir: ../media/

[.lead]
This command lets you set the credentials for users to access secure resources, such as hosts, repositories, and database profiles. The host password is the user's password on the host on which SnapManager is running. The repository password is the password of the Oracle user that contains the SnapManager repository schema. The profile password is a password that is made up by the person who creates the profile. For the host and repository options, if the optional `-password` option is not included, you will be prompted to enter a password of the type specified in the command arguments.

== Syntax

----

        smsap credential set
\[-host
-name host_name
-username username\]
\[-password password\] \] \|
\[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username\] \[-password repo_password\] \]
-port repo_port \|
\[-profile
-name profile_name\]
\[-password password\] \]
\[-quiet \| -verbose\]
----

== Parameters

* *`-host _hostname_`*
+
Specifies the name or IP address of the host server on which SnapManager is running.
+
The `-host` parameter includes the following options:

 ** `-name host_name`: Specifies the name of the host for which you will set the password.
 ** `-username user_name`: Specifies the user name on the host.
 ** `-password password`: Specifies the password of the user on the host.

* *`-repository -dbname`*
+
Specifies the name of the database that stores the profile. Use either the global name or the SID.
+
The `-repository` parameter includes the following options:

 ** `-dbnamerepo_service_name`: Specifies the name of the database that stores the profile. Use either the global name or the SID.
 ** `-host repo_host`: Specifies the name or IP address of the host server the repository database runs on.
 ** `-login-username repo_username`: Specifies the user name needed to access the database that stores the repository.
 ** `-password password`: Specifies the password needed to access the database that stores the repository.
 ** `-port repo_port`: Specifies the TCP port number used to access the database that stores the repository.

* *`-profile -name _profile_name_`*
+
Specifies the profile with which the database is associated.
+
The `-profile` parameter includes the following option:

 ** `-name profilename`: Specifies the name of the profile for which you will set the password.
 ** `-password password`: Specifies the password needed to access the profile.

* *`-quiet`*
+
Displays only error messages on the console. The default is to display error and warning messages.

* *`-verbose`*
+
Displays error, warning, and informational messages on the console.

== Example command for setting repository credentials

The following example sets credentials for a repository.

----

smsap credential set -repository -dbname SMSAPREPO -host hotspur -port 1527 -login -username chris
Password for chris@hotspur:1527/SMSAPREPO : ********
Confirm password for chris@hotspur:1527/SMSAPREPO : ********
----

----
SMSAP-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMSAP-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----

== Example command for setting host credentials

Because a host credential represents an actual operating system credential, it must include the username in addition to the password.

----
smsap credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----
