---
permalink: windows/reference_the_smosmsap_clone_update_command.html
sidebar: sidebar
keywords: 
summary: 'This command updates information about the clone. You can update the comment.'
---
= The smsap clone update command
:icons: font
:imagesdir: ../media/

[.lead]
This command updates information about the clone. You can update the comment.

== Syntax

----

        smsap clone update 
-profile profile_name 
\[-label label \| -id id\] 
-comment  commment_text
\[-quiet \| -verbose\]
----

== Parameters

* *-profile profile_name*
+
Specifies the name of the profile containing the clone you want to update. The profile contains the identifier of the database and other database information.

* *-id id*
+
Specifies the ID for the clone. The ID is generated by SnapManager when you create a clone. Use the smsap clone list command to display the ID for each clone.

* *-label label*
+
Specifies the label for the clone.

* *-comment*
+
Shows the comment entered in the clone creation. This is an optional parameter.

* *-quiet*
+
Displays only error messages on the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages on the console.

== Example command

The following example updates the clone comment.

----
smsap clone update -profile anson.pcrac5
-label clone_pcrac51_20080820141624EDT  -comment See updated clone
----
