---
permalink: windows/reference_unable_to_restore_rac_database_from_one_of_the_rac_nodes_where_the_profile_was_not_created.html
sidebar: sidebar
keywords: oracle, rac, environment, node, cluster, restore, backup, operation, fail, profile
summary: "In an Oracle RAC environment where both nodes belong to the same cluster, if you attempt a restore operation from a node which is different from the node where the backup was created, the restore operation fails."
---
= Unable to restore RAC database from one of the RAC nodes where the profile was not created
:icons: font
:imagesdir: ../media/

[.lead]
In an Oracle RAC environment where both nodes belong to the same cluster, if you attempt a restore operation from a node which is different from the node where the backup was created, the restore operation fails.

For example, if you create a backup in Node A and try to restore from Node B, the restore operation fails.

*What to do*

Before performing restore operation from node B, perform the following in node B:

.Steps

. Add the repository.
. Sync the profile by running the command `smo profile sync`.
. Set the credential for the profile to be used for restore operation by running the command `smo credential set`.
. Update the profile to add the new host name and the corresponding SID by running the command `smo profile update`.
