---
permalink: windows/reference-troubleshooting-clone-issues.html
sidebar: sidebar
keywords: information, clone, operation, resolve, troubleshoot, issue
summary: "You can find information about that might occur during clone operations and how you can resolve them."
---
= Troubleshooting clone issues
:icons: font
:imagesdir: ../media/

[.lead]
You can find information about that might occur during clone operations and how you can resolve them.

[options="header"]
|===
| Symptom| Explanation| Workaround
a|
The clone operation fails when the archive destination is set to `USE_DB_RECOVERY_FILE_DEST`.
a|
When the archive destination is referring to USE_DB_RECOVERY_FILE_DEST, Flash recovery area (FRA) actively manages the archive log. SnapManager does not use the FRA location during clone or restore operations and thus the operations fail.
a|
Change the archive destination to actual archive log location instead of the FRA location.
a|
The clone operation fails with the following error message: `Cannot perform operation: Clone Create. Root cause: ORACLE-00001: Error executing SQL: [ALTER DATABASE OPEN RESETLOGS;]. The command returned: ORA-01195: online backup of file 1 needs more recovery to be consistent`.
a|
This issue occurs if Oracle listener fails to connect to the database.
a|
If you are using SnapManager GUI to clone a backup, perform the following actions:

. From the Repository tree, click *Repository* > *Host* > *Profile* to display the backups.
. Right-click the backup that you want to clone and select *Clone*.
. On the Clone Initialization page, enter the mandatory values and select the clone specification method.
. On the Clone Specification page, select *Parameters*.
. Click the *Parameter* tab.
. In the *Parameter Name* field, enter the name as `local_listener` and click *OK*.
. Select the *Override Default* check box for the local_listener row.
. Click any parameter, then double-click the local_listener parameter, and enter the following value:``(ADDRESS=(PROTOCOL=TCP)(HOST=<your_host_name>)(PORT=<port#>))``
. Click *Save To File*.
. Click *Next* and continue with the clone create wizard.

If you are using CLI to clone a backup, you must include the following information in the *<parameters>* tag of the clone specification file:

----

<parameters>
  <parameter>
  <name>local_listener</name>
  <value>(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=<hostname>)(PORT=<port#>)))</value>
  </parameter>
</parameters>
----

a|
The clone operation fails with an error message saying that the mountpoint you are using is already in use.
a|
SnapManager does not let you mount a clone over an existing mountpoint. So an incomplete clone did not remove the mountpoint.
a|
Specify a different mountpoint to be used by the clone, or unmount the problematic mountpoint.
a|
The clone operation fails with an error message about data files not having a .dbf extension.
a|
Some versions of the Oracle NID utility do not work with data files unless the files use a .dbf extension.
a|

* Rename the data file to give it a .dbf extension.
* Repeat the backup operation.
* Clone the new backup.

a|
The clone operation fails due to unmet requirements.
a|
You are attempting to create a clone; however, some of the prerequisites have not been met.
a|
Proceed as described in _Creating a clone_ to meet the prerequisites.
a|
SnapManager for SAP fails to clone Oracle 10gR2 (10.2.0.5) physical Oracle Data Guard Standby databases.
a|
SnapManager for SAP does not disable the managed recovery mode while performing an offline backup of the Oracle 10gR2 (10.2.0.5) physical standby databases created using Oracle Data Guard services. Due to this issue, the offline backup taken is inconsistent. When SnapManager for SAP tries to clone the offline backup, it does not even try to perform any recovery on the cloned database. Because the backup is inconsistent, the cloned database requires recovery, and thus SAP fails to create the clone successfully.

a|
Upgrade the Oracle database to the Oracle 11gR1 (11.1.0.7 patch).
|===
