---
permalink: windows/reference_the_smosmsapbackup_show_command.html
sidebar: sidebar
keywords: 
summary: 'You can use the backup show command to display detailed information about a backup, including its protection status, backup retention class, and backups on primary and secondary storage.'
---
= The smsap backup show command
:icons: font
:imagesdir: ../media/

[.lead]
You can use the backup show command to display detailed information about a backup, including its protection status, backup retention class, and backups on primary and secondary storage.

== Syntax

----

        smsap backup show 
-profile profile_name 
[-label label \[-data \| -archivelogs\] \| \[-id id\] 
\[-quiet \| -verbose\]
----

== Parameters

* *-profile profile_name*
+
Specifies the profile for which to show backups. The profile contains the identifier of the database and other database information.

* *-label label*
+
Specifies the label of the backup.

* *-data*
+
Specifies the data files.

* *-archivelogs*
+
Specifies the archive log files.

* *-id id*
+
Specifies the backup ID.

* *-quiet*
+
Displays only error messages in the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages in the console, as well as any clone and verification information.

== Example

The following example shows detailed information about the backup:

----
smsap backup show -profile SALES1 -label BTNFS -verbose
Backup id: 8abc013111a450480111a45066210001
Backup status: SUCCESS
Primary storage resources: EXISTS
Protection sate: NOT REQUESTED
Retention class: DAILY
Backup scope: FULL
Backup mode: OFFLINE
Mount status: NOT MOUNTED
Backup label: BTNFS
Backup comment:

Backup start time: 2007-03-30 15:26:30
Backup end time: 2007-03-30 15:34:13
Verification status: OK
Backup Retention Policy: NORMAL
Backup database: hsdb1
Checkpoint: 2700620
Tablespace: SYSAUX
Datafile: E:\disks\data\hsdb\sysaux01.dbf [ONLINE]
...
Control Files:
File: E:\disks\data\control03.ctl
...
Archive Logs:
File: E:\disks\data\archive_logs\2_131_626174106.dbf
...
Volume: hs_data
Snapshot: SMSAP_HSDBR_hsdb1_F_C_1_
8abc013111a450480111a45066210001_0
File: E:\disks\data\hsdb\SMSAPBakCtl_1175283005231_0
...
----

*Related information*

xref:task_viewing_backup_details.adoc[Viewing backup details]
