---
permalink: windows/reference_the_smosmsapclone_template_command.html
sidebar: sidebar
keywords: command, create, clone, specification, template, smsap
summary: This command lets you create a clone specification template.
---
= The smsap clone template command
:icons: font
:imagesdir: ../media/

[.lead]
This command lets you create a clone specification template.

== Syntax

----

        smsap clone template
-profile name
\[-backup-id guid  \| -backup-label backup_name\]
\[-quiet \| -verbose\]
----

== Parameters

* *-profile name*
+
Specifies the database you want to create a clone specification of. The profile contains the identifier of the database and other database information.

* *-backup-id guid*
+
Creates a clone specification from the backup with the specified GUID. The GUID is generated by SnapManager when you create a backup. Use the smsap backup list command to display the GUID for each backup.

* *-backup-label backup_label_name*
+
Creates a clone specification from the backup with the specified backup label.

* *-quiet*
+
Displays only error messages on the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages on the console.

== Example command

The following example creates a clone specification template from the backup with the label full_backup_sales_May. Once the smsap clone template command completes, the clone specification template is complete.

----
smsap clone template -profile SALES1 -backup-label full_backup_sales_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----

*Related information*

xref:task_creating_clone_specifications.adoc[Creating clone specifications]

xref:task_cloning_databases_from_backups.adoc[Cloning databases from backups]
