---
permalink: windows/reference_the_smosmsapbackup_unmount_command.html
sidebar: sidebar
keywords: run, backup, unmount, command, smsap
summary: You can run the backup unmount command to unmount a backup.
---
= The smsap backup unmount command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the backup unmount command to unmount a backup.

== Syntax

----

        smsap backup unmount
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id id\]
\[-force\]
\[-dump\]
\[-quiet \| -verbose\]
----

== Parameters

* *-profile profile_name*
+
Specifies the profile for which you want to unmount a backup. The profile contains the identifier of the database and other database information.

* *-id id*
+
Unmounts the backup with the specified GUID. The GUID is generated by SnapManager when you create a backup. You can use the smsap backup list command to display the GUID for each backup.

* *-label label*
+
Unmounts the backup with the specified label.

* *-data*
+
Specifies the data files.

* *-archivelogs*
+
Specifies the archive log files.

* *-dump*
+
Collects the dump files after a successful or failed unmount operation.

* *-force*
+
Unmounts the backup even if there are problems in freeing the resources associated with the backup. SnapManager tries to unmount the backup and clean up any associated resources. The log shows the unmount operation as successful, but you may have to manually clean up resources if there are errors in the log.

* *-quiet*
+
Displays only error messages in the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages in the console.

== Example

The following is an example of an unmount operation:

----
# smsap backup unmount -label test -profile SALES1 -verbose
----

----
[INFO ]: SMSAP-13051: Process PID=9788
[INFO ]: SMSAP-13036: Starting operation Backup Unmount on host hadley.domain.private
[INFO ]: SMSAP-13036: Starting operation Backup Unmount on host hadley.domain.private
[INFO ]: SMSAP-13046: Operation GUID 8abc015738849a3d0138849a43900001 starting on Profile FAS_P1
[INFO ]: SD-00031: Beginning to disconnect filesystem(s) [C:\SnapManager_auto_mounts\H-2012071400592312_0, C:\SnapManager_auto_mounts\I-2012071400592328_0].
[INFO ]: SD-00032: Finished disconnecting filesystem(s) [C:\SnapManager_auto_mounts\H-2012071400592312_0, C:\SnapManager_auto_mounts\I-2012071400592328_0].
[INFO ]: SMSAP-13048: Backup Unmount Operation Status: SUCCESS
[INFO ]: SMSAP-13049: Elapsed Time: 0:07:26.754
----

*Related information*

xref:task_unmounting_backups.adoc[Unmounting backups]
