---
permalink: windows/reference_the_smosmsapbackup_mount_command.html
sidebar: sidebar
keywords: 
summary: 'You can run the backup mount command to mount a backup in order to perform a recover operation by using an external tool.'
---
= The smsap backup mount command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the backup mount command to mount a backup in order to perform a recover operation by using an external tool.

== Syntax

----

        smsap backup mount 
-profile profile_name 
[-label label \[-data \| -archivelogs\] \| \[-id id\] 
[-host  host] 
 
\[-dump\]
[-quiet | -verbose]
----

== Parameters

* *-profile profile_name*
+
Specifies the profile associated with the backup that you want to mount. The profile contains the identifier of the database and other database information.

* *-id guid*
+
Mounts the backup with the specified GUID. The GUID is generated by SnapManager when you create a backup. You can use the smsap backup list command to display the GUID for each backup.

* *-label label*
+
Mounts the backup with the specified label.

* *-data*
+
Specifies the data files.

* *-archivelogs*
+
Specifies the archive log files.

* *-host host*
+
Specifies the host on which you want to mount the backup.

* *-dump*
+
Collects the dump files after the successful or failed mount operation.

* *-quiet*
+
Displays only error messages in the console. The default setting is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages in the console.

NOTE: You must use this command only if you are using an external tool such as Oracle Recovery Manager (RMAN). SnapManager automatically handles the mounting of backups if you use the smsap backup restore command to restore the backup. This command displays a list, which shows the paths where the Snapshot copies have been mounted. This list is displayed only when the -verbose option is specified.

== Example

The following example mounts the backup:

----
smsap backup mount -profile S10_BACKUP -label full_monthly_10 -verbose
[INFO ]: SMSAP-13051: Process PID=6852
[INFO ]: SMSAP-13036: Starting operation Backup Mount on host hadley.domain.private
[INFO ]: SMSAP-13036: Starting operation Backup Mount on host hadley.domain.private
[INFO ]: SMSAP-13046: Operation GUID 8abc01573883daf0013883daf5ac0001 starting on Profile FAS_P1
[INFO ]: SD-00025: Beginning to connect filesystem(s) [I:\] from snapshot smsap_fas_p1_fasdb_d_h_2_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SD-00016: Discovering storage resources for C:\SnapManager_auto_mounts\I-2012071400592328_0.
[INFO ]: SD-00017: Finished storage discovery for C:\SnapManager_auto_mounts\I-2012071400592328_0
[INFO ]: SD-00026: Finished connecting filesystem(s) [I:\] from snapshot smsap_fas_p1_fasdb_d_h_2_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SD-00025: Beginning to connect filesystem(s) [H:\] from snapshot smsap_fas_p1_fasdb_d_h_1_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SD-00016: Discovering storage resources for C:\SnapManager_auto_mounts\H-2012071400592312_0.
[INFO ]: SD-00017: Finished storage discovery for C:\SnapManager_auto_mounts\H-2012071400592312_0.
[INFO ]: SD-00026: Finished connecting filesystem(s) [H:\] from snapshot smsap_fas_p1_fasdb_d_h_1_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SMSAP-13048: Backup Mount Operation Status: SUCCESS
[INFO ]: SMSAP-13049: Elapsed Time: 0:19:05.620
----

*Related information*

xref:task_mounting_backups.adoc[Mounting backups]
