---
permalink: windows/reference_the_smosmsapcredential_delete_command.html
sidebar: sidebar
keywords: 
summary: 'This command deletes the user credentials for a particular secured resource.'
---
= The smsap credential delete command
:icons: font
:imagesdir: ../media/

[.lead]
This command deletes the user credentials for a particular secured resource.

== Syntax

----

        smsap credential delete 
\[-host -name host_name 
-username username\] \|  
[-repository 
-dbname repo_service_name 
-host repo_host 
-login -username repo_username 
-port repo_port\] \| 
\[-profile 
-name profile_name\] 
[-quiet | -verbose]
----

== Parameters

* *-host hostname*
+
Specifies the name of the host server on which SnapManager is running.
+
The -host parameter includes the following options:

 ** -name host_name: Specifies the name of the host for which you will delete the password.
 ** -username user_name: Specifies the user name on the host.

* *-repository -dbname*
+
Specifies the name of the database that stores the profile. Use either the global name or the SID.
+
The -repository parameter includes the following options:

 ** -dbnamerepo_service_name: Specifies the name of the database that stores the profile. Use either the global name or the SID.
 ** -host repo_host: Specifies the name or IP address of the host server the repository database runs on.
 ** -login-username repo_username: Specifies the user name needed to access the database that stores the repository.
 ** -port repo_port: Specifies the TCP port number used to access the database that stores the repository.

* *-profile -name profile_name*
+
Specifies the profile with which the database is associated.
+
The -profile parameter includes the following option:

 ** -name profilename: Specifies the name of the profile for which you will delete the password.

* *-quiet*
+
Displays only error messages on the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages on the console.

== Example command

This example deletes the credentials of the profile.

----
smsap credential delete -profile -name user1 -verbose
----

----
SMSAP-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----

This example deletes the credentials of the repository.

----
smsap credential delete -repository -dbname SMSAPREPO -host Host2
-login -username user1 -port 1521
----

----
SMSAP-20023 [INFO ]: Deleted repository credentials for "user1@SMSAPREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----

This example deletes the credentials of the host.

----
smsap credential delete -host -name Host2
----

----
SMSAP-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----

*Related information*

xref:task_deleting_credentials_for_individual_resources.adoc[Deleting credentials for individual resources]
