---
permalink: windows/reference_the_smosmsap_schedule_update_command.html
sidebar: sidebar
keywords: command, update, schedule, backup, smsap
summary: This command updates the schedule for a backup.
---
= The smsap schedule update command
:icons: font
:imagesdir: ../media/

[.lead]
This command updates the schedule for a backup.

== Syntax

----

        smsap schedule update
-profile profile_name
-schedule-name schedule_name
\[-schedule-comment schedule_comment\]
-interval \{-hourly \| -daily \| -weekly \| -monthly \| -onetimeonly\}
-cronstring cron_string
-start-time \{start_time <yyyy-MM-dd HH:mm\>\}
-runasuser runasuser
\[-taskspec taskspec\]
-force
\[-quiet \| -verbose\]
----

== Parameters

* *-profile profile_name*
+
Specifies the name of the profile related to the database you want to schedule the back up. The profile contains the identifier of the database and other database information.

* *-schedule-name schedule_name*
+
Specifies the name that you provide for the schedule.

* *-schedule-comment schedule_comment*
+
Specifies an optional comment to describe about scheduling the backup.

* *-interval { -hourly | -daily | -weekly | -monthly | -onetimeonly}*
+
Indicates the time interval by which the backups are created. You can schedule the backup on an hourly, daily, weekly, monthly, or one time only.

* *-cronstring cron_string*
+
Specifies to schedule the backup using cronstring. Cron expressions are used to configure instances of CronTrigger. Cron expressions are strings that are actually made up of seven sub-expressions:

 ** 1 refers to seconds
 ** 2 refers to minutes
 ** 3 refers to hours
 ** 4 refers to a day in a month
 ** 5 refers to the month
 ** 6 refers to a day in a week
 ** 7 refers to the year (optional)

* *-start-time yyyy-MM-dd HH:mm*
+
Specifies the start time of the schedule operation. The schedule start time should be included in the format of yyyy-MM-dd HH:mm.

* *-runasuser runasuser*
+
Specifies to change the user of the scheduled backup operation while scheduling the backup.

* *-taskspec taskspec*
+
Specifies the task specification XML file that can be used for pre-processing activity or post-processing activity of the backup operation. The complete path of the XML file should be provided which give the -taskspec option.
