---
permalink: windows/task-view-operation-details.html
sidebar: sidebar
keywords: view, detail, information, particular, profile, verify, success, failure, operation, resource, operation
summary: "You can view detailed information about a particular profile to verify the success or failure of an operation. It can also help you determine the storage resources in use for a particular operation."
---
= View operation details
:icons: font
:imagesdir: ../media/

[.lead]
You can view detailed information about a particular profile to verify the success or failure of an operation. It can also help you determine the storage resources in use for a particular operation.

== About this task

You can view the following details about a particular operation:

* Operation ID
* Type of operation
* Whether the operation was forced
* Runtime information, including status, start and end date of the operation
* The host on which the operation ran, including the Process ID and SnapManager version
* Repository information
* Storage resources in use

.Step

. To view the detailed information for a specific operation ID, enter the following command:
+
`*smsap operation show -profile _profile_name_ [-label _label_ | -id _id_] [-quiet | -verbose]*`
