---
permalink: windows/task-creating-repositories.html
sidebar: sidebar
keywords: snapmanager, require, repository, host, data, operation, perform, creating, create
summary: SnapManager requires a repository on a host to hold data about the operations you perform.
---
= Creating repositories
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager requires a repository on a host to hold data about the operations you perform.

Ensure that the following tasks are completed:

. Create an Oracle user and password in the repository database.
. Authorize user access to the repository.

For a repository, SnapManager for SAP requires a minimum 4K block size for the tablespace into which it is installed. You can check the block size using the following SQL command:

----
select a.username, a.default_tablespace, b.block_size
from dba_users a, dba_tablespaces b
a.username = repo_user
----

where

* a.default_tablespace = b.tablespace_name
* a.username = the user name on the repository

If you are upgrading repositories, you must reboot the SnapManager server to restart any associated schedules.

. To create the repository, enter the repository create command, using the following general format:
+
`smsap repository create -repository -dbname repo_service_name -host repo_host -login -username repo_username -port repo_port [-force] [-noprompt] [-quiet | -verbose]`
+
Where:

 ** -repository -dbname is the name of the repository database.
 ** -host is the name of the host for the repository.
 ** -username is the name of the database user who has access to the repository.
 ** -port is the port for the host.
Other options for this command are as follows:

+
[-force] [-noprompt]
+
[quiet | -verbose]
+
NOTE: If you have an existing repository with the same name and you use the -force option, all data within an existing repository schema will be overwritten.

== Creating a repository

The following command line creates a repository.

----
smsap repository create -repository -dbname HR1
-host server1 -login -username admin -port 1521
----
