---
permalink: windows/task-creating-or-updating-post-scripts.html
sidebar: sidebar
keywords: create, post, script, default, install, directory, plugin, creating, update, updating
summary: You can either create new post scripts or use the scripts available at default_install_directory\\plugins\\backup\\create\\post.
---
= Creating or updating the post scripts
:icons: font
:imagesdir: ../media/

[.lead]
You can either create new post scripts or use the scripts available at default_install_directory\plugins\backup\create\post.

You must structure the script in a particular manner so that it can be executed within the context of a SnapManager operation. Create the script based on the expected operations, available input parameters, and return code conventions.

. Create a new script or use the available sample scripts.
. Modify or include the functions, variables, and parameters as required.
. Save the custom script.
. Add the script name and required inputs in the post-processing task specification XML file or provide the inputs from the GUI by selecting the proper script and input parameter.
+
NOTE: You do not have to provide secondary storage details in the task specification XML file.

*Related information*

xref:concept-creating-task-specification-file-and-scripts-for-snapmanager-operations.adoc[Creating task specification file and scripts for SnapManager operations]
