---
permalink: windows/task_create_an_oracle_user_for_the_target_database.html
sidebar: sidebar
keywords: create, oracle, user, sysdba, role, connect, database, perform, operation, target
summary: "You need to create an Oracle user with the sysdba role that connects to the database and performs database operations."
---
= Create an Oracle user for the target database
:icons: font
:imagesdir: ../media/

[.lead]
You need to create an Oracle user with the sysdba role that connects to the database and performs database operations.

== About this task

SnapManager can use any Oracle user with sysdba privileges that exists in the target database, for example, the default "sys" user. You can also create a user in the target database to be used exclusively by SnapManager.

.Steps

. Log in to SQL *Plus.
+
At the command prompt, enter the following command:
+
`*sqlplus '/ as sysdba'*`

. To create a user, for example `_smsap_oper_` with the administrator password, for example, `_adminpw1_`, enter the following command at the SQL prompt:
+
`*SQL> create user _smsap_oper_ identified by _adminpw1_;*`
. Grant sysdba privileges to the Oracle user by entering the following command:
+
`*SQL> grant sysdba to _smsap_oper_;*`
