---
permalink: windows/task-using-post-processing-task-specification-to-vault-qtrees.html
sidebar: sidebar
keywords: snapmanager, sap, enable, script, vault, qtrees, backup, operation, windows, environment, post-process, task, specification
summary: SnapManager for SAP enables you to use the script to vault the qtrees after the backup operation takes place in a Windows environment.
---
= Using post-processing task specification to vault qtrees
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager for SAP enables you to use the script to vault the qtrees after the backup operation takes place in a Windows environment.

. Create a task specification XML file.
. In the XML file, enter the script name as an input parameter.
. Save the task specification XML file.
. Create a protected backup of the database to secondary storage using the following command.
+
While creating the protected backup, you must provide the complete path of the saved task specification XML file after the -taskspec option.
+
Example: smsapbackup create -profile test_profile -full -online -taskspec "C:\\mirror\\snapvault.xml"

The following example shows the post-processing task specification structure if you are using Data ONTAP operating in 7-Mode:

----
# <post-tasks>
#                <task>
#                  <name>Vault the backup</name>
#                   <description>Vault the backup</description>
#              </task>
#         <post-tasks>
----

The following example shows the post-processing task specification structure if you are using clustered Data ONTAP:

----
# <task-specification>
#                <post-tasks>
#                  <task>
#                   <name>"Vault the backup for cDOT"</name>
#                 <parameter>
#                    <name>SNAPSHOT_LABEL</name>
#                    <value>TST</value>
#                    </parameter>
#                  </task>
#                </post-tasks>
#              </task-specification>
#            </preposttask-specification>
----
