---
permalink: windows/task-clone-a-database-to-an-alternate-host.html
sidebar: sidebar
keywords: clone, command, database, alternate, host
summary: "You can use the clone create command to clone a database backup on an alternate host."
---
= Clone a database to an alternate host
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `clone create` command to clone a database backup on an alternate host.

== What you'll need

* Create a profile or have an existing profile.
* Create a full backup or have an existing database backup.
* Create a clone specification or have an existing clone specification.

.Step

. To clone a database to an alternate host, enter the following command:
+
`*smsap clone create -backup-label _backup_label_name -newsid _new_sid_ -host _target_host_ -label _clone_label_ -comment _comment_text_ -profile _profile_name_ -clonespec _full_path_to_clonespecfile_*`
+
Oracle does not let you run two databases with the same SID simultaneously on the same host. Because of this, you must supply a new SID for each clone. However, you can have a database on another host with the same SID.
