---
permalink: windows/task-create-oracle-users-for-the-repository-database.html
sidebar: sidebar
keywords: create, oracle, user, repository, database, assign, privilege, operation
summary: "You can create an Oracle user for the repository database and assign specific privileges to perform different operations on the repository database."
---
= Create Oracle users for the repository database
:icons: font
:imagesdir: ../media/

[.lead]
You can create an Oracle user for the repository database and assign specific privileges to perform different operations on the repository database.

== About this task

You must assign the connect and resource privileges to the Oracle user. You do not have to create a user for the repository database with sysdba privileges.

NOTE: However, you must create an Oracle user with the sysdba role for the target database.

.Steps

. Log in to SQL *Plus.
+
At the command prompt, enter the following command:
+
`*sqlplus '/ as sysdba'*`
+
----
SQL*Plus: Release 11.2.0.1.0 Production on Wed Jun 1 06:01:26 2011
Copyright (c) 1982, 2009, Oracle.  All rights reserved.
Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - Production
With the Partitioning, Automatic Storage Management, OLAP, Data Mining
and Real Application Testing options
----

. To create a user, for example `_repo1_user_`, for the repository with the administrator password, for example, `_adminpw1_`, enter the following command at the SQL prompt:
+
`*SQL> create user _repo1_user_ identified by _adminpw1_;*`
. To grant connect and resource privileges to the user, enter the following command:
+
`*grant connect, resource to _repo1_user_;*`
