---
permalink: windows/task_free_backups.html
sidebar: sidebar
keywords: free, backup, delete, snapshot, copies, copy, metadata, function, space, smsap
summary: "You can free backups, which deletes the Snapshot copies without deleting the backup metadata. This function frees the space occupied by the backup. You can use the smsap backup free command to free the backups."
---
= Free backups
:icons: font
:imagesdir: ../media/

[.lead]
You can free backups, which deletes the Snapshot copies without deleting the backup metadata. This function frees the space occupied by the backup. You can use the smsap `backup free` command to free the backups.

== What you'll need

For a backup to be eligible for freeing, you must ensure the following:

* Backup was successful
* Backup is not to be mounted
* Backup does not have clones
* Backup is not to be retained by using an unlimited retention policy
* Backup is not already freed

== About this task

You can specify the `-dump` option as an optional parameter to collect the dump files after the successful or failed backup free operation.

.Step

. Enter the following command:
+
`*smsap backup free -profile _profile_name_ {-label _label_ [data | -archivelogs] | -id _id_ | -all} -force[-dump] [-quiet] [-force]*`
