---
permalink: windows/task-viewing-a-list-of-operations.html
sidebar: sidebar
keywords: view, summary, listing, operation, perform, profile, list
summary: You can view a summary listing of all the operations performed against a profile.
---
= Viewing a list of operations
:icons: font
:imagesdir: ../media/

[.lead]
You can view a summary listing of all the operations performed against a profile.

You can view the following information when you list operations associated with a particular profile:

* Start and end date when the operation ran
* Operation status
* Operation ID
* Type of operation
* Host that it ran upon

.Step
. To list the summary information of all the operations, use the following command:
+
`smsap operation list profile -profile profile_name -delimitercharacter [-quiet | -verbose]`
+
When the -delimiter option is specified, the command lists each row on a separate line and the attributes in that row are separated by the character specified.

*Related information*

xref:reference-the-smosmsapoperation-list-command.adoc[The smsap operation list command]
