---
permalink: windows/task_clearing_user_credentials_for_all_hosts_repositories_and_profiles.html
sidebar: sidebar
keywords: 
summary: 'You can clear the cache of your credentials for resources \(hosts, repositories, and profiles\). This deletes all of the resource credentials for the user running the command. After clearing the cache, you must authenticate your credentials again to gain access to these secured resources.'
---
= Clearing user credentials for all hosts, repositories, and profiles
:icons: font
:imagesdir: ../media/

[.lead]
You can clear the cache of your credentials for resources (hosts, repositories, and profiles). This deletes all of the resource credentials for the user running the command. After clearing the cache, you must authenticate your credentials again to gain access to these secured resources.

. To clear your credentials, enter the smsap credential clear command from the SnapManager CLI or select *Admin* > *Credentials* > *Clear Cache* from the SnapManager GUI.
. Exit the SnapManager GUI.
+
NOTE:

 ** If you have cleared the credential cache from the SnapManager GUI, you do not need to exit the SnapManager GUI.
 ** If you have cleared the credential cache from the SnapManager CLI, you must restart SnapManager GUI.
 ** If you have deleted the encrypted credential file manually, you must restart the SnapManager GUI again.

. To set the credentials again, repeat the process to set credentials for the repository, profile host, and profile. For additional information on setting the user credentials again, refer to "Setting credentials after clearing credential cache."

*Related information*

xref:reference_the_smosmsapcredential_clear_command.adoc[The smsap credential clear command]
