---
permalink: windows/task_create_restore_specifications.html
sidebar: sidebar
keywords: restore, specification, file, sml, contain, original, alternate, location, snapmanager, location, create
summary: "The restore specification file is an XML file that contains the original and alternate locations from which the file can be restored. SnapManager uses this specification file to restore files from the specified location."
---
= Create restore specifications
:icons: font
:imagesdir: ../media/

[.lead]
The restore specification file is an XML file that contains the original and alternate locations from which the file can be restored. SnapManager uses this specification file to restore files from the specified location.

== About this task

You can create the restore specification file by using any text editor. You must use a .xml extension for the file.

.Steps

. Open a text file.
. Enter the following:
+
`+<restore-specification xmlns="http://www.netapp.com">+`
. Enter any file mapping information using the format shown in the following example:
+
----
<file-mapping>
    <original-location>E:\disks\sysaux.dbf</original-location>
    <alternate-location>E:\disks\sysaux.dbf</alternate-location>
</file-mapping>
----
+
File mapping specifies where a file is restored from. The original location is the location of the file on the active file system at the time of backup. The alternate location is the location from where the file is restored.

. Enter any mounted file system mapping information using the format shown in the example:
+
----
<mountpoint-mapping>
     <original-location>E:\disks\sysaux.dbf</original-location>
     <snapname>snapname</snapname>
     <alternate-location>E:\disks\sysaux.dbf</alternate-location>
</mountpoint-mapping>
----
+
Mountpoint refers to directory path `C:\myfs`. The mountpoint mapping specifies the mountpoint from which the files are restored. The original location is the location of the mountpoint in the active file system at the time of backup. The alternate location is the mountpoint from which the files in the original location are restored. The `snapname` is the name of the Snapshot copy in which the original files were backed up.
+
NOTE: The Snapshot copy name is a necessary component because the same file system can be used multiple times in a single backup operation (for example, once for the data files and once for the logs).

. Enter the following:
+
`*</restore-specification>*`
. Save the file as a .xml file and close the specification.
