---
permalink: windows/task-download-and-start-the-graphical-user-interface-using-java-web-start-windows.html
sidebar: sidebar
keywords: java, web, start, snapmanager, install, host, download, graphical, user, interface, gui, jre
summary: "You can use Java Web Start if SnapManager is not installed on the host. Java Web Start downloads SnapManager components and starts the graphical user interface (GUI). The supported JRE versions are 1.5, 1.6, and 1.7."
---
= Download and start the graphical user interface using Java Web Start
:icons: font
:imagesdir: ../media/

[.lead]
You can use Java Web Start if SnapManager is not installed on the host. Java Web Start downloads SnapManager components and starts the graphical user interface (GUI). The supported JRE versions are 1.5, 1.6, and 1.7.

== What you'll need

You must ensure that the following conditions are met:

* The SnapManager server is running.
* A web browser window is open.

.Steps

. In the Microsoft Internet Explorer Web browser window, enter `+https://smsap-server.domain.com:port+`.
+
`smsap-server.domain.com` is the fully qualified host name and domain on which you installed SnapManager and `port` is the listening port for the SnapManager server (27314, by default).
+
NOTE: You must enter `https` in the browser window.
+
`A dialog box with the message There is a problem with the site's security certificate...Do you want to proceed?` is displayed.

. Click *Yes* or *Continue*.
. Click on the link labeled *Click here to download and install JRE 6.0 and the application*.
+
A link labeled Download Java Web Start with the message `This site might require the following ActiveX control: Java Plug-in 1.6"... "Click here to install` is displayed.

. In the *Install* window, perform the following steps:
 .. Click the message labeled `Click here to install....`
+
An *Install ActiveX Control* menu is displayed.

 .. Select *Install ActiveX Control...*.
+
The message `Internet Explorer - Security Warning" containing the following text: "Do you want to install this software? Name: Java Plug-in 1.6` is displayed.

 .. Click *Install*.
+
A "Java Plug-in 1.6." window for the installer for J2SE Runtime Environment 1.6 is displayed.

 .. Click *Install*.

+
A window requesting you to install J2SE Runtime Environment 1.6 is displayed.
. In the Install window, perform the following steps:
 .. On the *License Agreement* page, select *I accept the terms in the license agreement* and click *Next*.
 .. On the *Setup Type* page, select *Typical* and click *Next*.
 .. On the *Installation Completed* window, click *Finish*.
+
SnapManager begins to download.

+
A File Download dialog box with the message `Do you want to save this file? application.jnlp` is displayed.
. In the *file download* window, perform the following steps:
 .. Install the latest version of JRE 1.6 on the Windows client.
 .. Verify that Java is installed by running the following command: `java -version`
+
The output should indicate Java version 1.6.0_24 (which is Java 1.6) or later.

 .. Change your Windows configuration settings to always open files with extension jnlp with the program Java Web Start Launcher.
+
The steps to change the Windows configuration settings varies based on the version of Windows you are using.

 .. Enter the SnapManager URL that you have specified in the step 1.

+
The SnapManager download starts on the Windows client and a Warning - security dialog box is displayed.
. Perform the following steps.
+
The message contents and button labels vary based on platform.

 .. In the *Warning - Security* dialog box, click *Yes*.
+
A dialog box is displayed.

 .. In the host name mismatch dialog box, click *Run*.
+
The Warning - Security dialog box with a message about the signature of the SnapManager application is displayed.

 .. Click *Run*.
+
A dialog box with the title Java Installer - Security Warning and the message `Warning Security - the application's digital signature has an error. Do you want run the application`, is displayed.

 .. Click *Run*.
+
The browser downloads and starts the SnapManager for SAP GUI.
