---
permalink: windows/task_updating_profiles.html
sidebar: sidebar
keywords: update, profile, modify, password, backup, database, operating, system, authentication, information, host, oracle, updating
summary: You can update the profiles to modify the profile password, the number of backups to retain, access to the database, the operating system \(OS\) authentication to database authentication and vice versa, and information about the host. If the Oracle database password information changes, you must also change that information in the profile.
---
= Updating profiles
:icons: font
:imagesdir: ../media/

[.lead]
You can update the profiles to modify the profile password, the number of backups to retain, access to the database, the operating system (OS) authentication to database authentication and vice versa, and information about the host. If the Oracle database password information changes, you must also change that information in the profile.

SnapManager (3.2 or later) enables you to update the profile to separate archive log backups from the data file backups by using the -separate-archivelog-backups option. You can specify separate retention duration for the archive log backup. SnapManager enables you to include the archive log backup along with online database backup. You can also create an online datafile backup and archive log backup together for cloning. When you create an online data files backup, the archive logs backups are immediately created along with the data files.

. Enter the following command: `smsap profile update -profileprofile [-new-profilenew_profile_name] [-profile-passwordprofile_password][-database-dbnamedb_dbname-host db_host [-siddb_sid] [-login -usernamedb_username-password db_password-port db_port]] [{-rman{-controlfile | {-login  -usernamerman_username-password  rman_password-tnsname  rman_tnsname}}} | -remove-rman] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern] [-summary-notification] [-notification [-success-emailemail_address1, email_address2-subjectsubject_pattern] [-failure-emailemail_address1, email_address2-subjectsubject_pattern]] [-separate-archivelog-backups-retain-archivelog-backups-hourshours | -daysdays | -weeksweeks| -monthsmonths [-include-with-online-backups | -no-include-with-online-backups]] [-dump]`
+
Other options for this command are as follows:
+
[-force] [-noprompt]
+
[quiet | verbose]
+
[options="header"]
|===
| If you want to...| Then...
a|
*Change the backup retention policy for backups of the database in the profile*
a|
Specify either the retention count or retention duration for a retention class, or both to change the retention policy. The duration is in units of the class (for example, hours for hourly, days for daily).

 ** -hourly is the hourly retention class, for which [-countn] [-durationm]] are the retention count and retention duration, respectively.
 ** -daily is the daily retention class, for which [-countn] [-durationm]] are the retention count and retention duration, respectively.
 ** -weekly is the weekly retention class, for which [-countn] [-durationm]] are the retention count and retention duration, respectively.
 ** -monthly is the monthly retention class, for which [-countn] [-durationm]] are the retention count and retention duration, respectively.

a|
*Enable email notifications for the completion status of the database operations*
a|
Specify the following options and variables:

 ** -summary-notification enables you to configure a summary email notification for multiple profiles under a repository database.
 ** -notification enables you to receive an email notification on the completion status of the database operation for a profile.
 ** -success-emailemail_address2 enables you to receive an email notification following the completion of a successful database operation performed by using a new or an existing profile.
 ** -failure-emailemail_address2 enables you to receive an email notification on a failed database operation performed by using a new or an existing profile.
 ** -subjectsubject_text specifies subject text for the email notification while creating a new profile or an existing profile.
If the notification settings are not configured for the repository and you are trying to configure profile or summary notifications by using the command-line interface (CLI), the following message is logged in the console log: SMSAP-14577: Notification Settings not configured.

+
If you have configured the notification settings and you are trying to configure summary notification by using the CLI without enabling summary notification for the repository, the following message is logged in the console log: __**__SMSAP-14575: Summary notification configuration not available for this repository
a|
*Update the profile to create backup of the archive log files separately*
a|
Specify the following options and variables:

 ** -separate-archivelog-backups enables you to create a backup of the archive log files separately from the database files.
+
After you specify this option, you can either create a data files-only backup or an archivelogs-only backup. You cannot create a full backup. Also, you cannot revert the profile settings by separating the backup. SnapManager retains the backups based on the retention policy for the backups that were created before taking archivelogs-only backup.

 ** -retain-archivelog-backups sets the retention duration for archive log backups.
+
NOTE: If you are updating the profile for the first time, you can separate the archive log backups from the data files backup by using the -separate-archivelog-backups option; you must provide the retention duration for the archive log backups by using the -retain-archivelog-backups option. Setting the retention duration is optional when you later update the profile.

 ** -include-with-online-backups specifies that the archive log backup is included along with the database backup.
 ** -no-include-with-online-backups specifies the archive log file backup is not included along with the database backup.

a|
*Change the host name of the target database*
a|
Specify -hostnew_db_host to change the host name of the profile.
a|
*Collect the dump files after the profile update operation*
a|
Specify the -dump option.
|===

. To view the updated profile, enter the following command: smsap profile show

*Related information*

xref:concept_how_to_collect_dump_files.adoc[How to collect dump files]
