---
permalink: windows/task-customize-e-mail-subject-for-a-new-profile.html
sidebar: sidebar
keywords: customize, email, subject, profile, create, cusomtizing
summary: You can customize the email subject for the new profile when you create it.
---
= Customize the email subject for a new profile
:icons: font
:imagesdir: ../media/

[.lead]
You can customize the email subject for the new profile when you create it.

== About this task

You can customize the email subject by using the \{profile}_\{operation-name}_\{db-sid}_\{db-host}_\{start-date}_\{end-date}_\{status} pattern or enter your own text.

[options="header"]
|===
| Variable name| Description| Example value
a|
`profile`
a|
Profile name used for the database operation
a|
PROF1
a|
`operation-name`
a|
Database operation name
a|
Backup, Data Backup, Data and Archive Logs Backup
a|
`db-sid`
a|
SID of the database
a|
DB1
a|
`db-host`
a|
Name of the host server
a|
hostA
a|
`start-date`
a|
Start time of the database operation in the mmdd:hh:ss yyyy format
a|
April 27 21:00:45 PST 2012
a|
`end-date`
a|
End time of the database operation in the mmdd:hh:ss yyyy format
a|
April 27 21:10:45 PST 2012
a|
`status`
a|
Database operation status
a|
Success
|===
If you do not provide any value for the variables, then SnapManager displays the following error message: `Missing value(s) -subject`.

.Step

. Enter the following command:
+
`*smsap profile create -profile _profile_ [-profile-password _profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login -username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login-username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login -username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname -pattern _pattern_][ [ ]] [-notification [-success -email _email_address1_, _email_address2_ -subject _subject_pattern_] [-failure -email _email_address1_, _email_address2_ -subject _subject_pattern_]]*`
