---
permalink: windows/task_updating_target_database_hostname_associated_with_a_profile.html
sidebar: sidebar
keywords: snapmanager, sap, provide, ability, update, host, name, target, database, profile, updating, associate
summary: SnapManager \(3.2 or later\) for SAP provides the ability to update the host name of the target database in the SnapManager profile.
---
= Updating the target database host name associated with a profile
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager (3.2 or later) for SAP provides the ability to update the host name of the target database in the SnapManager profile.

* The local user's home directory must be aware of the profile-to-repository mappings.
* The SnapManager graphical user interface (GUI) sessions must be closed.

You can update the profile with the new host name by using only the CLI.

*Scenarios not supported for changing the target database host name in profile*

The following scenarios not supported for changing the target database host name in the profile:

* Changing the target database host name by using the SnapManager GUI
* Rolling back of the repository database after updating the target database host name of the profile
* Updating multiple profiles for a new target database host name by running a single command
* Changing the target database host name when any SnapManager operation is running

NOTE: After you update the target database host name in the profile, only the target database host name is changed. All the other configuration parameters set on the profile are retained.

After you update the target database host name, you cannot delete or unmount the backup if the clone or mounted backup is not available in the new host. In such scenarios, running the SnapManager operations from the new host lead to failure as well as stale entries in the earlier host. To perform SnapManager operations, you must revert to the earlier host name by using profile update.

. Enter the following command: `smsap profile update -profileprofile [-profile-passwordprofile_password][-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port]] [{-rman{-controlfile | {-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname}}} | -remove-rman] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][-summary-notification] [-notification [-success-emailemail_address1, email_address2-subjectsubject_pattern] [-failure-emailemail_address1, email_address2-subjectsubject_pattern]] [-separate-archivelog-backups-retain-archivelog-backups-hourshours | -daysdays | -weeksweeks| -monthsmonths [-protect [-include-with-online-backups | -no-include-with-online-backups]] [-dump]`
+
Other options for this command are as follows:
+
[-force] [-noprompt]
+
[quiet | -verbose]
+
|===
| If you want to...| Then...
a|
*Change the target database host name*
a|
Specify -hostnew_db_host
|===

. To view the target database host name of the profile, enter the following command: `smsap profile show`
