---
permalink: windows/task_previewing_backup_restore_information.html
sidebar: sidebar
keywords: 
summary: 'You can preview information about a backup restore process before it occurs to see information about restore eligibility that SnapManager for SAP found on your backup. SnapManager analyzes data on your backup to determine whether the restore process can be completed successfully.'
---
= Previewing backup restore information
:icons: font
:imagesdir: ../media/

[.lead]
You can preview information about a backup restore process before it occurs to see information about restore eligibility that SnapManager for SAP found on your backup. SnapManager analyzes data on your backup to determine whether the restore process can be completed successfully.

The restore preview provides the following information:

* Which restore mechanism (storage-side file system restore, storage-side file restore, or host-side file copy restore) can be used to restore each file.
* Why more efficient mechanisms were not used to restore each file, when you specify the -verbose option.

If you specify the-preview option in the backup restore command, SnapManager does not restore anything, but lists the files to be restored and indicates how they will be restored.

NOTE: You can preview all types of restore mechanisms. The preview shows information about up to 20 files.

. Enter the following command:``smsap backup restore -profileprofile_name-labellabel-complete -preview -verbose``
+
For example, enter:
+
----
smsap backup restore -profile targetdb1_prof1
      -label full_bkup_sales_nov_08  -complete -preview -verbose
----
+
The following example shows the files ready to be restored and lists the different methods used for each:
+
----
The following files will be restored via storage side full file system
restore:
E:\disks\sysaux.dbf
E:\disks\system.dbf

The following files will be restored via host side file copy restore:
E:\disks\undotbs1.dbf
E:\disks\undotbs2.dbf
----

. Review any reasons why other restore processes cannot be used.
. Begin the restore operation without the -preview option, if only reasons that are overridable are displayed.
+
You can still override non-mandatory checks.
