---
permalink: windows/task_upgrade_snapmanager_for_oraclesnapmanager_for_sap_hosts.html
sidebar: sidebar
keywords: upgrade, exist, snapmanager, host, version, simultaneous, result, downtime, schedule, operation, time
summary: "You can upgrade all the existing SnapManager hosts to use the latest version of SnapManager. All the hosts are upgraded simultaneously. However, this might result in downtime of all the SnapManager hosts and the scheduled operations during that time."
---
= Upgrade SnapManager hosts
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade all the existing SnapManager hosts to use the latest version of SnapManager. All the hosts are upgraded simultaneously. However, this might result in downtime of all the SnapManager hosts and the scheduled operations during that time.

.Steps

. Stop the SnapManager server by performing the following steps:
 .. In the *Windows Services* window, select *NetApp SnapManager for SAP*.
 .. In the left panel, click *Stop*.
. Double-click the SnapManager installation file.
+
[options="header"]
|===
| If the operating system is...| Then use...
a|
Windows x86
a|
`netapp.smsap.windows-x86-version_number.exe`
a|
Windows x64
a|
`netapp.smsap.windows-x64-version_number.exe`
|===
The following message is displayed: `The publisher could not be verified. Are you sure you want to run this software?`

. Click *OK*.
+
The Introduction window is displayed.

. Click *Next*.
+
The Choose Install Folder window is displayed.

. Click *Next* to accept the default installation location or select a new location.
+
The default location is: `C:\Program Files\NetApp\SnapManager for SAP`.

. In the *Menu Availability* window, click *Next*.
. In the *Specify Service Properties* window, enter the account and password information for Windows service.
+
The specified account must be a member of the following groups:

 ** The storage system's local administration group
 ** The local administrator's group
 ** The ORA_DBA group
You can specify if the service must start automatically after reboot or the service must be started manually.

. In the *Pre-Installation Summary* window, click *Install*.
. In the *Install Complete* window, click *Next*.
. In the *Important Information* window, click *Done* to exit the installer.
