---
permalink: unix-administration/concept_dump_files.html
sidebar: sidebar
keywords: 
summary: 'The dump files are compressed log files containing information about SnapManager and its environment. The different types of log files created are operation, profile, and system dump file.'
---
= Dump files
:icons: font
:imagesdir: ../media/

[.lead]
The dump files are compressed log files containing information about SnapManager and its environment. The different types of log files created are operation, profile, and system dump file.

You can use the dump command or the *Create Diagnostics* tab in the graphical user interface (GUI) to collect information about an operation, a profile, or the environment. A system dump does not require a profile; however, the profile and operation dumps require profiles.

SnapManager includes the following diagnostic information in the dump file:

* The steps performed
* The length of time for each step to complete
* The outcome of each step
* Error, if any, that occurred during the operation

NOTE: SnapManager log files or dump files enable read and write permissions only for the root users and the other users who belong to root user group.

SnapManager also includes the following information in the file:

* Operating system version and architecture
* Environment variables
* Java version
* SnapManager version and architecture
* SnapManager preferences
* SnapManager messages
* log4j properties
* SnapDrive version and architecture
* SnapDrive log files
* Oracle version
* Oracle OPatch local inventory details
* Automatic Storage Management (ASM) instance OPatch local inventory details
* Storage system version
* Oracle oratab file
* Oracle listener status
* Oracle network configuration files (listener.ora and tnsnames.ora)
* Repository database Oracle version
* Target database type (stand aloneor Real Application Clusters (RAC))
* Target database role (primary, physical standby, or logical standby)
* Target database Oracle Recovery Manager (RMAN) setup (no RMAN integration, RMAN with control files, or RMAN with catalog file)
* Target database ASM instance version
* Target database Oracle version
* System identifier (SID) of the target database
* Repository database service name
* Database instances installed on the host
* Profile descriptor
* Shared memory maximum
* Swap space information
* Memory information
* Kernel version
* FSTAB
* Protocol used by Snapdrive
* Multipath environment
* RAC
* Supported volume manager
* Operations Manager version
* Supported file system
* Host utilities version
* BACKINT interface versions
* BR tool version
* Patch level
* Output of the system verify command
* Output of the sdconfcheck command

SnapManager dump files also contain the SnapDrive data collector file and the Oracle alert log file. You can collect the Oracle alert log file by using the smsap operation dump and smsap profile dump commands.

NOTE: System dump does not contain Oracle alert logs; however, the profile and operation dumps contain the alert logs.

Even if the SnapManager host server is not running, you can access the dump information by using the command-line interface (CLI) or the GUI.

If you encounter a problem that you cannot resolve, you can send these files to NetApp Global Services.
