---
permalink: unix-administration/concept_scheduling_database_backups.html
sidebar: sidebar
keywords: snapmanager, sap, enable, schedule, database, backup, off-peak, hour, scheduling, retention, policy
summary: "SnapManager (3.2 or later) for SAP enables you to schedule database backups to occur on a regular basis during off-peak hours to maintain high performance. To schedule a backup, you can create a profile, which includes the database information and retention policy, and then set schedules for the backup."
---
= Scheduling database backups
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager (3.2 or later) for SAP enables you to schedule database backups to occur on a regular basis during off-peak hours to maintain high performance. To schedule a backup, you can create a profile, which includes the database information and retention policy, and then set schedules for the backup.

NOTE: You must schedule the backups as either a root user or an Oracle user. If you try to schedule the backups as a non-existing user, SnapManager displays an error message: Invalid user: username: Cannot create schedule backup for a given user

The following are some of the schedule-related tasks:

* Schedule a database backup to occur on an hourly, daily, weekly, monthly, or one-time basis.
* View a list of scheduled backups associated with a profile.
* Update a scheduled backup.
* Suspend a schedule temporarily.
* Resume the suspended schedule.
* Delete a schedule.

NOTE: The *Run Now Menu Operation* check box is disabled when a scheduled backup is running for that schedule.
