---
permalink: unix-administration/concept_snapshot_copy_naming.html
sidebar: sidebar
keywords: naming, name, snapshot, copy, convention, pattern, copies
summary: "You can specify a naming convention or pattern to describe the Snapshot copies related to the profile you create or update. You can also include custom text in all Snapshot copy names."
---
= Snapshot copy naming
:icons: font
:imagesdir: ../media/

[.lead]
You can specify a naming convention or pattern to describe the Snapshot copies related to the profile you create or update. You can also include custom text in all Snapshot copy names.

You can change the Snapshot copy naming pattern when you create a profile or after the profile has been created. The updated pattern applies only to Snapshot copies that have not yet occurred; Snapshot copies that exist retain the previous snapname pattern.

The following examples show the two Snapshot copy names taken for a volume. The second Snapshot copy listed has _F_H_1_ in the middle of its name. The "1" indicates that it is the first Snapshot copy taken in the backup set. The first Snapshot copy listed is the most recent and has a "2," which means it is the second Snapshot copy taken. The "1" Snapshot copy includes the datafiles; the "2" Snapshot copy includes the control files. Because the control file Snapshot copies must be taken after the data file Snapshot copy, two Snapshot copies are required.

----
smsap_profile_sid_f_h_2_8ae482831ad14311011ad14328b80001_0
smsap_profile_sid_f_h_1_8ae482831ad14311011ad14328b80001_0
----

The default pattern includes the required smid, as shown in the following:

* Default pattern: smsap_\{profile}_\{db-sid}_\{scope}_\{mode}_\{smid}
* Example: smsap_my_profile_rac51_f_h_2_8abc01e915a55ac50115a55acc8d0001_0

You can use the following variables in the Snapshot copy name:

[cols="1a,3a,2a" options="header"]
|===
| Variable name| Description| Example value
a|
smid (Required)
a|
The SnapManager unique ID is the only required element when creating a name for the Snapshot copy. This ID ensures that you create a unique Snapshot name.
a|
8abc01e915a55ac50115a55acc8d0001_0
a|
class (Optional)
a|
Retention class associated with the backup for the profile and indicated by hourly (h), daily (d), weekly (w), monthly (m), or unlimited (u).
a|
d
a|
comment (Optional)
a|
Comment associated with the backup for the profile. Spaces in this field will be converted to underscores when the Snapshot copy name is complete.
a|
sample_comment_spaces_replaced
a|
date (Optional)
a|
Date that the backup occurs for the profile. Date values are padded with zeros if necessary. (yyyymmdd)
a|
20070218
a|
db-host (Optional)
a|
Database host name associated with the profile being created or updated.
a|
my_host
a|
db-name (Optional)
a|
Database name associated with the Snapshot copy you create.
a|
rac5
a|
db-sid (Optional)
a|
Database sid associated with the Snapshot copy you create.
a|
rac51
a|
label (Optional)
a|
Label associated with the backup for the profile.
a|
sample_label
a|
mode (Optional)
a|
Specifies whether the backup is completed online (h) or offline (c).
a|
h
a|
profile (Optional)
a|
Profile name associated with the backup you create.
a|
my_profile
a|
scope (Optional)
a|
Specifies whether the backup is either full (f) or partial (p).
a|
f
a|
time (Optional)
a|
Time that the backup occurs for the profile. Time values for this variable use the 24-hour clock and are padded with zeros if necessary. For example, 5:32 and 8 seconds appears as 053208 (hhmmss).
a|
170530
a|
time-zone (Optional)
a|
Time zone specified for the target database host.
a|
EST
a|
usertext (Optional)
a|
Custom text that you can enter.
a|
prod
|===
*Note:* SnapManager for SAP does not support the colon (:) symbol in the long forms of the names for Snapshot copies.
