---
permalink: unix-administration/concept_snapmanager_for_oraclesnapmanager_for_sap_uses_protection_manager_to_protect_a_database_backup.html
sidebar: sidebar
keywords: snapmanager, sap, protection, manager, install, unix, host, server, respectively, database, administrator, dba, primary, storage, backup
summary: "SnapManager for SAP and Protection Manager, when installed on a UNIX host and on the server respectively, give the SnapManager database administrator (DBA) the ability to configure and carry out policy-based Oracle database backups to secondary storage, and to restore, if necessary, the backed up data from secondary to primary storage."
---
= SnapManager for SAP uses Protection Manager to protect a database backup
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager for SAP and Protection Manager, when installed on a UNIX host and on the server respectively, give the SnapManager database administrator (DBA) the ability to configure and carry out policy-based Oracle database backups to secondary storage, and to restore, if necessary, the backed up data from secondary to primary storage.

In the following example, a DBA, who is using SnapManager, creates a profile for a local backup on primary storage and another profile for a protected backup to secondary storage. Then this DBA works with his network storage administrator, who is using the Protection Manager's console, to configure a policy-based backup of that database from primary to secondary storage.
