---
permalink: unix-administration/concept-backup-schedule-and-retention-strategy.html
sidebar: sidebar
keywords: dba, ensure, backup, loss, data, disaster, regulatory, reason, retention, policy, database, schedule
summary: "The DBA wants to ensure that backups are available in case of a loss of data, in case of a disaster, and for regulatory reasons. This requires a carefully thought out retention policy for the various databases."
---
= Backup schedule and retention strategy
:icons: font
:imagesdir: ../media/

[.lead]
The DBA wants to ensure that backups are available in case of a loss of data, in case of a disaster, and for regulatory reasons. This requires a carefully thought out retention policy for the various databases.

For the production payroll database, the DBA adheres to the following TechCo retention strategy:

[cols="1a,1a,1a,1a" options="header"]
|===
| Backup frequency| Retention duration| Backup time| Type of storage
a|
Once daily
a|
10 days
a|
7 p.m.
a|
Primary (local)
a|
Once daily
a|
10 days
a|
7 p.m.
a|
Secondary (archive)
a|
Once weekly
a|
52 weeks
a|
Saturdays 1 a.m.
a|
Secondary (archive)
|===

* *Local backup advantages*
+
Daily local backup provides database protection, which is instantaneous, uses zero network bandwidth, uses a minimum of additional storage space, provides instantaneous restore, and provides finely-grained backup and restore capability.
+
Because the final weekly backups of the payroll database are retained for a minimum 52 weeks at a secondary storage site, there is no need to retain the daily backups any longer than 10 days.

* *Protected backup advantages*
+
Daily and weekly backups to secondary storage at a remote location guarantee that if the data at the primary storage site is damaged, the target database is still protected and can be restored from secondary storage.
+
The daily backups to secondary storage are made to protect against primary storage system damage. Because the final weekly backups of the payroll database are retained for a minimum 52 weeks, there is no need to retain the daily backups any longer than 10 days.
