---
permalink: unix-administration/concept_splitting_a_clone.html
sidebar: sidebar
keywords: snapmanager, enable, split, manage, clone, exist, flexclone, technology, data, block, database
summary: "SnapManager enables you to split and manage an existing clone that was created by using the FlexClone technology. In the FlexClone technology, the clone and original database share the same physical data blocks."
---
= Splitting a clone
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager enables you to split and manage an existing clone that was created by using the FlexClone technology. In the FlexClone technology, the clone and original database share the same physical data blocks.

Before you perform the clone split operation, you can know that the estimated size of the clone to be split and the required space available on the aggregate.

A new profile is generated by SnapManager if the clone split operation is successful. If SnapManager fails to create the new profile, you can manually create a new profile. You can use the new profile to create database backups, restore data, and create clones. If the clone split operation is successful, irrespective of whether the new profile is created or not, the clone-related metadata is removed from the repository database.

You can perform the following tasks related to splitting clones:

* View the clone split estimate.
* Split a clone on a primary storage.
* Split a clone on a secondary storage.
* View the clone split operation status.
* Stop the clone split operation.
* Destroy the profile along with the underlying storage.
* Delete the profile created for a split clone.

When you split a clone from its parent volume, the Snapshot copies associated with the cloned volume are deleted. The backups created for the cloned database before the clone split process cannot be used because the Snapshot copies of these backups are deleted, and the backups remain as stale entries in the repository.
