---
permalink: unix-administration/concept_general_layout_and_configuration.html
sidebar: sidebar
keywords: 
summary: 'Knowing the recommended general database layouts and storage configurations can help you avoid issues related to disk groups, file types, and tablespaces.'
---
= Recommended general database layouts and storage configurations
:icons: font
:imagesdir: ../media/

[.lead]
Knowing the recommended general database layouts and storage configurations can help you avoid issues related to disk groups, file types, and tablespaces.

* Do not include files from more than one type of SAN file system or volume manager in your database.
+
All files making up a database must reside on the same type of file system.

* SnapManager requires a multiple of 4K block size.
* Include the database system identifier in the oratab file.
+
Include an entry in the oratab file for each database to be managed. SnapManager relies on the oratab file to determine which Oracle home to use.

If you want to leverage the new volume-based restore or full disk group restore, consider the following guidelines related to file systems and disk groups:

* A disk group containing data files cannot contain other types of files.
* The logical unit number (LUN) for the data file disk group must be the only object in the storage volume.

The following are some guidelines for volume separation:

* Data files for only one database must be in the volume.
* You must use separate volumes for each of the following file classifications: database binaries, data files, online redo log files, archived redo log files, and control files.
* You do not need to create a separate volume for temporary database files because SnapManager does not back up temporary database files.

SAP uses a standard layout for Oracle database installations. In this layout, SAP places copies of the Oracle control file in E:\oracle\SID\origlogA, E:\oracle\SID\origlogB, and E:\oracle\SID\sapdata1 file systems.

The control file in the sapdata1 file system conflicts with the SnapManager requirements for separating the control files and data files into separate volumes and must be adjusted to allow fast restore capability.

NOTE: Because BR*Tools backups include the Oracle and SAP profiles located in the dbs subdirectory of the Oracle installation, the Oracle installation must be located on storage.

In the case of a new installation, you can modify the location of the control files by using SAPINST and move the control file normally placed in the sapdata1 file system to a file system that does not reside in the same volume as the data files. (SAPINST is the tool that SAP provides for installing SAP systems.)

However, in the case of a system that has already been installed, you must move the control file from the file system to allow fast restore using SnapManager. You can do this by creating a new file system in a volume that does not contain data files, moving the control file to that file system, and then creating a symbolic link from the previous file system to the directory for the new file system. It is necessary to stop SAP and the Oracle database when moving the control file to avoid database errors.

Before making any modifications, listing of the files in the sapdata1 directory containing the control file might look like this:

----
hostname:/
#  ls -l /oracle/SID/sapdata1/cntrl
-rw-r----- 1 orasid  dba  9388032 Jun 19 01:51 cntrlSID.dbf
----

After the modification, the listing might look like this:

----
hostname:/
# ls -sl /oracle/SID/sapdata1
0 lrwxrwxrwx 1 root root 19 2008-08-06 14:55 cntrl -> /oracle/SID/control
0 -rw-r--r-- 1 root root 0 2008-08-06 14:57 data01.dbf

# ls -sl /oracle/SID/control
0 -rw-r--r-- 1 root root 0 2008-08-06 14:56 cntrlSID.dbf
----
