---
permalink: unix-administration/concept_variables_available_in_the_task_scripts_for_clone_operation.html
sidebar: sidebar
keywords: 
summary: 'SnapManager provides context information in the form of environment variables related to the clone operation being performed. For example, your script can retrieve the name of the original host, the name of the clone database, and the label of the backup.'
---
= Variables available in the task scripts for clone operation
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager provides context information in the form of environment variables related to the clone operation being performed. For example, your script can retrieve the name of the original host, the name of the clone database, and the label of the backup.

The following table lists the environment variables that you can use in your scripts:

|===
| Variables| Description| Format
a|
SM_ORIGINAL_SID
a|
SID of the original database
a|
string
a|
SM_ORIGINAL_HOST
a|
Host name associated with the original database
a|
string
a|
SM_ORIGINAL_OS_USER
a|
OS owner of the original database
a|
string
a|
SM_ORIGINAL_OS_GROUP
a|
OS group of the original database
a|
string
a|
SM_TARGET_SID
a|
SID of the clone database
a|
string
a|
SM_TARGET_HOST
a|
Host name associated with the clone database
a|
string
a|
SM_TARGET_OS_USER
a|
OS owner of the clone database
a|
string
a|
SM_TARGET_OS_GROUP
a|
OS group of the clone database
a|
string
a|
SM_TARGET_DB_PORT
a|
Port of the target database
a|
integer
a|
SM_TARGET_GLOBAL_DB_NAME
a|
Global database name of the target database
a|
string
a|
SM_BACKUP_LABEL
a|
Label of the backup used for the clone
a|
string
|===
