---
permalink: unix-administration/concept_workflow_summary_for_local_and_secondary_database_backup.html
sidebar: sidebar
keywords: dba, snapmanager, storage, administrator, netapp, management, console, data, protection, capability, local, backup, protect, database, target, workflow, summary, local, secondary, backup
summary: In this example, the DBA \(using SnapManager\) and the storage administrator \(using the NetApp Management Console data protection capability\) coordinate actions to configure local backup and secondary backup \(also known as a protected backup\) of the target database.
---
= Workflow summary for local and secondary database backup
:icons: font
:imagesdir: ../media/

[.lead]
In this example, the DBA (using SnapManager) and the storage administrator (using the NetApp Management Console data protection capability) coordinate actions to configure local backup and secondary backup (also known as a protected backup) of the target database.

The sequence of actions carried out are summarized as follows:

* *Secondary resource pool configuration*
+
The storage administrator uses the NetApp Management Console data protection capability to configure a resource pool of storage systems at the secondary site that can be used to store the payroll database backup.

* *Secondary backup scheduling*
+
The storage administrator uses the NetApp Management Console data protection capability to configure secondary backup schedules.

* *Protection policy configuration*
+
The storage administrator uses the NetApp Management Console data protection capability to configure a secondary backup protection policy for the target database. The protection policy includes the schedules and specifies the base type of protection to implement backup protection (backup, mirror, or a combination of both), and names retention policies for primary data, secondary, and sometimes tertiary storage nodes.

* *Database profile configuration and protection policy assignment*
+
The DBA uses SnapManager to create or edit a profile of the target database that supports secondary backup. While configuring the profile, the DBA:

 ** Enables backup protection to secondary storage.
 ** Assigns the new protection policy, which was created in and retrieved from the NetApp Management Console data protection capability, to this profile.
+
Assigning the protection policy automatically includes the target database in a partially provisioned, but nonconformant the NetApp Management Console data protection capability dataset. When fully provisioned, the dataset configuration enables backup of the target database to secondary storage.
+
The dataset name uses this syntax: smsap_hostname_databasename, which translates to "smsap_prod01.sample.com_p01".

* *Secondary and tertiary storage provisioning*
+
The storage administrator uses the NetApp Management Console data protection capability to assign resource pools to provision the secondary and sometimes tertiary storage nodes (if the assigned protection policy specifies tertiary storage nodes).

* *Backup on local storage*
+
The DBA opens the profile with protection enabled in SnapManager and creates a full backup to local storage. The new backup shows in SnapManager as scheduled for protection, but not yet protected.

* *Secondary backup confirmation*
+
Because the backup was based on a protection-enabled profile, the backup is transferred to secondary according to the protection policy's schedule. The DBA uses SnapManager to confirm the transferral of the backup to secondary storage. After the backup has been copied to secondary storage, SnapManager changes the backup Protection State from "Not protected" to "Protected."
