---
permalink: unix-administration/reference_the_smosmsapoperation_dump_command.html
sidebar: sidebar
keywords: run, operation, dump, command, create, jar, file, contain, diagnostic, information, smsap
summary: "You can run the operation dump command to create a JAR file that contains diagnostic information about an operation."
---
= The smsap operation dump command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the `operation` dump command to create a JAR file that contains diagnostic information about an operation.

== Syntax

[subs=+macros]
----
pass:quotes[smsap operation dump
-profile _profile_name_
[-label _label_name_ | -id _guid_]
[-quiet | -verbose]]
----


== Parameters

* `*-profile _profile_name_*`
+
Specifies the profile for which you want to create the dump files. The profile contains the identifier of the database and other database information.

* `*-label _label_name_*`
+
Creates dump files for the operation and assigns the specified label.

* `*-id _guid_*`
+
Creates dump files for the operation with the specified GUID. The GUID is generated by SnapManager when the operation begins.

* ``*-quiet*``
+
Displays only error messages in the console. The default is to display error and warning messages.

* ``*-verbose*``
+
Displays error, warning, and informational messages in the console.

---
== Example

The following example creates the dump file for the backup:

----
smsap operation dump -profile SALES1
-id 8abc01ec0e78f3e2010e78f3fdd00001
----

----
Dump file created Path:/userhomedirectory/.netapp/smsap/3.3/smsap_dump_8abc01ec0e78f3e2010e78f3fdd00001.jar
----
---
