---
permalink: unix-administration/reference_mounting_a_flexclone_fails_in_nfs_environment.html
sidebar: sidebar
keywords: snapmanager, create, flexclone, volume, nfs, environment, export, file, clone, backup, fail, mount, error, message
summary: "When SnapManager creates a FlexClone of a volume in an NFS environment, an entry is added in the /etc/exports file. The clone or backup fails to mount on a SnapManager host with an error message."
---
= Mounting a FlexClone volume fails in NFS environment
:icons: font
:imagesdir: ../media/

[.lead]
When SnapManager creates a FlexClone of a volume in an NFS environment, an entry is added in the `/etc/exports` file. The clone or backup fails to mount on a SnapManager host with an error message.

The error message is: `0001-034 Command error: mount failed: mount: filer1:/vol/SnapManager_20090914112850837_vol14 on /opt/NTAPsmsap/mnt/-ora_data02-20090914112850735_1 - WARNING unknown option "zone=vol14" nfs mount: filer1:/vol/SnapManager_20090914112850837_vol14: Permission denied`.

At the same time, the following message is generated at the storage system console: `Mon Sep 14 23:58:37 PDT [filer1: export.auto.update.disabled: warning]: /etc/exports was not updated for vol14 when the vol clone create command was run. Please either manually update /etc/exports or copy /etc/exports.new to it`.

This message might not be captured in the AutoSupport messages.

NOTE: You might encounter similar issues while cloning FlexVol volumes on NFS. You can follow the same steps to enable the `nfs.export.auto-update` option.

*What to do*

. Set the `nfs.export.auto-update` option `_on_` so that the `/etc/exports` file is updated automatically.

`*options nfs.export.auto-update _on_*`

NOTE: In the HA pair configuration, ensure that you set the NFS exports option to on for both the storage systems.
