---
permalink: unix-administration/reference-the-smosmsapbackup-mount-command.html
sidebar: sidebar
keywords: run, backup, mount, command, backup, recover, operation, external, tool, smsap
summary: "You can run the backup mount command to mount a backup in order to perform a recover operation by using an external tool."
---
= The smsap backup mount command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the `backup mount` command to mount a backup in order to perform a recover operation by using an external tool.

== Syntax

[subs=+macros]
----
pass:quotes[smsap backup mount
-profile _profile_name_
[-label _label_ [-data | -archivelogs\] | [-id _id_\]
[-host  _host_]
[-from-secondary {-copy-id _id_\}]
[-dump\]
[-quiet | -verbose]]
----

== Parameters

* `*-profile _profile_name_*`
+
Specifies the profile associated with the backup that you want to mount. The profile contains the identifier of the database and other database information.

* `*-id guid*`
+
Mounts the backup with the specified GUID. The GUID is generated by SnapManager when you create a backup. You can use the `smsap backup list` command to display the GUID for each backup.

* `*-label _label_*`
+
Mounts the backup with the specified label.

* `*-data*`
+
Specifies the data files.

* `*-archivelogs*`
+
Specifies the archive log files.

* `*-from-secondary -copy-id _id_*`
+
Mounts the backup from secondary storage. If this option is not specified, SnapManager mounts the backup from primary storage. You can use this option if the backup is freed.
+
You must specify the `-copy-id`option whenever you specify the `-from-secondary` option. If there is more than one backup on the secondary storage system, the `-copy-id` option is used to specify which backup copy on the secondary storage should be used to mount the backup.
+
NOTE: If you are using Data ONTAP operating in 7-Mode, you must specify a valid value for the `-copy-id` option. However, if you are using clustered Data ONTAP, the `-copy-id` option is not required.

* `*-host _host_*`
+
Specifies the host on which you want to mount the backup.

* `*-dump*`
+
Collects the dump files after the successful or failed mount operation.

* `*-quiet*`
+
Displays only error messages in the console. The default setting is to display error and warning messages.

* `*-verbose*`
+
Displays error, warning, and informational messages in the console.

NOTE: You must use this command only if you are using an external tool such as Oracle Recovery Manager (RMAN). SnapManager automatically handles the mounting of backups if you use the `smsap backup restore` command to restore the backup. This command displays a list, which shows the paths where the Snapshot copies have been mounted. This list is displayed only when the `-verbose` option is specified.

---
== Example

The following example mounts the backup:

----
smsap backup mount -profile S10_BACKUP -label full_monthly_10 -verbose
SMSAP-13046 [INFO ]: Operation GUID 8abc013111b9088e0111b908a7560001
starting on Profile S10_BACKUP
SMSAP-08052 [INFO ]: Beginning to connect mount(s)
[/oracle/S10_mirrlogs, /oracle/S10_sapdata] from logical snapshot
SMSAP_S10_BACKUP_S10_F_C_1_8abc013111a450480111a45066210001.
SMSAP-08025 [INFO ]: Beginning to connect mount
/oracle/S10_mirrlogs from snapshot
SMSAP_S10_BACKUP_S10_F_C_1_8abc013111a450480111a45066210001_0 of
volume saplog_S10.
SMSAP-08027 [INFO ]: Finished connecting mount /oracle/S10_mirrlogs from snapshot
SMSAP_S10_BACKUP_S10_F_C_1_8abc013111a450480111a45066210001_0 of
volume saplog_S10.
SMSAP-08025 [INFO ]: Beginning to connect mount /oracle/S10_sapdata
from snapshot
SMSAP_S10_BACKUP_S10_F_C_1_8abc013111a450480111a45066210001_0 of
volume sapdata_S10.
SMSAP-08027 [INFO ]: Finished connecting mount /oracle/S10_sapdata
from snapshot
SMSAP_S10_BACKUP_S10_F_C_1_8abc013111a450480111a45066210001_0 of
volume sapdata_S10.
SMSAP-08053 [INFO ]: Finished connecting mount(s)
[/oracle/S10_mirrlogs, /oracle/S10_sapdata] from logical snapshot
SMSAP_S10_BACKUP_S10_F_C_1_8abc013111a450480111a45066210001.
SMSAP-13037 [INFO ]: Successfully completed operation: Backup Mount
SMSAP-13048 [INFO ]: Operation Status: SUCCESS
SMSAP-13049 [INFO ]: Elapsed Time: 0:01:00.981
Operation Id [8abc013111b9088e0111b908a7560001] succeeded.
----
---
