---
permalink: unix-administration/reference_the_smosmsap_clone_split_command.html
sidebar: sidebar
keywords: run, clone, split, command, independent, original, snapmanager, smsap, operation, profile
summary: "You can run the clone split command to split a clone. The split clone becomes independent of the original clone. SnapManager generates a new profile after the clone split operation and you can use this profile to manage the split clone."
---
= The smsap clone split command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the clone split command to split a clone. The split clone becomes independent of the original clone. SnapManager generates a new profile after the clone split operation and you can use this profile to manage the split clone.

== Syntax

----

        smsap clone split
-profile clone-profile
\[-host hostname\]
\{-label clone-label | -id clone-id\} \[-split-label split-operation_label\]
\[-comment comment\]
-new-profile new-profile-name \[-profile-password new-profile_password\]
-repository -dbname repo_service_name
-host repo_host
-port repo_port
-login -username repo_username
-database -dbname db_dbname
-host db_host \[-sid db_sid\] \[-login -username db_username -password db_password
-port db_port\]
\[-rman \{\{-controlfile \| \{-login -username rman_username
-password rman_password\} -tnsname rman_tnsname\}\}\]
-osaccount osaccount
-osgroup osgroup
\[-retain
\[-hourly \[-count n\] \[-duration  m\]\]
\[-daily \[-count n\] \[-duration m\]\]
\[-weekly  \[-count n\] \[-duration m\]\]
\[-monthly \[-count n\] \[-duration m\]\] \]
\[-profile-comment profile-comment\]
\[-snapname-pattern pattern\]
\[-protect \[-protection-policy policy_name\]\] \| \[-noprotect\]\]
\[-summary-notification
\[-notification
\[-success -email email_address1,email_address2
-subject subject-pattern\]
\[failure -email email_address1,email_address2
-subject subject-pattern\] \]
[-separate-archivelog-backups
-retain-archivelog-backups
 -hours  hours |
-days days |
-weeks weeks |
-months months
[-protect \[-protection-policy policy_name \| -noprotect]
[-include-with-online-backups \| -no-include-with-online-backups]]
[-dump]
\[-quiet \| -verbose\]
----

== Parameters

* *-profile clone-profile*
+
Specifies the profile name from which the clone is created.

* *-host hostname*
+
Specifies the host name in which the clone exists.

* *-label clone-label*
+
Specifies the label name generated by the clone operation.

* *-id clone-id*
+
Specifies the unique ID generated by the clone operation.

* *-split-label split-operation_label*
+
Specifies the label name generated by the clone operation.

* *-new-profile new-profile_name*
+
Specifies the new profile name that SnapManager will generate after a successful split operation.

* *-profile-password new-profile_password*
+
Specifies the password for the profile.

* *-repository*
+
Specifies the details of the database for the repository.

* *-dbname repo_service_name*
+
Specifies the name of the database that stores the repository. You can use either the global name or system identifier.

* *-host repo_host*
+
Specifies the name or IP address of the host computer on which the repository database resides.

* *-port repo_port*
+
Specifies the Transmission Control Protocol (TCP) port number used to access the host on which the repository database resides.

* *-login*
+
Specifies the repository login details. This is optional. If not specified, SnapManager defaults to OS Authentication Connection Mode.

* *-username repo_username*
+
Specifies the user name required to access the host on which the repository database resides.

* *-database*
+
Specifies the details of the database that will be backed up, restored, or cloned.

* *-dbname db_dbname*
+
Specifies the name of the database that the profile describes. You can use either the global name or system identifier.

* *-host db_host*
+
Specifies the name or IP address of the host computer on which the database resides.

* *-sid db_sid*
+
Specifies the system identifier of the database that the profile describes. By default, SnapManager uses the database name as the system identifier. If the system identifier is different from the database name, you must specify it using the -sid option.

* *-login*
+
Specifies the database login details.

* *-username db_username*
+
Specifies the user name needed to access the database that the profile describes.

* *-password db_password*
+
Specifies the password needed to access the database that the profile describes.

* *-osaccount osaccount*
+
Specifies the name of the Oracle database user account. SnapManager uses this account to perform the Oracle operations such as startup and shutdown. It is typically the user who owns the Oracle software on the host, for example, orasid.

* *-osgroup osgroup*
+
Specifies the name of the Oracle database group name associated with the orasid account.
+
NOTE: The -osaccount and -osgroup variables are required for UNIX but not allowed for databases running on Windows.

* *-retain [-hourly [-count n] [-duration m]] [-daily [-count n] [-duration m]] [-weekly [-count n] [-duration m]] [-monthly [-count n] [-duration m]]*
+
Specifies the retention policy for a backup.
+
For each retention class, either or both the retention count or retention duration might be specified. The duration is in units of the class (for example, hours for hourly, days for daily). For instance, if you specify only a retention duration of 7 for daily backups, then SnapManager will not limit the number of daily backups for the profile (because the retention count is 0), but SnapManager will automatically delete daily backups created over 7 days ago.

* *-profile-comment profile-comment*
+
Specifies the comment for a profile describing the profile domain.

* *-snapname-pattern pattern*
+
Specifies the naming pattern for Snapshot copies. You can also include custom text, for example, HAOPS for highly available operations, in all Snapshot copy names. You can change the Snapshot copy naming pattern when you create a profile or after the profile has been created. The updated pattern applies only to Snapshot copies that have not yet been created. Snapshot copies that exist retain the previous Snapname pattern. You can use several variables in the pattern text.

* *-protect -protection-policy policy_name*
+
Specifies whether the backup should be protected to secondary storage.
+
NOTE: If -protect is specified without -protection-policy, then the dataset will not have a protection policy. If -protect is specified and -protection-policy is not set when the profile is created, then it may be set later by the smsap profile update command or set by the storage administrator by using the Protection Manager's console.

* *-summary-notification*
+
Specifies the details for configuring summary email notification for multiple profiles under a repository database. SnapManager generates this email.

* *-notification*
+
Specifies the details for configuring email notification for the new profile. SnapManager generates this email. The email notification enables the database administrator to receive emails on the succeeded or failed status of the database operation that is performed by using this profile.

* *-success*
+
Specifies that email notification is enabled for a profile for when the SnapManager operation succeeds.

* *-email email address 1 email address 2*
+
Specifies the email address of the recipient.

* *-subject subject-pattern*
+
Specifies the email subject.

* *-failure*
+
Specifies that email notification is enabled for a profile for when the SnapManager operation fails.

* *-separate-archivelog-backups*
+
Specifies that the archive log backup is separated from the datafile backup. This is an optional parameter, which you can provide while creating the profile. After the backups are separated by using this option, you can either create datafiles-only backup or archive logs-only backup.

* *-retain-archivelog-backups -hours hours | -daysdays | -weeksweeks| -monthsmonths*
+
Specifies that the archive log backups are retained based on the archive log retention duration (hourly, daily, weekly, or monthly).

* *protect [-protection-policypolicy_name] | -noprotect*
+
Specifies that the archive log files is protected based on the archive log protection policy.
+
Specifies that the archive log files are not protected by using the -noprotect option.

* *-include-with-online-backups | -no-include-with-online-backups*
+
Specifies that the archive log backup is included along with the online database backup.
+
Specifies that the archive log backups are not included along with the online database backup.

* *-dump*
+
Specifies that the dump files are not collected after the successful profile create operation.

* *-quiet*
+
Displays only error messages in the console. The default setting displays error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages in the console.
