---
permalink: unix-administration/reference-troubleshooting-storage-system-renaming-issue.html
sidebar: sidebar
keywords: face, issue, renaming, rename, storage, system, successful, troubleshooting
summary: "You might face issues when renaming a storage system or after you have successfully renamed the storage system."
---
= Troubleshooting storage system renaming issue
:icons: font
:imagesdir: ../media/

[.lead]
You might face issues when renaming a storage system or after you have successfully renamed the storage system.

When you try to rename the storage system, the operation might fail with the following error message: `SMSAP-05085 No storage controller "fas3020-rtp07New" is found to be associated with the profile`

You must enter the IP address or name of the storage system that is listed when you run the `smsap storage list` command.

After you rename the storage system, SnapManager operations might fail if SnapManager fails to recognize the storage system. You must perform some additional steps in the DataFabric Manager server host and the SnapManager server host to resolve this issue.

Perform the following steps in the DataFabric Manager server host:

. Delete the IP address and host of the earlier storage system in the host file located at ``/etc/hosts`` in the DataFabric Manager server host.
. Add the new IP address and host of the new storage system in the host file located at ``/etc/hosts`` in the DataFabric Manager server host.
. Change the storage host name by entering the following command:
+
`*dfm host rename -a _old_host_namenew_host_name_*`
. Set the new IP address in the host by entering the following command:
+
`*dfm host set _old_host_name_or_objId_ hostPrimaryAddress = _new_storage_controller_ip_address_*`
+
NOTE: You must perform this step only if you have specified the IP address as the new storage system name.

. Update the new storage system name in the DataFabric Manager server host by entering the following command:
+
`*dfm host diag _old_storage_name_*`
+
You can verify that the earlier storage controller name is replaced with new storage controller name by entering the following command:
+
`*dfm host discover new_storage_name*`

Perform the following steps as a root user in the SnapManager server host.

NOTE: When you enter the new storage controller name, ensure that you use the system alias name and not the fully qualified domain name (FQDN).

. Delete the earlier storage system name by entering the following command:
+
`*snapdrive config delete _old_storage_name_*`
+
NOTE: If you do not delete the earlier storage system name, then all the SnapManager operations fail.

. Delete the IP address and host of the earlier storage system in the host file located at `etc/hosts` in the target database host.
. Add the new IP address and host of the new storage system in the host file located at ``/etc/hosts`` in the target database host.
. Add the new storage system name by entering the following command:
+
`*snapdrive config set root _new_storage_name_*`
. Map the earlier and later storage system names by entering the following command:
+
`*snapdrive config migrate set _old_storage_namenew_storage_name_*`
. Delete the management path of the earlier storage system by entering the following command:
+
``*snapdrive config delete -mgmtpath _old_storage_name_*``
. Add the management path for the new storage system by entering the following command:
+
`*snapdrive config set -mgmtpath _new_storage_name_*`
. Update the dataset for both data files and archive log files with the new storage system name by entering the following command:
+
`*snapdrive dataset changehostname -dn _dataset_name_ -oldname _old_storage_name_ -newname _new_storage_name_*`
. Update the profile for the new storage system name by entering the following command:
+
`*smsap storage rename -profile _profile_name_ -oldname _old_storage_name_ -newname _new_storage_name_*`
. Verify the storage system associated with the profile by entering the following command:
+
`*smsap storage list -profile _profile_name_*`
