---
permalink: unix-administration/reference-the-smosmsapbackup-update-command.html
sidebar: sidebar
keywords: run, backup, update, command, retention, policy, smsap
summary: "You can run the backup update command to update the backup retention policy."
---
= The smsap backup update command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the `backup update` command to update the backup retention policy.

== Syntax

[subs=+macros]
----
pass:quotes[smsap backup update
-profile _profile_name_
[-label _label_ [-data | -archivelogs\] | [-id _guid_\]
[-retain {-hourly | -daily | -weekly | -monthly | -unlimited}\]
[-comment _comment_text_\]
[-quiet | -verbose]]
----

== Parameters

* ``*-profile _profile_name_*``
+
Specifies the profile for which to update backups. The profile contains the identifier of the database and other database information.

* ``*-id _guid_*``
+
Verifies the backup with the specified GUID. The GUID is generated by SnapManager when you create a backup. You can use the smsap backup list command to display the GUID for each backup.

* ``*-label _label_*``
+
Specifies the backup label and scope of the backup as data file or archive log.

* ``*-data*``
+
Specifies the data files.

* ``*-archivelogs*``
+
Specifies the archive log files.

* ``*-comment _comment_text_*``
+
Enter text (up to 200 characters) about the backup update. You can include spaces.

* ``*-quiet*``
+
Displays only error messages in the console. The default is to display error and warning messages.

* ``*-verbose*``
+
Displays error, warning, and informational messages in the console.

* ``*-retain {-hourly | -daily | -weekly | -monthly | -unlimited}*``
+
Specifies whether the backup should be retained on an hourly, daily, weekly, monthly, or unlimited basis. If `-retain` is not specified, the retention class defaults to `-hourly`. To retain backups forever, use the `-unlimited` option. The `-unlimited` option makes the backup ineligible for deletion.

---
== Example

The following example updates the backup to be set the retention policy to unlimited:

----
smsap backup update -profile SALES1 -label full_backup_sales_May
-retain -unlimited -comment save_forever_monthly_backup
----
---
