---
permalink: unix-administration/reference_the_smosmsapbackup_unmount_command.html
sidebar: sidebar
keywords: run, backup, unmount, command, smsap
summary: You can run the backup unmount command to unmount a backup.
---
= The smsap backup unmount command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the backup unmount command to unmount a backup.

== Syntax

----

        smsap backup unmount
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id id\]
\[-force\]
\[-dump\]
\[-quiet \| -verbose\]
----

== Parameters

* *-profile profile_name*
+
Specifies the profile for which you want to unmount a backup. The profile contains the identifier of the database and other database information.

* *-id id*
+
Unmounts the backup with the specified GUID. The GUID is generated by SnapManager when you create a backup. You can use the smsap backup list command to display the GUID for each backup.

* *-label label*
+
Unmounts the backup with the specified label.

* *-data*
+
Specifies the data files.

* *-archivelogs*
+
Specifies the archive log files.

* *-dump*
+
Collects the dump files after a successful or failed unmount operation.

* *-force*
+
Unmounts the backup even if there are problems in freeing the resources associated with the backup. SnapManager tries to unmount the backup and clean up any associated resources. The log shows the unmount operation as successful, but you may have to manually clean up resources if there are errors in the log.

* *-quiet*
+
Displays only error messages in the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages in the console.

== Example

The following is an example of an unmount operation:

----
# smsap backup unmount -label test -profile SALES1 -verbose
----

----
SMSAP-13046 [INFO ]: Operation GUID 8abc013111b909eb0111b90a02f50001 starting on Profile SALES1
SMSAP-08028 [INFO ]: Beginning to disconnect connected mount(s)
[/u/user1/mnt/_mnt_ssys1_logs_SMSAP_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001,
 /u/user1/mnt/_mnt_ssys1_data_SMSAP_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001].
SMSAP-08030 [INFO ]: Done disconnecting connected mount(s)
[/u/user1/mnt/_mnt_ssys1_logs_SMSAP_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001,
 /u/user1//mnt/_mnt_ssys1_data_SMSAP_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001].
SMSAP-13037 [INFO ]: Successfully completed operation: Backup Unmount
SMSAP-13048 [INFO ]: Operation Status: SUCCESS
SMSAP-13049 [INFO ]: Elapsed Time: 0:00:33.715
Operation Id [8abc013111b909eb0111b90a02f50001] succeeded.
----

*Related information*

xref:task_unmounting_backups.adoc[Unmounting backups]
