---
permalink: unix-administration/reference_the_smosmsapclone_delete_command.html
sidebar: sidebar
keywords: run, clone, delete, command, operation, smsap
summary: "You can run the clone delete command to delete a clone. You cannot delete a clone if the clone is use by any operation."
---
= The smsap clone delete command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the `clone delete` command to delete a clone. You cannot delete a clone if the clone is use by any operation.

== Syntax

[subs=+macros]
----
pass:quotes[smsap clone delete
-profile _profile_name_
[-id _guid_ | -label _clone_name_\]
[-login
[-username _db_username_ -password _db_password_ -port _db_port_\]
[-asminstance -asmusername _asminstance_username_ -asmpassword _asminstance_password_\]]]
[-syspassword _syspassword_] -force
[-dump] [-quiet | -verbose]

----

== Parameters

* ``*-profile _profile_name_*``
+
Specifies the name of the profile containing the clone being deleted. The profile contains the identifier of the database and other database information.

* ``*-force*``
+
Deletes the clone even if there are resources associated with the clone.

* ``*-id _guid_*``
+
Specifies the GUID for the clone being deleted. The GUID is generated by SnapManager when you create a clone. You can use the `smsap clone list` command to display the GUID for each clone.

* ``*-label _name_*``
+
Specifies the label for the clone being deleted.

* ``*-asminstance*``
+
Specifies the credentials that are used to log in to the Automatic Storage Management (ASM) instance.

* ``*-asmusername _asminstance_username_*``
+
Specifies the user name used to log in to the ASM instance.

* ``*-asmpassword _asminstance_password_*``
+
Specifies the password used to log in to ASM instance.

* ``*-syspassword _syspassword_*``
+
Specifies the password for the sys privileged user.
+
NOTE: You must provide the password for the sys privileged user if the database credentials provided are not the same for sys privileged user.

* ``*-login*``
+
Allows you to enter the database login details.

* ``*-username _db_username_*``
+
Specifies the user name required to access the database.

* ``*-password _db_password_*``
+
Specifies the password required to access the database.

* ``*-port _db_port_*``
+
Specifies the TCP port number used to access the database that the profile describes.

* ``*-dump*``
+
Specifies to collect the dump files after the clone delete operation.

* ``*-quiet*``
+
Displays only error messages in the console. The default is to display error and warning messages.

* ``*-verbose*``
+
Displays error, warning, and informational messages in the console.

---
== Example

The following example deletes the clone:

----
smsap clone delete -profile SALES1 -label SALES_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----
---
