---
permalink: unix-administration/reference_supported_partition_devices.html
sidebar: sidebar
keywords: partition, device, support, snapmanager
summary: "You must know the different partition devices that are supported in SnapManager."
---
= Supported partition devices
:icons: font
:imagesdir: ../media/

[.lead]
You must know the different partition devices that are supported in SnapManager.

The following table provides partition information and how it can be enabled for different operating systems:

[cols="3a,1a,1a,1a,1a" options="header"]
|===
| Operating system| Single partition| Multiple partition| Non-partition devices| File system or RAW devices
a|
Red Hat Enterprise Linux 5x

or

Oracle Enterprise Linux 5x

a|
Yes
a|
No
a|
No
a|
ext3*
a|
Red Hat Enterprise Linux 6x

or

Oracle Enterprise Linux 6x

a|
Yes
a|
No
a|
No
a|
ext3 or ext4*
a|
SUSE Linux Enterprise Server 11
a|
Yes
a|
No
a|
No
a|
ext3*
a|
SUSE Linux Enterprise Server 10
a|
No
a|
No
a|
Yes
a|
ext3***
5+a|
*

For a non-MPIO environment, enter the following command:

`sfdisk -uS -f -L -q /dev/ device_name`

For an MPIO environment, enter the following commands:

* `sfdisk -uS -f -L -q /dev/ device_name`
* `kpartx -a -p p /dev/mapper/ device_name`

5+a|*_*_* *_*_* *_*_*

Not applicable.
|===
For more information on the operating system versions supported, refer to the Interoperability Matrix.
