---
permalink: unix-administration/reference_the_smosmsapcredential_delete_command.html
sidebar: sidebar
keywords: command, delete, user, credentials, secure, resource, smsap
summary: "This command deletes the user credentials for a particular secured resource."
---
= The smsap credential delete command
:icons: font
:imagesdir: ../media/

[.lead]
This command deletes the user credentials for a particular secured resource.

== Syntax

[subs=+macros]
----
pass:quotes[smsap credential delete
[-host -name _host_name_
-username _username_\] |
[-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_
-port _repo_port_\] |
[-profile
-name _profile_name_\]
[-quiet | -verbose]]
----


== Parameters

* `*-host _hostname_*`
+
Specifies the name of the host server on which SnapManager is running.
+
The `-host` parameter includes the following options:

 ** `-name _host_name_`: Specifies the name of the host for which you will delete the password.
 ** `-username _user_name_`: Specifies the user name on the host.

* `*-repository -dbname*`
+
Specifies the name of the database that stores the profile. Use either the global name or the SID.
+
The `-repository` parameter includes the following options:

 ** `-dbname _repo_service_name_`: Specifies the name of the database that stores the profile. Use either the global name or the SID.
 ** `-host _repo_host_`: Specifies the name or IP address of the host server the repository database runs on.
 ** `-login-username _repo_username_`: Specifies the user name needed to access the database that stores the repository.
 ** `-port _repo_port_`: Specifies the TCP port number used to access the database that stores the repository.

* `*-profile -name _profile_name_*`
+
Specifies the profile with which the database is associated.
+
The `-profile` parameter includes the following option:

 ** `-name _profilename_`: Specifies the name of the profile for which you will delete the password.

* `*-quiet*`
+
Displays only error messages on the console. The default is to display error and warning messages.

* `*-verbose*`
+
Displays error, warning, and informational messages on the console.

---
== Example command

This example deletes the credentials of the profile.

----
smsap credential delete -profile -name user1 -verbose
----

----
SMSAP-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----

This example deletes the credentials of the repository.

----
smsap credential delete -repository -dbname SMSAPREPO -host Host2
-login -username user1 -port 1521
----

----
SMSAP-20023 [INFO ]: Deleted repository credentials for "user1@SMSAPREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----

This example deletes the credentials of the host.

----
smsap credential delete -host -name Host2
----

----
SMSAP-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----
---
