---
permalink: unix-administration/reference-the-smosmsap-repository-rollingupgrade.html
sidebar: sidebar
keywords: command, perform, roll, upgrade, single, host, multiple, associate, target, database, version, snapmanager, smsap, repository, rollingupgrade
summary: "This command performs rolling upgrade on a single host or multiple hosts and their associated target databases from a lower version of SnapManager to a higher version. The upgraded host is managed only with the higher version of SnapManager."
---
= The smsap repository rollingupgrade command
:icons: font
:imagesdir: ../media/

[.lead]
This command performs rolling upgrade on a single host or multiple hosts and their associated target databases from a lower version of SnapManager to a higher version. The upgraded host is managed only with the higher version of SnapManager.

== Syntax

[subs=+macros]
----
pass:quotes[smsap repository rollingupgrade
-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_
-port _repo_port_
-upgradehost _host_with_target_database_
[-force] [-noprompt]
[-quiet | -verbose]
----

== Parameters

* `*-repository*`
+
The options that follow -repository specify the details of the database for the repository.

* `*-dbname _repo_service_name_*`
+
Specifies the name of the database that stores the repository. Use either the global name or the SID.

* `*-host _repo_host_*`
+
Specifies the name or IP address of the host computer the repository database runs on.

* `*-login*`
+
Starts the repository login details.

* `*-username _repo_username_*`
+
Specifies the user name needed to access the database that stores the repository.

* `*-upgradehost _host_with_target_database_*`
+
Specifies the name of the host which will be rolling upgraded from a lower version of SnapManager to a higher version.

* `*-port _repo_port_*`
+
Specifies the TCP port number used to access the database that stores the repository.

* `*-force*`
+
Attempts to force the update of the repository. SnapManager prompts you to make a backup of the current repository before updating.

* `*-noprompt*`
+
Does not display the prompt before updating the repository database. Using the `-noprompt` option ensures the prompt does not appear, making it easier to update repositories using a script.

* `*-quiet*`
+
Displays only error messages on the console. The default is to display error and warning messages.

* `*-verbose*`
+
Displays error, warning, and informational messages on the console.

---

== Example command

The following example updates the repository in the SALESDB database.

----
smsap repository rollingupgrade -repository -dbname SALESDB
-host server1 -login -username admin -port 1521 -upgradehost hostA
----
---
