---
permalink: unix-administration/reference-the-smosmsap-storage-rename-command.html
sidebar: sidebar
keywords: command, update, name, ip, address, storage, system, smsap
summary: "This command updates the name or IP address of the storage system."
---
= The smsap storage rename command
:icons: font
:imagesdir: ../media/

[.lead]
This command updates the name or IP address of the storage system.

== Syntax

[subs=+macros]
----
pass:quotes[smsap storage rename
-profile _profile_ -oldname _old_storage_name_ -newname _new_storage_name_
[-quiet | -verbose\]]
----

== Parameters

* `*-profile _profile_*`
+
Specifies the name of the profile. This name can be up to 30 characters long and must be unique within the host.

* `*-oldname _old_storage_name_*`
+
Specifies the IP address or name of the storage system before the storage system is renamed. You must enter the IP address or name of the storage system that is displayed when you run the `smsap storage list` command.

* `*-newname _new_storage_name_*`
+
Specifies the IP address or name of the storage system after the storage system is renamed.

* `*-quiet*`
+
Displays only error messages in the console. The default is to display error and warning messages.

* `*-verbose*`
+
Displays error, warning, and informational messages in the console.

---

== Example

The following example uses the `smsap storage rename` command to rename the storage system:

----
smsap storage rename -profile mjullian -oldname lech -newname hudson -verbose
----
---
