---
permalink: unix-administration/reference_the_smosmsaprepository_update_command.html
sidebar: sidebar
keywords: command, update, repository, store, database, profile, credentials, upgrade, snapmanager, install, version, incomplete, smsap
summary: "This command updates the repository that stores database profiles and associated credentials when you upgrade SnapManager. Any time you install a new version of SnapManager, you must run the repository update command before you can use the new version. You are able to use this command only if there are no incomplete commands in the repository."
---
= The smsap repository update command
:icons: font
:imagesdir: ../media/

[.lead]
This command updates the repository that stores database profiles and associated credentials when you upgrade SnapManager. Any time you install a new version of SnapManager, you must run the repository update command before you can use the new version. You are able to use this command only if there are no incomplete commands in the repository.

== Syntax

----
smsap repository update
-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port
[-force] [-noprompt]
[-quiet | -verbose]
----

== Parameters

* ``*-repository*``
+
The options that follow `-repository` specify the details of the database for the repository.

* ``*-dbname _repo_service_name_*``
+
Specifies the name of the database that stores the repository. Use either the global name or the SID.

* ``*-host _repo_host_*``
+
Specifies the name or IP address of the host computer the repository database runs on.

* ``*-login*``
+
Starts the repository login details.

* ``*-username _repo_username_*``
+
Specifies the user name needed to access the database that stores the repository.

* ``*-port _repo_port_*``
+
Specifies the TCP port number used to access the database that stores the repository.

* ``*-force*``
+
Attempts to force the update of the repository. SnapManager prompts you to make a backup of the current repository before updating.

* ``*-noprompt*``
+
Does not display the prompt before updating the repository database. Using the -noprompt option ensures the prompt does not appear, making it easier to update repositories using a script.

* ``*-quiet*``
+
Displays only error messages on the console. The default is to display error and warning messages.

* ``*-verbose*``
+
Displays error, warning, and informational messages on the console.

== Example command

The following example updates the repository in the SALESDB database.

----
smsap repository update -repository -dbname SALESDB
-host server1 -login -username admin -port 1521
----
