---
permalink: unix-administration/reference_the_smosmsapcmdfile_command.html
sidebar: sidebar
keywords: 
summary: 'You can use the cmdfile command to run any command if the shell on your host limits the number of characters that can appear on a command line.'
---
= The smsap cmdfile command
:icons: font
:imagesdir: ../media/

[.lead]
You can use the cmdfile command to run any command if the shell on your host limits the number of characters that can appear on a command line.

== Syntax

----

        smsap cmdfile 
-file file_name 
\[-quiet \| -verbose\]
----

You can include the command in a text file and use the smsap cmdfile command to execute the command. You can add only one command in a text file. You must not include smsap in the command syntax.

NOTE: The smsap cmdfile command replaces the smsap pfile command. The smsap cmdfile is not compatible with the smsap pfile command.

== Parameters

* *-file file_name*
+
Specifies the path to text file containing the command you want to execute.

* *-quiet*
+
Specifies that only error messages are displayed in the console. The default is to display error and warning messages.

* *-verbose*
+
Specifies that error, warning, and informational messages are displayed in the console.

== Example

This example creates a profile by including the profile create command in command.txt located at /tmp. You can then run the smsap cmdfile command.

The text file contains the following information:

----
profile create -profile SALES1 -repository -dbname SNAPMGRR
-login -username server1_user -password ontap -port 1521 -host server1
-database -dbname SMSMSAP -sid SMSMSAP -login -username sys -password oracle -port 1521
-host Host2 -osaccount oracle -osgroup db2
----

You can now create the profile by running the smsap cmdfile command with the command.txt file:

----
smsap cmdfile -file /tmp/command.txt
----
