---
permalink: unix-administration/reference_sample_database_volume_layouts.html
sidebar: sidebar
keywords: sample, database, volume, layout, configuring, configure
summary: "You can refer to sample database volume layouts for help in configuring your database."
---
= Sample database volume layouts
:icons: font
:imagesdir: ../media/

[.lead]
You can refer to sample database volume layouts for help in configuring your database.

== Single-instance databases

[cols="1a,3a,1a,1a" options="header"]
|===
| File types| Volume names| Dedicated volume for file types| Automatic Snapshot copies
a|
Oracle binaries
a|
orabin_ `_host name_`
a|
Yes
a|
On
a|
Data files
a|
oradata_ `_sid_`
a|
Yes
a|
Off
a|
Temporary data files
a|
oratemp_ `_sid_`
a|
Yes
a|
Off
a|
Control files
a|
oracntrl01_ `_sid_` (Multiplexed)

oracntrl02_ `_sid_` (Multiplexed)

a|
Yes
a|
Off
a|
Redo logs
a|
oralog01_ `_sid_` (Multiplexed)

oralog02_ `_sid_` (Multiplexed)

a|
Yes
a|
Off
a|
Archive logs
a|
oraarch_ `_sid_`
a|
Yes
a|
Off
|===

== Real Application Clusters (RAC) databases

[cols="1a,3a,1a,1a" options="header"]
|===
| File types| Volume names| Dedicated volume for file types| Automatic Snapshot copies
a|
Oracle binaries
a|
orabin_ `_host name_`
a|
Yes
a|
On
a|
Data files
a|
oradata_ `_dbname_`
a|
Yes
a|
Off
a|
Temporary data files
a|
oratemp_ `_dbname_`
a|
Yes
a|
Off
a|
Control files
a|
oracntrl01_ `_dbname_` (Multiplexed)

oracntrl02_ `_dbname_` (Multiplexed)

a|
Yes
a|
Off
a|
Redo logs
a|
oralog01_ `_dbname_` (Multiplexed)

oralog02_ `_dbname_` (Multiplexed)

a|
Yes
a|
Off
a|
Archive logs
a|
oraarch_ `_dbname_`
a|
Yes
a|
Off
a|
Cluster files
a|
oracrs_ `_clustername_`
a|
Yes
a|
On
|===
