---
permalink: unix-administration/reference_the_smosmsap_history_remove_command.html
sidebar: sidebar
keywords: command, enable, remove, history, snapmanager, operation, single, multiple, profile, repository, smsap
summary: "This command enables you to remove the history of SnapManager operations associated with a single profile, multiple profiles, or all profiles under a repository."
---
= The smsap history remove command
:icons: font
:imagesdir: ../media/

[.lead]
This command enables you to remove the history of SnapManager operations associated with a single profile, multiple profiles, or all profiles under a repository.

== Syntax

[subs=+macros]
----
pass:quotes[smsap history remove
-profile {-name _profile_name_ [_profile_name1, profile_name2_\] | -all
-repository -login [-password _repo_password_\] -username _repo_username_
-host _repo_host_
-dbname _repo_dbname_
-port _repo_port_}
-operation {-operations operation_name [_operation_name_, _operation_name2_\] | -all}
[-quiet | -verbose\]]
----

== Parameters

* `*-profile profile*`
+
Specifies the name of the profile. This name can be up to 30 characters long and must be unique within the host.

* `*-repository*`
+
The options that follow -repository specify the details of the database that stores the profile.

* `*-dbname _repo_dbname_*`
+
Specifies the name of the database that stores the profile. Use either the global name or the SID.

* `*-host _repo_host_*`
+
Specifies the name or IP address of the host computer the repository database runs on.

* `*-login*`
+
Starts the repository login details.

* `*-username _repo_username_*`
+
Specifies the user name needed to access the database that stores the repository.

* `*-port _repo_port_*`
+
Specifies the TCP port number used to access the database that stores the repository.

* `*-operation {-operations _operation_name_ [_operation_name1, operation_name2_] | -all*`
+
Specifies the SnapManager operation for which you configure the history.

* `*-quiet*`
+
Displays only error messages on the console. The default is to display error and warning messages.

* `*-verbose*`
+
Displays error, warning, and informational messages on the console.

---
== Example command

----
 smsap history purge -profile -name PROFILE1 -operation -operations backup
 -verbose
----
---
