---
permalink: unix-administration/reference-the-smosmsaprepository-delete-command.html
sidebar: sidebar
keywords: command, delete, repository, store, database, profile, associate, credentials, delete, smsap
summary: "This command deletes a repository used to store database profiles and associated credentials. You can delete a repository only if there are no profiles in the repository."
---
= The smsap repository delete command
:icons: font
:imagesdir: ../media/

[.lead]
This command deletes a repository used to store database profiles and associated credentials. You can delete a repository only if there are no profiles in the repository.

== Syntax

----
smsap repository delete
-repository
-port repo_port
-dbname repo_service_name
-host repo_host
-login -username repo_username
[-force] [-noprompt]
[-quiet | -verbose]
----

== Parameters

* ``*-repository*``
+
The options that follow `-repository` specify the details of the database for the repository.

* ``*-port _repo_port_*``
+
Specifies the TCP port number used to access the database that stores the repository.

* ``*-dbname _repo_service_name_*``
+
Specifies the name of the database that stores the repository. Use either the global name or the SID.

* ``*-host _repo_host_*``
+
Specifies the name or IP address of the host computer the repository database runs on.

* ``*-login*``
+
Starts the repository login details.

* ``*-username _repo_username_*``
+
Specifies the user name needed to access the database that stores the repository.

* ``*-force*``
+
Attempts to force the deletion of the repository, even if there are incomplete operations. SnapManager issues a prompt if there are incomplete operations, asking if you are sure you want to delete the repository.

* ``*-noprompt*``
+
Does not prompt you before deleting the repository. Using the -noprompt option ensures the prompt does not appear, making it easier to delete repositories using a script.

* ``*-quiet*``
+
Displays only error messages on the console. The default is to display error and warning messages.

* ``*-verbose*``
+
Displays error, warning, and informational messages on the console.

== Command example

The following example deletes the repository in the SALESDB database.

----
smsap repository delete -repository -dbname SALESDB
-host server1 -login -username admin -port 1527 -force -verbose
----
