---
permalink: unix-administration/reference_the_smosmsapclone_create_command.html
sidebar: sidebar
keywords: 
summary: 'You can run the clone create command to create a clone of a backed-up database. You can clone a backup from primary or secondary storage.'
---
= The smsap clone create command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the clone create command to create a clone of a backed-up database. You can clone a backup from primary or secondary storage.

== Syntax

----

        smsap clone create 
-profile profile_name 
[-backup-id backup_guid \| -backup-label backup_label_name \| -current\] 
-newsid new_sid 
\[-host target_host\] 
[-label clone_label] 
\[-comment string\] 
-clonespec full_path_to_clonespec_file 
\[-asminstance -asmusername asminstance_username  -asmpassword asminstance_password\]]  
\[-syspassword syspassword\]
\[-reserve \{yes \| no \| inherit\}\] 
\[-from-secondary \{-copy-id id\}\] 
\[-no-resetlogs \| -recover-from-location path1 \[, path2\]\]\[-taskspec taskspec\]
\[-dump\]
\[-quiet \| -verbose\]
----

== Parameters

* *-profile name*
+
Specifies the database that you want to clone. The profile contains the identifier of the database and other database information.

* *-backup-id guid*
+
Clones the backup with the specified GUID. The GUID is generated by SnapManager when you create a backup. You can use the smsap backup list-verbose command to display the GUID for each backup.

* *-backup-label backup_label_name*
+
Specifies to clone the backup with the specified label name.

* *-current*
+
Specifies to create backup and clone from the current state of the database.
+
NOTE: If the database is in the noarchivelog mode, SnapManager will create an offline backup.

* *-newsid new_sid*
+
Specifies a new, unique Oracle system identifier for the cloned database. The system identifier value is a maximum of eight characters. Oracle does not allow running two databases with the same system identifier on the same host simultaneously.

* *-host target_host*
+
Specifies the host on which the clone should be created.

* *-label clone_label*
+
Specifies a label for the clone.

* *-comment string*
+
Specifies an optional comment to describe this clone. You must enclose the string within single quotation marks.
+
NOTE: Some shells delete the quotation marks. If that is true for your shell, you must escape the quotation with a backslash (\). For example, you might need to enter: \' this is a comment\'

* *-clonespec full_path_to_clonespec_file*
+
Specifies the path to the clone specification XML file. This can be a relative or an absolute path name.

* *-asminstance*
+
Specifies the credentials that are used to log in to the ASM instance.

* *-asmusername asminstance_username*
+
Specifies the user name that is used to log in to the ASM instance.

* *-asmpassword asminstance_password*
+
Specifies the password that is used to log in to ASM instance.

* *-syspassword syspassword*
+
Specifies the password for the sys privileged user.
+
NOTE: You must provide the password for the sys privileged user if the database credentials that are provided are not the same for the sys privileged user.

* *-reserve*
+
Setting the -reserve option to yes ensures that the volume guarantee space reserve is turned on for the new clone volumes. Setting the -reserve option to no ensures that the volume guarantee space reserve is turned off for the new clone volumes. Setting the -reserve option to inherit ensures that the new clone inherits the space reservation characteristics of the parent Snapshot copy. The default setting is no.
+
The following table describes the cloning methods and their effect on the clone create operation and its -reserve option. A LUN can be cloned by using either method.
+
|===
| Cloning method| Description| Result
a|
    LUN cloning
a|
    A new clone LUN is created within the same volume.
a|
    When the -reserve option for a LUN is set to yes, space is reserved for the full LUN size within the volume.
a|
    Volume cloning
a|
    A new FlexClone is created, and the clone LUN exists within the new clone volume. Uses the FlexClone technology.
a|
    When the -reserve option for a volume is set to yes, space is reserved for the full volume size within the aggregate.
+
|===

* *-from-secondary [-copy-idcopy_id]*
+
Specifies that SnapManager should clone a copy of a backup that has been protected to secondary storage. If this option is not specified, SnapManager clones the copy from primary storage.
+
You must specify the -copy-id option whenever you specify the -from-secondary option. If there is more than one backup on the secondary storage system, the -copy-id option is used to specify which backup copy on the secondary storage should be used for cloning.
+
NOTE: If you are using Data ONTAP operating in 7-Mode, you must specify a valid value for the -copy-id option. However, if you are using clustered Data ONTAP, the -copy-id option is not required.

* *-no-resetlogs*
+
Specifies to skip recovering the database, executing the DBNEWID utility, and not opening the database with the resetlogs while creating the clone.

* *-recover-from-location*
+
Specifies the external archive log location of the archive log backups where SnapManager takes the archive log files from the external location and uses them for cloning.

* *-taskspec*
+
Specifies the task specification XML file for preprocessing activity or post-processing activity of the clone operation. You must provide the complete path of the task specification XML file.

* *-dump*
+
Specifies to collect the dump files after the clone create operation.

* *-quiet*
+
Displays only error messages in the console. The default setting is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages in the console.

== Example

The following example clones the backup by using a clone specification that is created for this clone:

----
smsap clone create -profile SALES1 -backup-label full_backup_sales_May -newsid
CLONE -label sales1_clone -clonespec /opt/<path>/smsap/clonespecs/sales1_clonespec.xml
----

----
Operation Id [8abc01ec0e794e3f010e794e6e9b0001] succeeded.
----

*Related information*

xref:task_creating_clone_specifications.adoc[Creating clone specifications]

xref:task_cloning_databases_from_backups.adoc[Cloning databases from backups]
