---
permalink: unix-administration/reference_the_smosmsap_clone_update_command.html
sidebar: sidebar
keywords: command, update, information, clone, comment, smsap
summary: "This command updates information about the clone. You can update the comment."
---
= The smsap clone update command
:icons: font
:imagesdir: ../media/

[.lead]
This command updates information about the clone. You can update the comment.

== Syntax

[subs=+macros]
----
pass:quotes[smsap clone update
-profile _profile_name_
[-label _label_ | -id _id_\]
-comment  _commment_text_ [-quiet | -verbose\]]
----

== Parameters

* `*-profile _profile_name_*`
+
Specifies the name of the profile containing the clone you want to update. The profile contains the identifier of the database and other database information.

* `*-id _id_*`
+
Specifies the ID for the clone. The ID is generated by SnapManager when you create a clone. Use the smsap clone list command to display the ID for each clone.

* `*-label _label_*`
+
Specifies the label for the clone.

* `*-comment*`
+
Shows the comment entered in the clone creation. This is an optional parameter.

* `*-quiet*`
+
Displays only error messages on the console. The default is to display error and warning messages.

* `*-verbose*`
+
Displays error, warning, and informational messages on the console.

---
== Example command

The following example updates the clone comment.

----
smsap clone update -profile anson.pcrac5
-label clone_pcrac51_20080820141624EDT  -comment See updated clone
----
---
