---
permalink: unix-administration/reference_the_smosmsapclone_template_command.html
sidebar: sidebar
keywords: command, create, clone, specification, template, smsap
summary: "This command lets you create a clone specification template."
---
= The smsap clone template command
:icons: font
:imagesdir: ../media/

[.lead]
This command lets you create a clone specification template.

== Syntax

[subs=+macros]
----
pass:quotes[smsap clone template
-profile _name_
[-backup-id _guid_  | -backup-label _backup_name_\]
[-quiet | -verbose]]
----

== Parameters

* ``*-profile _name_*``
+
Specifies the database you want to create a clone specification of. The profile contains the identifier of the database and other database information.

* ``*-backup-id _guid_*``
+
Creates a clone specification from the backup with the specified GUID. The GUID is generated by SnapManager when you create a backup. Use the smsap backup list command to display the GUID for each backup.

* ``*-backup-label _backup_label_name_*``
+
Creates a clone specification from the backup with the specified backup label.

* ``*-quiet*``
+
Displays only error messages on the console. The default is to display error and warning messages.

* ``*-verbose*``
+
Displays error, warning, and informational messages on the console.

---
== Example command

The following example creates a clone specification template from the backup with the label full_backup_sales_May. Once the smsap clone template command completes, the clone specification template is complete.

----
smsap clone template -profile SALES1 -backup-label full_backup_sales_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----
---
