---
permalink: unix-administration/reference_the_smosmsap_clone_split_command.html
sidebar: sidebar
keywords: run, clone, split, command, independent, original, snapmanager, smsap, operation, profile
summary: "You can run the clone split command to split a clone. The split clone becomes independent of the original clone. SnapManager generates a new profile after the clone split operation and you can use this profile to manage the split clone."
---
= The smsap clone split command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the `clone split` command to split a clone. The split clone becomes independent of the original clone. SnapManager generates a new profile after the clone split operation and you can use this profile to manage the split clone.

== Syntax

[subs=+macros]
----
pass:quotes[smsap clone split
-profile _clone-profile_
[-host hostname\]
{-label _clone-label_ | -id _clone-id_} [-split-label _split-operation_label_\]
[-comment _comment_\]
-new-profile _new-profile-name_ [-profile-password _new-profile_password_\]
-repository -dbname _repo_service_name_
-host _repo_host_
-port _repo_port_
-login -username _repo_username_
-database -dbname _db_dbname_
-host _db_host_ [-sid _db_sid_\] [-login -username _db_username_ -password _db_password_
-port _db_port_\]
[-rman {{-controlfile | {-login -username _rman_username_
-password _rman_password_} -tnsname _rman_tnsname_}}\]
-osaccount _osaccount_
-osgroup _osgroup_
[-retain
[-hourly [-count _n_\] [-duration  _m_\]\]
[-daily [-count _n_\] [-duration _m_\]\]
[-weekly  [-count _n_\] [-duration _m_\]\]
[-monthly [-count _n_\] [-duration _m_\]\] \]
[-profile-comment _profile-comment_\]
[-snapname-pattern _pattern_\]
[-protect [-protection-policy _policy_name_\]\] | [-noprotect\]\]
[-summary-notification
[-notification
[-success -email _email_address1,email_address2_
-subject subject-pattern\]
[failure -email _email_address1,email_address2_
-subject _subject-pattern_\] \]
[-separate-archivelog-backups
-retain-archivelog-backups -hours  _hours_ |
-days _days_ |
-weeks _weeks_ |
-months _months_
[-protect [-protection-policy _policy_name_ | -noprotect\]
[-include-with-online-backups | -no-include-with-online-backups\]\]
[-dump\]
[-quiet | -verbose\]]
----

== Parameters

* `*-profile _clone-profile_*`
+
Specifies the profile name from which the clone is created.

* `*-host _hostname_*`
+
Specifies the host name in which the clone exists.

* `*label _clone-label_*`
+
Specifies the label name generated by the clone operation.

* `*-id _clone-id_*`
+
Specifies the unique ID generated by the clone operation.

* `*-split-label split-_operation_label_*`
+
Specifies the label name generated by the clone operation.

* `*-new-profile _new-profile_name_*`
+
Specifies the new profile name that SnapManager will generate after a successful split operation.

* `*-profile-password _new-profile_password_*`
+
Specifies the password for the profile.

* `*-repository*`
+
Specifies the details of the database for the repository.

* `*-dbname _repo_service_name_*`
+
Specifies the name of the database that stores the repository. You can use either the global name or system identifier.

* `*-host _repo_host_*`
+
Specifies the name or IP address of the host computer on which the repository database resides.

* `*-port _repo_port_*`
+
Specifies the Transmission Control Protocol (TCP) port number used to access the host on which the repository database resides.

* `*-login*`
+
Specifies the repository login details. This is optional. If not specified, SnapManager defaults to OS Authentication Connection Mode.

* `*-username _repo_username_*`
+
Specifies the user name required to access the host on which the repository database resides.

* `*-database*`
+
Specifies the details of the database that will be backed up, restored, or cloned.

* `*-dbname _db_dbname_*`
+
Specifies the name of the database that the profile describes. You can use either the global name or system identifier.

* `*-host _db_host_*`
+
Specifies the name or IP address of the host computer on which the database resides.

* `*-sid _db_sid_*`
+
Specifies the system identifier of the database that the profile describes. By default, SnapManager uses the database name as the system identifier. If the system identifier is different from the database name, you must specify it using the -sid option.

* `*-login*`
+
Specifies the database login details.

* `*-username _db_username_*`
+
Specifies the user name needed to access the database that the profile describes.

* `*-password _db_password_*`
+
Specifies the password needed to access the database that the profile describes.

* `*-osaccount _osaccount_*`
+
Specifies the name of the Oracle database user account. SnapManager uses this account to perform the Oracle operations such as startup and shutdown. It is typically the user who owns the Oracle software on the host, for example, orasid.

* `*-osgroup _osgroup_*`
+
Specifies the name of the Oracle database group name associated with the orasid account.
+
NOTE: The -osaccount and -osgroup variables are required for UNIX but not allowed for databases running on Windows.

* `*-retain [-hourly [-count n] [-duration m]] [-daily [-count n] [-duration m]] [-weekly [-count n] [-duration m]] [-monthly [-count n] [-duration m]]*`
+
Specifies the retention policy for a backup.
+
For each retention class, either or both the retention count or retention duration might be specified. The duration is in units of the class (for example, hours for hourly, days for daily). For instance, if you specify only a retention duration of 7 for daily backups, then SnapManager will not limit the number of daily backups for the profile (because the retention count is 0), but SnapManager will automatically delete daily backups created over 7 days ago.

* `*-profile-comment _profile-comment_*`
+
Specifies the comment for a profile describing the profile domain.

* `*-snapname-pattern _pattern_*`
+
Specifies the naming pattern for Snapshot copies. You can also include custom text, for example, HAOPS for highly available operations, in all Snapshot copy names. You can change the Snapshot copy naming pattern when you create a profile or after the profile has been created. The updated pattern applies only to Snapshot copies that have not yet been created. Snapshot copies that exist retain the previous Snapname pattern. You can use several variables in the pattern text.

* `*-protect -protection-policy _policy_name_*`
+
Specifies whether the backup should be protected to secondary storage.
+
NOTE: If -protect is specified without -protection-policy, then the dataset will not have a protection policy. If -protect is specified and -protection-policy is not set when the profile is created, then it may be set later by the smsap profile update command or set by the storage administrator by using the Protection Manager's console.

* `*-summary-notification*`
+
Specifies the details for configuring summary email notification for multiple profiles under a repository database. SnapManager generates this email.

* `*-notification*`
+
Specifies the details for configuring email notification for the new profile. SnapManager generates this email. The email notification enables the database administrator to receive emails on the succeeded or failed status of the database operation that is performed by using this profile.

* `*-success*`
+
Specifies that email notification is enabled for a profile for when the SnapManager operation succeeds.

* `*-email _email address 1 email address 2_*`
+
Specifies the email address of the recipient.

* `*-subject _subject-pattern_*`
+
Specifies the email subject.

* `*-failure*`
+
Specifies that email notification is enabled for a profile for when the SnapManager operation fails.

* `*-separate-archivelog-backups*`
+
Specifies that the archive log backup is separated from the datafile backup. This is an optional parameter, which you can provide while creating the profile. After the backups are separated by using this option, you can either create datafiles-only backup or archive logs-only backup.

* `*-retain-archivelog-backups -hours _hours_ | -days _days_ | -weeks _weeks_| -months _months_*`
+
Specifies that the archive log backups are retained based on the archive log retention duration (hourly, daily, weekly, or monthly).

* `*protect [-protection-policy _policy_name_] | -noprotect*`
+
Specifies that the archive log files is protected based on the archive log protection policy.
+
Specifies that the archive log files are not protected by using the `-noprotect` option.

* `*-include-with-online-backups | -no-include-with-online-backups*`
+
Specifies that the archive log backup is included along with the online database backup.
+
Specifies that the archive log backups are not included along with the online database backup.

* `*-dump*`
+
Specifies that the dump files are not collected after the successful profile create operation.

* `*-quiet*`
+
Displays only error messages in the console. The default setting displays error and warning messages.

* `*-verbose*`
+
Displays error, warning, and informational messages in the console.
