---
permalink: unix-administration/reference-the-smosmsapcredential-set-command.html
sidebar: sidebar
keywords: command, credentials, user, access, resource, secure, host, repositories, repository, database, profile, snapmanager, run, password, smsap
summary: "This command lets you set the credentials for users to access secure resources, such as hosts, repositories, and database profiles. The host password is the user’s password on the host on which SnapManager is running. The repository password is the password of the Oracle user that contains the SnapManager repository schema. The profile password is a password that is made up by the person who creates the profile. For the host and repository options, if the optional -password option is not included, you will be prompted to enter a password of the type specified in the command arguments."
---
= The smsap credential set command
:icons: font
:imagesdir: ../media/

[.lead]
This command lets you set the credentials for users to access secure resources, such as hosts, repositories, and database profiles. The host password is the user's password on the host on which SnapManager is running. The repository password is the password of the Oracle user that contains the SnapManager repository schema. The profile password is a password that is made up by the person who creates the profile. For the host and repository options, if the optional `-password` option is not included, you will be prompted to enter a password of the type specified in the command arguments.

== Syntax

[subs=+macros]
----
pass:quotes[smsap credential set
[-host
-name _host_name_
-username _username_\]
[-password _password_\] \] |
[-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_\] [-password _repo_password_\] \]
-port _repo_port_ |
[-profile
-name _profile_name_\]
[-password _password_\] \]
[-quiet | -verbose]]
----

== Parameters

* `*-host _hostname_*`
+
Specifies the name or IP address of the host server on which SnapManager is running.
+
The `-host` parameter includes the following options:

 ** `-name _host_name_`: Specifies the name of the host for which you will set the password.
 ** `-username _user_name_`: Specifies the user name on the host.
 ** `-password _password_` Specifies the password of the user on the host.

* `*-repository -dbname*`
+
Specifies the name of the database that stores the profile. Use either the global name or the SID.
+
The `-repository` parameter includes the following options:

 ** `-dbname _repo_service_name_`: Specifies the name of the database that stores the profile. Use either the global name or the SID.
 ** `-host _repo_host_`: Specifies the name or IP address of the host server the repository database runs on.
 ** `-login-username _repo_username_`: Specifies the user name needed to access the database that stores the repository.
 ** `-password _password_`: Specifies the password needed to access the database that stores the repository.
 ** `-port _repo_port_`: Specifies the TCP port number used to access the database that stores the repository.

* `*-profile -name _profile_name_*`
+
Specifies the profile with which the database is associated.
+
The `-profile` parameter includes the following option:

 ** `-name _profilename_`: Specifies the name of the profile for which you will set the password.
 ** `-password _password_`: Specifies the password needed to access the profile.

* `*-quiet*`
+
Displays only error messages on the console. The default is to display error and warning messages.

* `*-verbose*`
+
Displays error, warning, and informational messages on the console.

---
== Example command for setting repository credentials

The following example sets credentials for a repository.

----

smsap credential set -repository -dbname SMSAPREPO -host hotspur -port 1527 -login -username chris
Password for chris@hotspur:1527/SMSAPREPO : ********
Confirm password for chris@hotspur:1527/SMSAPREPO : ********
----

----
SMSAP-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMSAP-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----
---
---
== Example command for setting host credentials

Because a host credential represents an actual operating system credential, it must include the username in addition to the password.

----
smsap credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----
---
