---
permalink: unix-administration/task-reset-profile-password.html
sidebar: sidebar
keywords: reset, profile, password, remember, provide
summary: "You can reset the profile password if you do not remember the password that you had provided while creating the profile."
---
= Reset the profile password
:icons: font
:imagesdir: ../media/

[.lead]
You can reset the profile password if you do not remember the password that you had provided while creating the profile.

*What you'll need*

* You must ensure that the SnapManager server is running on the repository database.
* You must have the root user credentials of the host on which the repository database is residing.
* You must ensure that the profile is not in use for any operation when the password is being reset for that profile.

*About this task*

You can reset the password from either the SnapManager CLI or GUI. While resetting the password, SnapManager queries the SnapManager server on the repository host to identify the operating system for the repository host. You must enter the authorized user credentials for connecting to the repository host. The SnapManager server authenticates users with their root credentials on the repository database. When the authentication is successful, SnapManager resets the profile password on the SnapManager server with the new password.

NOTE: SnapManager does not maintain the history of the password reset operations.

.Step

. Reset the profile password by entering the following command:
+
`*smsap password reset -profile _profile_ [-profile-password _profile_password_] [-repository-hostadmin-password _admin_password_]*`
