---
permalink: unix-administration/task_customize_e_mail_subject_for_a_new_profile.html
sidebar: sidebar
keywords: customize, email, subject, profile, create, customizing
summary: "You can customize the email subject for the new profile when you create it."
---
= Customize the email subject for a new profile
:icons: font
:imagesdir: ../media/

[.lead]
You can customize the email subject for the new profile when you create it.

You can customize the email subject by using the \{profile}_\{operation-name}_\{db-sid}_\{db-host}_\{start-date}_\{end-date}_\{status} pattern or enter your own text.

[cols="1a,3a,2a" options="header"]
|===
| Variable name| Description| Example value
a|
`_profile_`
a|
Profile name used for the database operation
a|
PROF1
a|
`_operation-name_`
a|
Database operation name
a|
Backup, Data Backup, Data and Archive Logs Backup
a|
`_db-sid_`
a|
SID of the database
a|
DB1
a|
`_db-host_`
a|
Name of the host server
a|
hostA
a|
`_start-date_`
a|
Start time of the database operation in the mmdd:hh:ss yyyy format
a|
April 27 21:00:45 PST 2012
a|
`_end-date_`
a|
End time of the database operation in the mmdd:hh:ss yyyy format
a|
April 27 21:10:45 PST 2012
a|
`_status_`
a|
Database operation status
a|
Success
|===
If you do not provide any value for the variables, then SnapManager displays the following error message: `Missing value(s) -subject.`

. Enter the following command:
+
`*smsap profile create -profile _profile_ [-profile-password _profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -portrepo_port-login -username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login -username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] -osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][-protect [-protection-policy _policy_name_]] [-notification [-success -email _email_address1,email_address2_ -subject _subject_pattern_] [-failure -email _email_address1,email_address2_ -subject _subject_pattern_]]*`

---
The following is an example showing the email subject pattern:

----

smsap profile create -profile sales1 -profile-password admin1 -repository -dbname repo2 -host 10.72.197.133 -port 1521 -login -username admin2 -database -dbname DB1 -host 10.72.197.142 -sid DB1
-osaccount oracle -osgroup dba -profile-notification -success -email admin@org.com -subject {profile}_{operation-name}_{db-sid}_{db-host}_{start-date}_{end-date}_{status}
----
---
