---
permalink: unix-administration/task_configuring_snapdrive_when_rbac_is_not_enabled.html
sidebar: sidebar
keywords: 
summary: 'You must register the root user or the administrator of the DataFabric Manager server and root user of the storage system with SnapDrive to enable data protection.'
---
= Configuring SnapDrive when RBAC is not enabled
:icons: font
:imagesdir: ../media/

[.lead]
You must register the root user or the administrator of the DataFabric Manager server and root user of the storage system with SnapDrive to enable data protection.

. To refresh the DataFabric Manager server to update the changes made directly on the storage system by the target database, enter the following command:
+
`dfm host discover storage_system`

. To register the root user or the administrator of the DataFabric Manager server with SnapDrive, enter the following command:
+
`snapdrive config set -dfm Administratordfm_host`

. To Register the root user or the administrator of the storage system with SnapDrive, enter the following command:
+
`snapdrive config set root storage_system`
