---
permalink: unix-administration/task_restoring_backup_using_single_file_snaprestore.html
sidebar: sidebar
keywords: 
summary: 'You can restore the backups by using the Single File SnapRestore \(SFSR\) method.'
---
= Restoring backups by using Single File SnapRestore
:icons: font
:imagesdir: ../media/

[.lead]
You can restore the backups by using the Single File SnapRestore (SFSR) method.

. Create a profile from the SnapManager graphical user interface (GUI).
. Back up the database by using the GUI.
. Unlink the Oracle and Network File System (NFS) service groups from the cluster service groups and freeze them.
. Ensure that Secure Shell (SSH) is configured between the hosts and SnapDrive for UNIX by setting #secure-communication-among-cluster-nodes to on in the snapdrive.conf file.
. From the SnapManager GUI, perform full backup restore and recovery by using --alllogs.
. Unfreeze the service groups and link them back to the cluster service group.
+
NOTE: This configuration is applicable only when you use SnapDrive 4.1.1 D2 for UNIX and SnapDrive 4.2 for UNIX.
+
If one restore operation is followed by another restore operation, then there is a possibility that the creation of the backup Snapshot copy fails. If you run successive restore operations within the specified time in which the SFSR can complete, then SnapManager for SAP will encounter Snapshot copy creation errors.
+
To prevent Snapshot copy creation errors, ensure that restore operations are performed after the time period during which SFSR is in progress.
+
To achieve this, check the LUN clone split process status by entering the following command from the storage system command-line interface (CLI): `rshfilernnamelun clone split statuslun-name`
+
----

Sample Output:
/vol/delaware_760gb/lun700gb (64% complete)..
----
+
NOTE: Volume-based SnapRestore (VBSR) is not supported on Solaris hosts running Veritas stack with SFRAC and VCS environment.
