---
permalink: unix-administration/task_cloning_databases_in_the_current_state.html
sidebar: sidebar
keywords: 
summary: 'You can create a backup and a clone of the database from the current state of the database by using a single command.'
---
= Cloning databases in the current state
:icons: font
:imagesdir: ../media/

[.lead]
You can create a backup and a clone of the database from the current state of the database by using a single command.

When you specify the profile with the -current option, SnapManager first creates a backup and then a clone from the current state of the database.

In the profile setting, if you have enabled the backup of data files and archive logs together for cloning, whenever you back up the online data files, the archive logs are also backed up. While cloning the database, SnapManager creates the data files backup along with the archive log backup and creates the database clone. If the archive log backup is not included, SnapManager does not create the archive log backup and therefore cannot create the clone of the database.

. To clone the database in its current state, enter the following command: `smsap clone create -profileprofile_name-current -labelclone_name-clonespec./clonespec_filename.xml`
+
This command takes a full automatic backup (generating the backup label) and immediately makes a clone from that backup, using an existing clone specification that you want to use.
+
NOTE: You can specify the -dump option as an optional parameter to collect the dump files after the successful or failed operations. The dump is collected for both the backup and clone operations.
