---
permalink: unix-administration/task_configure_snapdrive_when_rbac_is_not_enabled.html
sidebar: sidebar
keywords: register, root, user, administrator, datafabric, manager, server, storage, system, snapdrive, data, protection, configuring, configure, rbac
summary: "You must register the root user or the administrator of the DataFabric Manager server and root user of the storage system with SnapDrive to enable data protection."
---
= Configure SnapDrive when RBAC is not enabled
:icons: font
:imagesdir: ../media/

[.lead]
You must register the root user or the administrator of the DataFabric Manager server and root user of the storage system with SnapDrive to enable data protection.

.Steps

. To refresh the DataFabric Manager server to update the changes made directly on the storage system by the target database, enter the following command:
+
*Example*
+
`*dfm host discover _storage_system_*`

. To register the root user or the administrator of the DataFabric Manager server with SnapDrive, enter the following command:
+
*Example*
+
`*snapdrive config set -dfm _Administratordfm_host_*`

. To Register the root user or the administrator of the storage system with SnapDrive, enter the following command:
+
*Example*
+
`*snapdrive config set root _storage_system_*`
