---
permalink: unix-administration/task_adding_existing_profile_to_summary_notification.html
sidebar: sidebar
keywords: snapmanager, enable, exist, add, profile, summary, email, notification, update, updating
summary: SnapManager enables you to add an existing profile to a summary email notification while updating that profile.
---
= Adding an existing profile to summary email notifications
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager enables you to add an existing profile to a summary email notification while updating that profile.

. Enter the following command: `smsap profile update -profileprofile_name [-profile-passwordprofile_password] -repository-dbnamerepo_service_name-hostrepo_host-portrepo_port-login-usernamerepo_username-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port] [-rman {-controlfile | \{-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname} } ] -osaccountosaccount-osgrouposgroup [-retain [-hourly-countn] [-durationm]] [-daily-countn] [-durationm]] [-weekly-countn] [-durationm]] [-monthly-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][-protect [-protection-policypolicy_name]] [-summary-notification]`
