---
permalink: unix-administration/task_verifying_database_backups.html
sidebar: sidebar
keywords: backup, verify, command, block, database, backup, corrupt, operation, invoke, oracle, utility, data, file
summary: You can use the backup verify command to verify that the blocks in the database backup are not corrupted. The verify operation invokes the Oracle Database Verify utility for each data file in the backup.
---
= Verifying database backups
:icons: font
:imagesdir: ../media/

[.lead]
You can use the backup verify command to verify that the blocks in the database backup are not corrupted. The verify operation invokes the Oracle Database Verify utility for each data file in the backup.

SnapManager enables you to perform the verify operation at any time that is convenient for you and the users on your system. You can perform the verification immediately after creating the backup. You must specify the profile containing the backup and either the label or the ID of the backup you created.

NOTE: You can specify -dump to collect the dump files after the backup verify operation.

. Enter the following command: `smsap backup verify -profileprofile_name [-label label | -idid] [-force] [ -dump] [-quiet | -verbose]`

*Related information*

xref:reference_the_smosmsapbackup_verify_command.adoc[The smsap backup verify command]
