---
permalink: unix-administration/task_split_a_clone_on_a_primary_or_secondary_storage.html
sidebar: sidebar
keywords: clone, split, complete, metadata, remove, repository, primary, secondary, storage, delete, free
summary: "You can use the clone split command to split the clone. After the clone split is complete, the clone metadata is removed from the repository database and the backup associated with the clone can be deleted or freed."
---
= Split a clone on primary or secondary storage
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `clone split` command to split the clone. After the clone split is complete, the clone metadata is removed from the repository database and the backup associated with the clone can be deleted or freed.

*About this task*

The new profile created after the successful split operation is used for managing the split clone. The new profile will be like any other existing profile in SnapManager. You can use this profile to perform backup, restore, and clone operations.

In addition, you can also configure email notification for the new profile. This enables the database administrator to be notified about the status of the database operation performed using the profile.

NOTE: SnapManager supports the splitting operation when performed on a FlexClone only.

If the split operation fails, an appropriate error message with the reason for failure is displayed. The status of multiple operations is also displayed in the operation log. For example:

----
--[ INFO] The following operations were completed:
Clone Split : Success
Profile Create : Failed
Clone Detach : Success
----

You can optionally collect the dump files after a successful or failed clone split operation.

NOTE: After you enter the `clone split` command, you should not stop the SnapManager server until the clone split operation has started.

NOTE: SnapManager generates the profile even if you do not provide any value for the Oracle account (osaccount and osgroup).

.Step

. Enter the following command:
+
`*smsap clone split -profile _clone-profile_ -host _hostname_ [-label _clone-label_ | -id _clone-id_]-split-label _split-operation-label_ -comment _comment_ new-profile _new-profile-name_ [-profile-password _new-profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login-username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-siddb_sid] [-login-username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] -osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly-count _n_] [-duration _m_]] [-daily-count _n_] [-duration _m_]] [-weekly-count _n_] [-duration _m_]] [-monthly-count _n_] [-duration _m_]]] [-profile-comment _profile-comment_][-snapname-pattern _pattern_][-protect [-protection-policy _policy_name_]] | [-noprotect]][-summary-notification] [-notification [-success-email _email_address1, email_address2_ -subject _subject_pattern_] [-failure-email _email_address1, email_address2_ -subject _subject_pattern_]][-quiet | -verbose]-dump*`
