---
permalink: unix-administration/task_use_snapmanager_for_oraclesnapmanager_for_sapto_restore_a_local_backup_on_primary_storage.html
sidebar: sidebar
keywords: restore, local, backup, exist, primary, storage, entire, process, perform, snapmanager, sap
summary: "You can restore local backups that exist on primary storage. The entire process is performed using SnapManager for SAP."
---
= Using SnapManager for SAP to restore a local backup on primary storage
:icons: font
:imagesdir: ../media/

[.lead]
You can restore local backups that exist on primary storage. The entire process is performed using SnapManager for SAP.

*About this task*

You can also preview information about a backup restore process. You might want to do this to see information about restore eligibility of a backup. SnapManager analyzes data on a backup to determine whether the restore process can be completed by using the volume-based restore or the file-based restore method.

The restore preview shows the following information:

* Which restore mechanism (fast restore, storage-side file system restore, storage-side file restore, or host-side file copy restore) will be used to restore each file.
* Why more efficient mechanisms were not used to restore each file.

In preview of the restore plan, SnapManager does not restore anything. The preview shows information up to 20 files.

If you want to preview a restore of data files but the database is not mounted, then SnapManager mounts the database. If the database cannot be mounted, then the operation fails and SnapManager returns the database to its original state.

.Steps


. From the *Repository* tree, right-click the backup you want to restore, and select *Restore*.
. On the Restore and Recovery Wizard Welcome page, click *Next*.
. On the *Restore Configuration Information* page, select *Complete Datafile/Tablespace Restore with Control Files*.
. Click *Allow shutdown of database if necessary*.
+
SnapManager changes the database state, if necessary. For example, if the database is offline and it needs to be online, SnapManager forces it online.

. On the *Recovery Configuration Information* page, click *All Logs*.
+
SnapManager restores and recovers the database to the last transaction and applies all required logs.

. On the *Restore Source Location Configuration* page, view the information about the backup on primary and click *Next*.
+
If the backup exists only on primary storage, SnapManager restores the backup from the primary storage.

. On the *Volume Restore Configuration Information* page, select *Attempt volume restore* to attempt volume restore method.
. Click *Fallback to file-based restore*.
+
This allows SnapManager to use the file-based restore method if the volume restore method cannot be used.

. Click *Preview* to see the eligibility checks for fast restore and information about mandatory and overridable checks.
. On the *Perform Operation* page, verify the information you have entered, and click *Restore*.
. To view details about the process, click *Operation Details*.
