---
permalink: unix-administration/task_use_snapmanager_for_oraclesnapmanager_for_sap_to_create_the_database_profile_for_a_local_backup.html
sidebar: sidebar
keywords: database, administrator, snapmanager, database, initiate, local, storage, primary, system, creation, process, involve, manager
summary: "The database administrators use SnapManager to create a database profile that will be used to initiate a backup to local storage on a primary storage system. The entire profile creation and backup creation processes are performed entirely in SnapManager; they do not involve Protection Manager."
---
= Use SnapManager for SAP to create the database profile for a local backup
:icons: font
:imagesdir: ../media/

[.lead]
The database administrators use SnapManager to create a database profile that will be used to initiate a backup to local storage on a primary storage system. The entire profile creation and backup creation processes are performed entirely in SnapManager; they do not involve Protection Manager.

*About this task*

A profile contains the information about the database being managed, including its credentials, backup settings, and protection settings for backups. By creating a profile, you do not need to specify database details each time you perform an operation on that database, instead just provide the profile name. A profile can reference only one database. That same database can be referenced by more than one profile.

.Steps

. Go to the SnapManager for SAP client.
. From the SnapManager Repositories tree, right-click the host you want associated with this profile, and select *Create Profile*.
. In the Profile Configuration Information page, enter the following information and click *Next*.
 ** Profile name: payroll_prod
 ** Profile password: payroll123
 ** Comment: Production Payroll database
. In the Database Configuration Information page, enter the following information and click *Next*.
 ** Database name: PAYDB
 ** Database SID: payrolldb
 ** Database host: Accept the default
+
Because you are creating a profile from a host in the repository tree, SnapManager displays the host name.
. In the second Database Configuration Information page, accept the following database information and click *Next*:
 ** Host Account, representing the Oracle user account (for ora<sid>): orapayrolldb
 ** Host Group, representing the Oracle group: dba
. In the Database Connection Information page, select *Use database Authentication* to allow users to authenticate using database information.
+
For this example, enter the following information and click *Next*.

 ** SYSDBA Privileged User Name, representing the system database administrator who has administrative privileges: sys
 ** Password (SYSDBA password): oracle
 ** Port to connect to database host: 1527

. In the Snapshot Naming Information page, specify a naming convention for the Snapshots associated with this profile by selecting variables. The only variable that is required is the *smid* variable, which creates a unique snapshot identifier.
+
For this example, do the following:

 .. In the Variable Token list, select the *\{usertext}* variable and click *Add*.
 .. Enter "prod01.sample.com_" as the host name and click *OK*.
 .. Click *Left* until the host name appears just after "smsap" in the Format box.
 .. Click *Next*.

+
The Snapshot naming convention of `_smsap_hostname_smsapprofile_dbsid_scope_mode_smid_` becomes "smsap_prpd01.sample.com_P01_BACKUP_P01_f_a_x" (where the "f" indicates a full backup, the "a" indicates the automatic mode, and the "x" represents the unique SMID).

. On the Perform Operation page, verify the information and click *Create*.
. Click *Operation Details* to see information about the profile create operation and volume-based restore eligibility information.
