---
permalink: unix-administration/task_freeing_backups.html
sidebar: sidebar
keywords: free, backup, delete, snapshot, copies, copy, deleting, metadata, function, smsap, command
summary: You can free backups, which deletes the Snapshot copies without deleting the backup metadata. This function frees the space occupied by the backup. You can use the smsap backup free command to free the backups.
---
= Freeing backups
:icons: font
:imagesdir: ../media/

[.lead]
You can free backups, which deletes the Snapshot copies without deleting the backup metadata. This function frees the space occupied by the backup. You can use the smsap backup free command to free the backups.

For a backup to be eligible for freeing, you must ensure the following:

* Backup was successful
* Backup is not to be mounted
* Backup does not have clones
* Backup is not to be retained by using an unlimited retention policy
* Backup is not already freed

If protection is enabled on the profile and the protection policy contains connections from the primary node that use a mirror relationship, then Snapshot copies are deleted on the primary node when a backup is freed. Those Snapshot copies are also deleted from the mirror nodes when the next transfer to secondary storage occurs.

When you free a protected backup, SnapManager requests that Protection Manager remove the local Snapshot copies for the backup. If the backup free operation is successful for the protected backups, the Snapshot copies are deleted by Protection Manager in an asynchronous manner.

[options="header"]
|===
| Protection state| Local status| Action on primary storage| Action on secondary storage| Explanation
.2+a|
Not requested (to be protected)
a|
Exists
a|
Frees the backup
a|
No action required
a|
SnapManager frees the local backup.
a|
Freed
a|
No action required
a|
No action required
a|
The local backup is already freed.
.2+a|
Not protected
a|
Exists
a|
Frees the backup
a|
No action required
a|
SnapManager frees the local backup even though no copies exist on the secondary storage.
a|
Freed
a|
No action required
a|
No action required
a|
The local backup is already freed.
.2+a|
Protected
a|
Exists
a|
Frees the backup
a|
No action required; the backup on secondary remains
a|
SnapManager frees the local backup. Copies remain on the secondary storage.
a|
Freed
a|
No action required
a|
No action required
a|
The local backup is already freed.
|===
You can specify the -dump option as an optional parameter to collect the dump files after the successful or failed backup free operation.

. Enter the following command: `smsap backup free -profileprofile_name {-labellabel [data | -archivelogs] | -idid | -all} -force[-dump] [-quiet] [-force]`

*Related information*

xref:concept_what_protection_states_are.adoc[What protection states are]

xref:reference_the_smosmsapbackup_free_command.adoc[The smsap backup free command]
