---
permalink: unix-administration/task_setting_credentials_after_clearing_credential_cache.html
sidebar: sidebar
keywords: 
summary: 'After clearing the cache to remove the stored user credentials, you can set the credentials for the hosts, repositories, and profiles.'
---
= Setting credentials after clearing the credential cache
:icons: font
:imagesdir: ../media/

[.lead]
After clearing the cache to remove the stored user credentials, you can set the credentials for the hosts, repositories, and profiles.

You must ensure that you set the same user credentials for the repository, profile host, and profile that you had given earlier. An encrypted credentials file is created while setting the user credentials.

The credentials file is located at /root/.netapp/smsap/3.3.0.

From the SnapManager graphical user interface (GUI), if there is no repository under Repositories, perform the following steps:

. Click *Tasks* > *Add Existing Repository* to add an existing repository.
. Perform the following steps to set the credentials for repository:
 .. Right-click the repository and select *Open*.
 .. In the Repository Credentials Authentication window, enter the user credentials.
. Perform the following steps to set the credentials for host:
 .. Right-click the host under the repository and select *Open*.
 .. In the Host Credentials Authentication window, enter the user credentials.
. Perform the following steps to set the credentials for profile:
 .. Right-click the profile under the host and select *Open*.
 .. In the Profile Credentials Authentication window, enter the user credentials.
