---
permalink: unix-administration/task_protecting_archive_log_backups.html
sidebar: sidebar
keywords: create, creating, profile, enable, protection, archive, log, backup, policy, protect
summary: While creating profiles, you can enable protection for the archive log backups based on the archive log protection policy.
---
= Protecting archive log backups
:icons: font
:imagesdir: ../media/

[.lead]
While creating profiles, you can enable protection for the archive log backups based on the archive log protection policy.

. Enter the following command: `smsap profile create -profileprofile [-profile-passwordprofile_password] -repository-dbnamerepo_dbname-hostrepo_host-portrepo_port-login-usernamerepo_username-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port] [-rman {-controlfile | \{-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname} } ] -osaccountosaccount-osgrouposgroup [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][-protect [-protection-policypolicy_name]] [-summary-notification] [-notification [-success-emailemail_address1, email_address2-subjectsubject_pattern] [-failure-emailemail_address1, email_address2-subjectsubject_pattern]][-separate-archivelog-backups-retain-archivelog-backups-hourshours | -daysdays | -weeksweeks| -monthsmonths [-protect [-protection-policypolicy_name] | -noprotect] [-include-with-online-backups | -no-include-with-online-backups]] [-dump]`
+
[options="header"]
|===
| If...| Then...
a|
*You want to backup archive log backups separately and protect the archive log files*
a|
Specify the following options:

 ** -separate-archivelog-backups enables you to separate the archive log files from the data files.
 ** -protect assigns a separate protection policy for the archive log archive log backups.
 ** -protection-policy assigns the protection policy for the archive log backups.

+
|===
