---
permalink: unix-administration/task_mounting_backups.html
sidebar: sidebar
keywords: snapmanager, automatic, handle, mount, backup, available, host, scenario, external, tool, oracle, recovery, manager, rman, access, file
summary: "SnapManager automatically handles the mounting of a backup to make it available to the host. You can also mount backups in scenarios where you use an external tool, such as Oracle Recovery Manager (RMAN), to access the files in the backup."
---
= Mounting backups
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager automatically handles the mounting of a backup to make it available to the host. You can also mount backups in scenarios where you use an external tool, such as Oracle Recovery Manager (RMAN), to access the files in the backup.

*About this task*

The `smsap backup mount` command displays a list of paths where the Snapshot copies consisting of the backup have been mounted.

You can use the `-from-secondary` option to mount the backup from secondary storage. If you do not use this option, SnapManager mounts the backup from primary storage.

You must specify the `-copy-id` option whenever you specify the `-from-secondary` option. If there is more than one backup on the secondary storage system, the `-copy-id` option is used to specify which backup copy on the secondary storage should be used to mount the backup.6

NOTE: If you are using Data ONTAP operating in 7-Mode, you must specify a valid value for the `-copy-id` option. However, if you are using clustered Data ONTAP, the `-copy-id` option is not required.

If you are mounting a database backup to a remote host, you must ensure that the Automatic Storage Management (ASM) credentials are the same on both the hosts.

NOTE: You can optionally collect the dump files after a successful or failed backup mount operation.

.Step

. To Mount a backup enter the following command:
+
`*smsap backup mount -profile _profile_name label_ [data | -archivelogs] | -id _id_} [-host _-host_] [-from-secondary [-copy-id _id_]] [-dump] [-quiet | -verbose]*`
