---
permalink: unix-administration/task_cloning_protected_backups.html
sidebar: sidebar
keywords: 
summary: 'You can use SnapManager to clone a copy of a backup that has been protected.'
---
= Cloning protected backups
:icons: font
:imagesdir: ../media/

[.lead]
You can use SnapManager to clone a copy of a backup that has been protected.

The host (selected for the clone) must have access to the secondary storage using the same storage protocol (for example, SAN or NAS).

You can use the -from-secondary option to specify that you want to clone from the secondary storage.

You must specify the -copy-id option whenever you specify the -from-secondary option. If there is more than one backup on the secondary storage system, the -copy-id option is used to specify which backup copy on the secondary storage should be used for cloning.

NOTE: If you are using Data ONTAP operating in 7-Mode, you must specify a valid value for the -copy-id option. However, if you are using clustered Data ONTAP, the -copy-idoption is not required.

Deleting the clones of protected backups on secondary storage systems might fail. This issue occurs when the system time of the primary and secondary storage systems are not synchronized.

. Create a clone of a protected backup copy: `smsap clone create -backup-labelbackup_name-newsidnew_sid-labelclone_label-profileprofile_name-clonespecfull_path_to_clonespecfile-from-secondary -copy-idid`

== Example

----
smsap clone create -label testdb_clone_clstest
-profile sys_db_finance -from-secondary -copy-id 3042 sys_db_finance_sept_08
----

*Related information*

xref:concept_about_different_protection_policies.adoc[About different protection policies]
