---
permalink: unix-administration/task_issuing_commands_from_an_alternate_host.html
sidebar: sidebar
keywords: issue, cli, command, host, database, snapmanager, route, issuing, alternate
summary: "You can issue CLI commands from a host other than the database host and SnapManager will route the commands you enter to the appropriate host."
---
= Issuing commands from an alternate host
:icons: font
:imagesdir: ../media/

[.lead]
You can issue CLI commands from a host other than the database host and SnapManager will route the commands you enter to the appropriate host.

*About this task*

For the system to dispatch an operation to the correct host, it must first know where to find the profile for the operation. In this procedure the system keeps the profile to repository mapping information for a file in the user's home directory on the local host.

.Step

. To make the local user's home directory aware of the profile-to-repository mappings so it can route the operation request, enter the following command:
+
`*smsap profile sync -repository-dbname _repo_dbname_ -host _repo_host_ -port _repo_port_ -login-username _repo_username_ [-quiet | -verbose]*`
