---
permalink: unix-administration/task_scheduling_archive_log_file_pruning.html
sidebar: sidebar
keywords: create, backup, schedule, pruning, prune, archive, log, file, scheduling
summary: When you create a backup, you can schedule the pruning of archive log files to occur at a specified time.
---
= Scheduling archive log file pruning
:icons: font
:imagesdir: ../media/

[.lead]
When you create a backup, you can schedule the pruning of archive log files to occur at a specified time.

SnapManager allows you to prune the archive log files periodically from the active file system.

. Enter the following command: `smsap schedule create -profile profile_name {[-full {-online \| -offline \| -auto}[-retain [-hourly | -daily | -weekly | -monthly | -unlimited] [-verify]] | [-data [-filesfiles [files]] | [-tablespaces-tablespaces [-tablespaces]] {-online \| -offline \| -auto}[-retain [-hourly | -daily | -weekly | -monthly | -unlimited] [-verify]] | [-archivelogs]} [-commentcomment] [-protect | -protectnow | -noprotect] [-backup-destpath1 [,[path2]] [-exclude-destpath1 [,path2]] [-prunelogs{-all | -untilSCNuntilSCN | -before {-dateyyyy-MM-dd HH:mm:ss | -monthsmonths | -weeksweeks | -daysdays | -hourshours}} -prune-destprune_dest1,,prune_dest2] -schedule-nameschedule_name [-schedule-commentschedule_comment] -interval {-hourly | -daily | -weekly | -monthly | -onetimeonly} -cronstringcronstring-start-time {start-timestart_time <yyyy-MM-dd HH:mm\>} -runasuser-runasuser [-force] [-quiet | -verbose]`
+
[options="header"]
|===
| If you want to...| Then...
a|
*Schedule pruning of archive log files*
a|
Specify the following options:

 ** -prunelogs to schedule pruning of the archive log files
 ** -prune-dest to prune archive log files from the archive log destinations

a|
*Include a name for the schedule*
a|
Specify the -schedule-name option.
a|
*Schedule pruning of archive log files at specific time interval*
a|
Specify the interval option and indicate whether the archive log files should be pruned based on the following interval classes:

 ** -hourly
 ** -daily
 ** -weekly
 ** -monthly
 ** -onetimeonly

a|
*Add a comment about the schedule operation*
a|
Specify the -schedule-comment option followed by the description string.
a|
*Specify the start time of the schedule operation*
a|
Specify the -start-time option in the yyyy-mm-dd hh:mm format.
|===
