---
permalink: unix-administration/task_viewing_clone_split_estimate.html
sidebar: sidebar
keywords: 
summary: 'The clone split estimate helps you know the total free space available on the aggregate, the amount of space shared between the clone and the original database, and the space exclusively used by the clone. In addition, you can view the date and time at which the underlying clone was created and the age of the clone. Based on this estimate, you decide whether to split a clone or not.'
---
= Viewing a clone split estimate
:icons: font
:imagesdir: ../media/

[.lead]
The clone split estimate helps you know the total free space available on the aggregate, the amount of space shared between the clone and the original database, and the space exclusively used by the clone. In addition, you can view the date and time at which the underlying clone was created and the age of the clone. Based on this estimate, you decide whether to split a clone or not.

To view the clone split estimate, you must enter the profile name of the original clone and the label or GUID of the clone operation. If the clone is in a different host, you can specify the host name.

. To view the clone split estimate, enter the following command: `smsap clone split-estimate -profileprofile [-hosthostname] [-labelclone-label | -idclone-id][-quiet \| -verbose]`

The following example shows the command for clone split storage estimate:

----

					smsap clone split-estimate
-profile p1 -label clone_test_label
----
