---
permalink: unix-administration/task_update_profiles.html
sidebar: sidebar
keywords: update, profile, modify, password, database, operating, system, os, authentication, updating, information, host, database, oracle, updating
summary: "You can update the profiles to modify the profile password, the number of backups to retain, access to the database, the operating system (OS) authentication to database authentication and vice versa, and information about the host. If the Oracle database password information changes, you must also change that information in the profile."
---
= Update profiles
:icons: font
:imagesdir: ../media/

[.lead]
You can update the profiles to modify the profile password, the number of backups to retain, access to the database, the operating system (OS) authentication to database authentication and vice versa, and information about the host. If the Oracle database password information changes, you must also change that information in the profile.

*About this task*

If protection policy is enabled on the profile, you cannot change the policy by using SnapManager. The storage administrator must change the policy by using the Protection Manager's console.

SnapManager (3.2 or later) enables you to update the profile to separate archive log backups from the data file backups by using the `-separate-archivelog-backups` option. You can specify separate retention durationand protection policy for the archive log backup. SnapManager enables you to include the archive log backup along with online database backup. You can also create an online datafile backup and archive log backup together for cloning. When you create an online data files backup, the archive logs backups are immediately created along with the data files.

.Steps

. Enter the following command:
+
`*smsap profile update -profile _profile_ [-new-profile _new_profile_name_] [-profile-password _profile_password_][-database-dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login -username _db_username_ -password _db_password_ -port _db_port_][-asminstance -asmusername _asminstance_username_ -asmpassword _asminstance_password_]] [{-rman{-controlfile | {-login  -username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_}}} | -remove-rman]-osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname -pattern _pattern_][[-protect [-protection-policy _policy_name_]]| [[-noprotect]] [-summary-notification] [-notification [-success-email _email_address1, email_address2_ -subject _subject_pattern_] [-failure-email _email_address1, email_address2_ -subject _subject_pattern_]] [-separate-archivelog-backups-retain-archivelog-backups-hours _hours_ | -days _days_ | -weeks _weeks_| -months _months_ [-protect [-protection-policy _policy_name_] | -noprotect] [-include-with-online-backups | -no-include-with-online-backups]] [-dump]*`
+
Other options for this command are as follows:
+
[-force] [-noprompt]
+
[-quiet | verbose]
+
[cols="2a,4a" options="header"]
|===
| If you want to...| Then...
a|
*Change the profile to use operating system authentication*
a|
Instead of adding the user name, password, and port, specify the following:

 ** `-osaccount _account_name_` as the name of the operating system account
 ** `-osgroup _osgroup_` as the group associated with the operating system account, typically the account used to install Oracle

a|
*Use Automatic Storage Management (ASM) instance authentication to create the profile*
a|
Specify the credentials for ASM instance authentication.

 ** `-asmusername _asminstance_username_` is the user name used to log in to the ASM instance.
 ** ``-asmpassword _asminstance_password_` is the password used to log in to the ASM instance.

a|
*Use a catalog as the Oracle Recovery Manager (RMAN) repository, or you want to remove RMAN*
a|
Specify the following options and variables:

 ** `-tnsname _tnsname_` as the tnsname defined in the `tnsnames.ora` file.
 ** `-login -username _username_` as the user name required to connect to the RMAN catalog.
+
If not specified, SnapManager uses the operating system authentication information. You cannot use operating system authentication with Real Application Clusters (RAC) databases.

 ** `-password _password_` as the RMAN password required to connect to the RMAN catalog.
 ** `-controlfile` if you are using the control file as the RMAN repository.
 ** `-remove-rman` to remove RMAN.

a|
*Change the backup retention policy for backups of the database in the profile*
a|
Specify either the retention count or retention duration for a retention class, or both to change the retention policy. The duration is in units of the class (for example, hours for hourly, days for daily).

 ** `-hourly` is the hourly retention class, for which `[-count _n_] [-duration _m_]]` are the retention count and retention duration, respectively.
 ** `-daily` is the daily retention class, for which `[-count _n_] [-duration _m_]]` are the retention count and retention duration, respectively.
 ** `-weekly` is the weekly retention class, for which `[-count _n_] [-duration _m_]]` are the retention count and retention duration, respectively.
 ** `-monthly` is the monthly retention class, for which `[-count _n_] [-duration _m_]]` are the retention count and retention duration, respectively.

a|
*Disable backup protection for the profile*
a|
Specify `-noprotect` to not protect the database backups created by using the profile.    For a profile that had `-protect` enabled, if you want to disable protect, a warning message is displayed stating that this action will delete the dataset and you will not be able to restore or clone backups for this profile.
a|
*Enable email notifications for the completion status of the database operations*
a|
Specify the following options and variables:

 ** `-summary-notification` enables you to configure a summary email notification for multiple profiles under a repository database.
 ** `-notification` enables you to receive an email notification on the completion status of the database operation for a profile.
 ** `-success -email _email_address2_` enables you to receive an email notification following the completion of a successful database operation performed by using a new or an existing profile.
 ** `-failure -email _email_address2_` enables you to receive an email notification on a failed database operation performed by using a new or an existing profile.
 ** `-subject _subject_text_` specifies subject text for the email notification while creating a new profile or an existing profile.
If the notification settings are not configured for the repository and you are trying to configure profile or summary notifications by using the command-line interface (CLI), the following message is logged in the console log: `SMSAP-14577: Notification Settings not configured`.

+
If you have configured the notification settings and you are trying to configure summary notification by using the CLI without enabling summary notification for the repository, the following message is logged in the console log: `SMSAP-14575: Summary notification configuration not available for this repository`
a|
*Update the profile to create backup of the archive log files separately*
a|
Specify the following options and variables:

 ** `-separate-archivelog-backups` enables you to create a backup of the archive log files separately from the database files.
+
After you specify this option, you can either create a data files-only backup or an archivelogs-only backup. You cannot create a full backup. Also, you cannot revert the profile settings by separating the backup. SnapManager retains the backups based on the retention policy for the backups that were created before taking archivelogs-only backup.

 ** `-retain-archivelog-backups` sets the retention duration for archive log backups.
+
NOTE: If you are updating the profile for the first time, you can separate the archive log backups from the data files backup by using the `-separate-archivelog-backups` option; you must provide the retention duration for the archive log backups by using the `-retain-archivelog-backups` option. Setting the retention duration is optional when you later update the profile.

 ** `-protect` creates an application dataset in the Data Fabric Manager (DFM) server and adds members related to the database, data file, control files, and archive logs.
+
If the dataset exists, it is reused when a profile is created.

 ** `-protection-policy` sets the protection policy to the archive log backups.
 ** `-include-with-online-backups` specifies that the archive log backup is included along with the database backup.
 ** `-no-include-with-online-backups` specifies the archive log file backup is not included along with the database backup.

a|
*Change the host name of the target database*
a|
Specify ``-host _new_db_host_` to change the host name of the profile.
a|
*Collect the dump files after the profile update operation*
a|
Specify the `-dump` option.
|===

. To view the updated profile, enter the following command: smsap profile show
