---
permalink: unix-administration/task_changing_the_retention_policy_default_behavior.html
sidebar: sidebar
keywords: backup, expire, base, retention, policy, snapmanager, determine, delete, back, up, setting, behavior, unprotect, protect, changing, change
summary: When a backup expires based on the retention policy, SnapManager determines whether to delete the backup based on the retention settings. Deletion of backups is the default behavior. You can change this default behavior and choose to free the unprotected backups instead.
---
= Changing the retention policy default behavior
:icons: font
:imagesdir: ../media/

[.lead]
When a backup expires based on the retention policy, SnapManager determines whether to delete the backup based on the retention settings. Deletion of backups is the default behavior. You can change this default behavior and choose to free the unprotected backups instead.

By default, SnapManager deletes or frees backups depending on whether they are protected or not as follows:

* For protected backups, SnapManager frees the local backups when they expire.
* For unprotected backups, SnapManager deletes the local backups when they expire.
+
You can change this default behavior.

For protected backups, SnapManager does not consider the following in determining whether to delete the local copy:

* The backup to secondary storage failed or is in process of being protected.
+
This enables the transfer of backups to secondary storage before the retention policy is applied.

* The copy was subsequently deleted from secondary storage.

. Access the following default location:
+
default smsap installation location/properties/smsap.config

. Edit the smsap.config file.
. Set the retain.alwaysFreeExpiredBackups property in the smsap.config file to true.
+
For example, `retain.alwaysFreeExpiredBackups = true`

*Related information*

xref:reference_the_smosmsapbackup_update_command.adoc[The smsap backup update command]
