---
permalink: unix-administration/task_restoring_backups_from_an_alternate_location.html
sidebar: sidebar
keywords: restore, backup, alternate, location, data, file, intermediate, system, block, raw, device, restoring
summary: You can restore backups from an alternate location to restore the data files from an intermediate file system to an active file system, or to restore the blocks of data from an intermediate raw device into an active raw device.
---
= Restoring backups from an alternate location
:icons: font
:imagesdir: ../media/

[.lead]
You can restore backups from an alternate location to restore the data files from an intermediate file system to an active file system, or to restore the blocks of data from an intermediate raw device into an active raw device.

* Create a restore specification XML file and specify the type of restore method you want to use.

You can use the smsap backup restore command and specify the restore specification XML file you created to restore the backup from an alternate location.

. Enter the following command: `smsap backup restore -profileprofile-labellabel-complete-alllogs-restorespecrestorespec`

*Related information*

xref:reference_the_smosmsapbackup_restore_command.adoc[The smsap backup restore command]
