---
permalink: unix-administration/task_using_snapmanager_for_oraclesnapmanager_for_sap_to_create_a_protected_backup.html
sidebar: sidebar
keywords: create, creating, backup, example, dba, select, full, set, secondary, storage, local, protection-enabled, profile, transfer, protection, policy
summary: When creating a backup for this example, the DBA selects to create a full backup, sets backup options, and selects protection to secondary storage. Although the backup is initially made on local storage, because this backup is based on a protection-enabled profile, the backup is then transferred to secondary storage according to the protection policy’s schedule as defined in Protection Manager.
---
= Using SnapManager for SAP to create a protected backup
:icons: font
:imagesdir: ../media/

[.lead]
When creating a backup for this example, the DBA selects to create a full backup, sets backup options, and selects protection to secondary storage. Although the backup is initially made on local storage, because this backup is based on a protection-enabled profile, the backup is then transferred to secondary storage according to the protection policy's schedule as defined in Protection Manager.

. Go to the SnapManager for SAP client.
. From the SnapManager Repository tree, right-click the profile containing the database that you want to back up, and select *Backup*.
+
The SnapManager for SAP Backup Wizard starts.

. Enter `Production_payroll` as the label.
. Enter `Production payroll Jan 19 backup` as the comment.
. Select *Auto* as the type of backup that you want to create.
+
This allows SnapManager to determine whether to perform an online or offline backup.

. Select *Daily* or *Weekly* as the frequency of the backup.
. To confirm that the backup is in a valid format for Oracle, check the box next to *Verify backup*.
+
This operation uses Oracle DBVerify to check the block format and structure.

. To force the state of the database into the appropriate mode (for example, from open to mounted), select *Allow startup or shutdown of database, if necessary*, and click *Next*.
. In the Database, Tablespaces, or Datafiles to Backup page, select *Full Backup* and click *Next*.
. To protect the backup on secondary storage, check *Protect the Backup* and click *Next*.
. In the Perform Operation page, verify the information you supplied and click *Backup*.
. In the progress page, view the progress and results of the backup creation.
. To view the details of the operation, click *Operation Details*.
