---
permalink: unix-administration/task_configuring_snapdrive_in_an_active_active_unix_environment.html
sidebar: sidebar
keywords: host-cluster-sw-restore-warn, parameter, snapdrive, conf, assign, value, support, restore, operation, active, veritas, storage, foundation, oracle, rac, sfrac, environment
summary: "If you have included the host-cluster-sw-restore-warn parameter in snapdrive.conf and have assigned the value on, you must change the value to support the restore operation in the active/active Veritas Storage Foundation for Oracle RAC (SFRAC) environment."
---
= Configuring SnapDrive for UNIX for an active/active Veritas SFRAC environment
:icons: font
:imagesdir: ../media/

[.lead]
If you have included the `host-cluster-sw-restore-warn` parameter in snapdrive.conf and have assigned the value on, you must change the value to support the restore operation in the active/active Veritas Storage Foundation for Oracle RAC (SFRAC) environment.

When you are using the active/active Veritas Storage Foundation for Oracle RAC (SFRAC) environment, if the `host-cluster-sw-restore-warn` parameter is set to `*on*`, a warning message is displayed and the restore operation is stopped. If you want to perform the restore operation in an active/active Veritas SFRAC environment, you must set `host-cluster-sw-restore-warn` to `*off*`.

For information on `snapdrive.conf`, see SnapDrive documentation.

.Steps

. Log in as the root user.
. Open the `snapdrive.conf` file by using a text editor.
. Change the value of `host-cluster-sw-restore-warn` to `*off*`.

*After you finish*

After configuring, restart the SnapDrive for UNIX server.

*Related information*

http://mysupport.netapp.com/[Documentation on the NetApp Support Site: mysupport.netapp.com^]
