---
permalink: unix-administration/task_updating_target_database_hostname_associated_with_a_profile.html
sidebar: sidebar
keywords: snapmanager, sap, ability, update, host, name, target, database, profile
summary: SnapManager \(3.2 or later\) for SAP provides the ability to update the host name of the target database in the SnapManager profile.
---
= Updating the target database host name associated with a profile
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager (3.2 or later) for SAP provides the ability to update the host name of the target database in the SnapManager profile.

* The local user's home directory must be aware of the profile-to-repository mappings.
* The SnapManager graphical user interface (GUI) sessions must be closed.
* In a Real Application Clusters (RAC) environment, the clones or mounted backups available on the host specified in the profile must be deleted and unmounted.

You can update the profile with the new host name by using only the CLI.

*Scenarios not supported for changing the target database host name in profile*

The following scenarios not supported for changing the target database host name in the profile:

* Changing the target database host name by using the SnapManager GUI
* Rolling back of the repository database after updating the target database host name of the profile
* Updating multiple profiles for a new target database host name by running a single command
* Changing the target database host name when any SnapManager operation is running
* Changing the target database host name if SnapManager is installed on Solaris and if the database logical unit numbers (LUNs) are created by using host-mounted file system with SVM stack.

NOTE: After you update the target database host name in the profile, only the target database host name is changed. All the other configuration parameters set on the profile are retained.

After you update the new target database host name in a protection-enabled profile, the same dataset and protection policies are retained for the updated profile.

After you change the host name for the target host, you must ensure that you update the host name for all the existing protected profiles before creating the new protected profiles. To update the host name for a profile, run the smsap profile update command.

After you update the target database host name, you cannot deleteor split the clone or unmount the backup if the clone or mounted backup is not available in the new host. In such scenarios, running the SnapManager operations from the new host lead to failure as well as stale entries in the earlier host. To perform SnapManager operations, you must revert to the earlier host name by using profile update.

. Enter the following command: `smsap profile update -profileprofile [-profile-passwordprofile_password][-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port]] [{-rman{-controlfile | {-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname}}} | -remove-rman]-osaccountosaccount-osgrouposgroup [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][[-protect [-protection-policypolicy_name]]| [[-noprotect]] [-summary-notification] [-notification [-success-emailemail_address1, email_address2-subjectsubject_pattern] [-failure-emailemail_address1, email_address2-subjectsubject_pattern]] [-separate-archivelog-backups-retain-archivelog-backups-hourshours | -daysdays | -weeksweeks| -monthsmonths [-protect [-protection-policypolicy_name] | -noprotect] [-include-with-online-backups | -no-include-with-online-backups]] [-dump]`
+
Other options for this command are as follows:
+
[-force] [-noprompt]
+
[quiet | -verbose]
+
[options="header"]
|===
| If you want to...| Then...
a|
*Change the target database host name*
a|
Specify -hostnew_db_host
|===

. To view the target database host name of the profile, enter the following command: `smsap profile show`
