---
settings:
  name: SnapManager for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    langs: "us-en,ja-jp,zh-cn"
sidebar:
  entries:
    - title: SnapManager for SAP docs
      url: "/index.html"
    - title: Release Notes
      url: "/reference-releasenotes.html"
    - section: unix-administration
    - section: unix-installation-7mode
    - section: unix-installation-cmode
    - section: windows
    - title: Legal notices
      url: "/legal-notices.html"
      
homepage:
  tiles:
    - title: Get started
      links:
        - title: Product overview
          url: /reference_smsap_isg_product_overview.html
        - title: Release Notes
          url: reference-releasenotes.html
    - title: Administration Guide for UNIX
      links:
        - title: Product overview
          url: /reference_smsap_isg_product_overview.html
    - title: Installation and Setup For UNIX For Data ONTAP Operating in 7-Mode
      links:
        - title: Product overviews
          url: /reference_smsap_isg_product_overview.html
    - title: Installation and Setup For UNIX For Clustered Data ONTAP
      links:
        - title: Product overview
          url: /reference_smsap_isg_product_overview.html
    - title: Installation and Administration Guide for Windows
      links:
        - title: Product overviews
          url: /reference_smsap_isg_product_overview.html
    - title: More resources
      links:
        - title: SnapManager for SAP videos
          url:
        - title: SnapManager for SAP blogs
          url:
        - title: Documentation for earlier versions
          url:
