---
settings:
  name: SnapManager for SAP
sidebar:
  entries:
    - title: SnapManager for SAP docs
      url: "/index.html"
    - title: Release Notes
      url: "/reference-releasenotes.html"
    - section: unix-administration
    - section: unix-installation-7mode
    - section: unix-installation-cmode
    - section: windows
    - title: Legal notices
      url: "/legal-notices.html"
