---
settings:
  name: SnapManager for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    langs: "us-en,ja-jp,zh-cn"
sidebar:
  entries:
    - title: SnapManager for SAP docs
      url: "/index.html"
    - title: Release notes
      url: "/reference-releasenotes.html"
    - section: unix-installation-cmode
    - section: unix-installation-7mode
    - section: unix-administration
    - section: windows
    - title: Legal notices
      url: "/legal-notices.html"
      