---
settings:
  name: SnapManager for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    langs: "us-en,ja-jp,zh-cn"
sidebar:
  entries:
    - title: SnapManager for SAP docs
      url: "/index.html"
    - title: Release notes
      url: "/reference-releasenotes.html"
    - section: unix-administration
    - section: unix-installation-7mode
    - section: unix-installation-cmode
    - section: windows
    - title: Legal notices
      url: "/legal-notices.html"

homepage:
  tiles:
    - title: Get started
      links:
        - title: Product overview
          url: /unix-installation-cmode/reference-smsap-isg-product-overview.html
        - title: Release notes
          url: reference-releasenotes.html
    - title: Administration
      links:
        - title: Configuring SnapManager for UNIX
          url: /unix-administration/concept-configuring-snapmanager-for-oraclesap.html
        - title: Configuring SnapManager for Windows
          url: /windows/concept-configuring-snapmanager-for-oraclesap.html
    - title: Installation and setup
      links:
        - title: Deployment workflow (7-Mode)
          url: /unix-installation-7mode/reference-smsap-isg-deployment-workflow.html
        - title: Deployment workflow (Cluster Mode)
          url: /unix-installation-cmode/reference-smsap-isg-deployment-workflow.html
    - title: More resources
      links:
        - title: NetApp Support
          url: https://mysupport.netapp.com/site/global/dashboard
        - title: NetApp Communities
          url: https://community.netapp.com/
