---
permalink: unix-installation-cmode/concept_limitations_for_performing_a_rollback.html
sidebar: sidebar
keywords: scenario, perform, rollback, task, rollback, limitation
summary: You must be aware of the scenarios in which you cannot perform a rollback. However, for some of these scenarios you can perform some additional tasks before performing rollback.
---
= Limitations for performing a rollback
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of the scenarios in which you cannot perform a rollback. However, for some of these scenarios you can perform some additional tasks before performing rollback.

The scenarios in which you cannot perform rollback or have to perform the additional tasks are as follows:

* If you perform one of the following operations after performing a rolling upgrade:
 ** Create a new profile.
 ** Split a clone.
 ** Change the protection status of the profile.
 ** Assign protection policy, retention class, or SnapVault and SnapMirror relationships.
+
In this scenario, after performing a rollback, you must manually remove the protection policy, retention class, or SnapVault and SnapMirror relationships that were assigned.

 ** Change the mount status of the backup.
+
In this scenario, you must first change the mount status to its original state and then perform a rollback.

 ** Restore a backup.
 ** Change the authentication mode from database authentication to operating system (OS) authentication.
+
In this scenario, after performing a rollback, you must manually change the authentication mode from OS to database.
* If the host name for the profile is changed
* If profiles are separated to create archive log backups
+
In this scenario, you cannot rollback to a version that is earlier than SnapManager 3.2.
