---
permalink: unix-installation-cmode/reference_prepare_storage_systems_for_snapmirror_and_snapvault_replication.html
sidebar: sidebar
keywords: 
summary: 'You can use SnapManager with ONTAP SnapMirror technology to create mirror copies of backup sets on another volume, and with ONTAP SnapVault technology to perform disk-to-disk backup replication for standards compliance and other governance-related purposes. Before you perform these tasks, you must configure a data-protection relationship between the source and destination volumes and initialize the relationship.'
---
= Preparing storage systems for SnapMirror and SnapVault replication
:icons: font
:imagesdir: ../media/

[.lead]
You can use SnapManager with ONTAP SnapMirror technology to create mirror copies of backup sets on another volume, and with ONTAP SnapVault technology to perform disk-to-disk backup replication for standards compliance and other governance-related purposes. Before you perform these tasks, you must configure a data-protection relationship between the source and destination volumes and initialize the relationship.

A data protection relationship replicates data on primary storage (the source volume) to secondary storage (the destination volume). When you initialize the relationship, ONTAP transfers the data blocks referenced on the source volume to the destination volume.

*Related information*

xref:concept_understanding_the_differences_between_snapmirror_and_snapvault.adoc[Understanding the differences between SnapMirror and SnapVault]

xref:task_preparing_storage_systems_for_snapmirror_replication.adoc[Preparing storage systems for SnapMirror replication]

xref:task_preparing_storage_systems_for_snapvault_replication.adoc[Preparing storage systems for SnapVault replication]
