---
permalink: unix-installation-cmode/reference_smsap_isg_host_requirements.html
sidebar: sidebar
keywords: 
summary: 'You must install SnapManager for SAP on every host where the database you want to backup is hosted. You must ensure that your hosts meet the minimum requirements for SnapManager configuration.'
---
= UNIX host requirements
:icons: font
:imagesdir: ../media/

[.lead]
You must install SnapManager for SAP on every host where the database you want to backup is hosted. You must ensure that your hosts meet the minimum requirements for SnapManager configuration.

* You must install SnapDrive on the database host before you install SnapManager.
* You can install SnapManager either on physical or virtual machines.
* You must install the same version of SnapManager on all hosts that share the same repository.
* You must install Oracle patch 13366202 if you are using Oracle databases 11.2.0.2 or 11.2.0.3.
+
If you are using DNFS, you must also install the patches listed in the My Oracle Support (MOS) report 1495104.1 for maximum performance and stability.

To use the SnapManager graphical user interface (GUI), you must have a host running on one of the following platforms. The GUI also requires that Java Runtime Environment (JRE) 1.8 is installed on the host.

* Red Hat Enterprise Linux
* Oracle Enterprise Linux
* SUSE Enterprise Linux
* Solaris SPARC, x86, and x86_64
* IBM AIX

NOTE: SnapManager also operates in the VMware ESX virtualized environment.
