---
permalink: unix-installation-cmode/task_create_the_repository_database_instance.html
sidebar: sidebar
keywords: repository, database, instance, oracle, snapmanager, stand-alone, target, create
summary: "The repository database instance is an Oracle database in which you create the SnapManager repository. The repository database instance must be a stand-alone database and cannot be the target database."
---
= Create the repository database instance
:icons: font
:imagesdir: ../media/

[.lead]
The repository database instance is an Oracle database in which you create the SnapManager repository. The repository database instance must be a stand-alone database and cannot be the target database.

== What you'll need

You must have an Oracle database and a user account to access the database.

.Steps
. Log in to SQL *Plus: `sqlplus '/ as sysdba'`
. Create a new tablespace for the SnapManager repository: `*create tablespacetablespace_name datafile ′/u01/app/oracle/oradata/datafile/tablespace_name.dbf′ size 100M autoextend on;*`
+
`tablespace_name` is the name of the tablespace.

. Verify the block size of the tablespace: `*select tablespace_name, block_size from dba_tablespaces;*`
+
SnapManager requires a minimum 4-K block size for the tablespace.

*Related information*

http://www.netapp.com/us/media/tr-3761.pdf[NetApp Technical Report 3761: SnapManager for Oracle: Best Practices^]
