---
permalink: unix-installation-cmode/task-smsap-isg-back-up-your-database.html
sidebar: sidebar
keywords: create, back up, database, schedule, initial, verification
summary: "After creating a profile, you must back up your database. You can schedule recurring backups after the initial backup and verification."
---
= Back up your database
:icons: font
:imagesdir: ../media/

[.lead]
After creating a profile, you must back up your database. You can schedule recurring backups after the initial backup and verification.

== About this task

These steps show how to create a backup of your database using the SnapManager user interface. You can also use the command-line interface (CLI) if you prefer.

For information about how to create backups using the CLI or SAP BR* Tools, see the _SnapManager for SAP Administration guide for UNIX_.

.Steps
. From the Repositories tree, right-click the profile containing the database you want to back up, and select *Backup*.
. In *Label*, enter a custom name for the backup.
+
You must not include spaces or special characters in the name. If you do not specify a name, SnapManager automatically creates a backup label.
+
From SnapManager 3.4, you can modify the backup label created automatically by SnapManager. You can edit the `override.default.backup.pattern` and `new.default.backup.pattern` configuration variables to create your own default backup label pattern.

. Optional: In *SnapVault Label*, you must enter the SnapMirror label that you specified in the rules of the SnapMirror policy while setting up the SnapVault relationship.
+
NOTE: The *SnapVault Label* field appears only if you have selected _SnapManager_cDOT_Vault_ as the protection policy while creating the profile.

. Select *Allow startup or shutdown of database, if necessary* to modify the state of the database, if required.
+
This option ensures that if the database is not in the required state to create a backup, SnapManager automatically brings the database to the desired state to complete the operation.

. On the *Database*, *Tablespaces* or *Datafiles* to `Backup` page, perform the following:
 .. Select *Backup Datafiles* to back up either the full database, selected data files, or selected tablespaces.
 .. Select *Backup Archivelogs* to back up the archive log files separately.
 .. Select *Prune Archivelogs* if you want to delete the archive log files from the active file system that is already backed up.
+
NOTE: If Flash Recovery Area (FRA) is enabled for archive log files, then SnapManager fails to prune the archive log files.

 .. Select *Protect the backup* if you want to enable backup protection.
+
This option is enabled only if the protection policy was selected while creating the profile.

 .. From the *Type* drop-down list, select the type of backup (offline or online) you want to create.
+
If you select _Auto_, SnapManager creates a backup based on the current state of the database.

 .. From the *Retention Class* drop-down list, select the retention class.
 .. Select the *Verify backup using the Oracle DBVERIFY utility* check box if you want to ensure that the backed-up files are not corrupted.
. On the *Task Enabling* page, specify whether you want to perform tasks before and after backup operations are completed.
. On the *Perform Backup Operation* page, verify the information and click *Backup*.
. Click *Finish* to close the wizard.
+
If the operation fails, click *Operation Details* to view what caused the operation to fail.

*Related information*

https://library.netapp.com/ecm/ecm_download_file/ECMP12481453[SnapManager 3.4.1 for SAP Administration Guide for UNIX^]
