---
permalink: unix-installation-cmode/task_modifying_the_backup_retention_class.html
sidebar: sidebar
keywords: upgrading, upgrade, snapmanager, assign, default, backup, retention, exist, default, retention, class, value, requirement, modify, class
summary: After upgrading, SnapManager assigns the default backup retention class to the existing backups. You can modify the default retention class values to meet your backup requirements.
---
= Modifying the backup retention class
:icons: font
:imagesdir: ../media/

[.lead]
After upgrading, SnapManager assigns the default backup retention class to the existing backups. You can modify the default retention class values to meet your backup requirements.

The default backup retention class assigned to the existing backups are as follows:

[options="header"]
|===
| Backup type| Retention class assignment after upgrade
a|
Backups to be retained forever
a|
Unlimited
a|
Other backups
a|
Daily
|===
*Note:* You can delete the backups that are retained forever without changing the retention class.

If you upgrade to SnapManager 3.0 or later, the greater of the following two values are assigned to the existing profiles:

* Previous retention count for the profile
* Default values for the retention count and duration of daily backups as specified in the smsap.config file

. Modify the values assigned to retain.hourly.count and retain.hourly.duration in the smsap.config file.
+
The smsap.config file is located at default installation location/properties/smsap.config.
+
You can enter the following values:

 ** retain.hourly.count = 12
 ** retain.hourly.duration = 2
