---
permalink: unix-installation-cmode/task_perform_a_rollback_on_a_single_host_or_multiple_hosts.html
sidebar: sidebar
keywords: perform, rollback, single, multiple, snapmanager, server, host, command-line, interface, cli
summary: "You can perform a rollback on a single or multiple SnapManager server hosts by using the command-line interface (CLI)."
---
= Perform a rollback on a single host or multiple hosts
:icons: font
:imagesdir: ../media/

[.lead]
You can perform a rollback on a single or multiple SnapManager server hosts by using the command-line interface (CLI).

== What you'll need

You must ensure that all the prerequisites for performing a rollback are complete.

.Steps
. To perform a rollback on a single host, enter the following command:
+
`*smsap repository rollback -repository -dbname _repo_service_name_ -host _repo_host_ -login -username _repo_username_ -port _repo_port_ -rollbackhost _host_with_target_database_*`
+
*Example*
+
The following example shows the command to roll back all the target databases that are mounted on hostA and a repository database named repoA located on the repository host, repo_host:
+
----

smsap repository rollback
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -rollbackhost hostA
----

. To perform a rollback on multiple hosts, enter the following command:
+
`*smsap repository rollback -repository-dbname _repo_service_name_ -host _repo_host_ -login -username _repo_username_ -port _repo_port_ -rollbackhost _host_with_target_database1_,_host_with_target_database2_*`
+
NOTE: For multiple hosts, enter the host names separated by a comma and ensure that there is no space between the comma and the next host name.
+
If you are using Real Application Clusters (RAC) configuration, you must manually roll back all RAC-associated hosts. You can use `-allhosts` to perform a rollback of all the hosts.
+
*Example*
+
The following example shows the command to roll back all the target databases that are mounted on the hosts, hostA, hostB, and a repository database named repoA located on the repository host, repo_host:
+
----

smsap repository rollback
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -rollbackhost hostA,hostB
----
+
The hosts, profiles, schedules, backups, and clones that are associated with the profiles of the target databases for the host are reverted to the earlier repository.
