---
permalink: unix-installation-cmode/task_smsap_isg_configuring_the_snapmanager_repository.html
sidebar: sidebar
keywords: configure, snapmanager, repository, database, instance, metadata, configuring
summary: You must configure the SnapManager repository in the repository database instance. The repository database stores metadata for databases managed by SnapManager.
---
= Configuring the SnapManager repository
:icons: font
:imagesdir: ../media/

[.lead]
You must configure the SnapManager repository in the repository database instance. The repository database stores metadata for databases managed by SnapManager.

* You must have created the repository database instance.
* You must have created the Oracle user for the repository database instance with required privileges.
* You must have included the repository database instance details in the tnsnames.ora file.

You can configure the SnapManager repository either from the SnapManager user interface (UI) or command-line interface (CLI). These steps show how to create a repository using the SnapManager UI. You can also use the CLI if you prefer.

For information about how to create the repository by using CLI, see the _SnapManager for SAP Administration guide for UNIX_.

. In the left pane of the SnapManager UI, right-click *Repositories*.
. Select *Create New Repository* and click *Next*.
. In the Repository Database Configuration Information window, enter the following information:
+
[options="header"]
|===
| In this field...| Do this...
a|
*User Name*
a|
Enter the name of the user you created for the repository database instance.
a|
*Password*
a|
Enter the password.
a|
*Host*
a|
Enter the IP address of the host where the repository database instance is created.
a|
*Port*
a|
Enter the port used to connect to the repository database instance.    The default port is 1521.
a|
*Service Name*
a|
Enter the name that SnapManager uses to connect to the repository database instance.    Depending on the details included in the tnsnames.ora file, this might be the short service name or the fully qualified service name.
+
|===

. In the Perform Repository Add Operation window, review the configuration summary and click *Add*.
+
If the operation fails, click the *Operation Details* tab to view what caused the operation to fail. The error details are also captured in the operation log located at /var/log/smsap.

. Click *Finish*.
+
The repository is listed in the left pane under the *Repositories* tree. If you do not see the repository, right-click *Repositories* and click *Refresh*.

*Related information*

https://library.netapp.com/ecm/ecm_download_file/ECMP12481453[SnapManager 3.4.1 for SAP Administration Guide for UNIX]
