---
permalink: unix-installation-7mode/concept_smsap_isg_defining_a_backup_strategy.html
sidebar: sidebar
keywords: define, defining, backup, strategy, creating, create, ensure, service, level, agreement, sla
summary: Defining a backup strategy before creating your backups ensures that you have backups to successfully restore your databases. SnapManager provides flexible granular backup schedule to meet your Service Level Agreement \(SLA\).
---
= Defining a backup strategy
:icons: font
:imagesdir: ../media/

[.lead]
Defining a backup strategy before creating your backups ensures that you have backups to successfully restore your databases. SnapManager provides flexible granular backup schedule to meet your Service Level Agreement (SLA).

NOTE: For SnapManager best practices, see _TR 3761_.

== What mode of SnapManager backup do you need?

SnapManager supports two modes of backups:

[options="header"]
|===
| Backup mode| Description
a|
Online backup
a|
Creates a backup of the database when the database is in online state. This backup mode is also called a hot backup.
a|
Offline backup
a|
Creates a backup of the database when the database is either in a mounted or shutdown state. This backup mode is also called a cold backup.
|===

== What type of SnapManager backup do you need?

SnapManager supports three types of backups:

[options="header"]
|===
| Backup type| Description
a|
Full backup
a|
Creates a backup of the entire database, which includes all the datafiles, control files, and archive log files.
a|
Partial backup
a|
Creates a backup of selected datafiles, control files, tablespaces, and archive log files
a|
Archive log-only backup
a|
Creates a backup of only the archive log files.You must select *Backup Archivelogs Separately* while creating the profile.

|===

== What type of database profile do you need?

SnapManager creates backups based on whether the database profile separates the archive log backups from the data file backups.

[options="header"]
|===
| Profile type| Description
a|
A single database profile for combined backup of data files and archive logs
a|
Allows you to create:

* Full backup containing all the data files, archive log files, and control files
* Partial backup containing selected data files, tablespaces, archive log files, and control files

a|
Separate database profiles for archive log backups and data file backups
a|
Allows you to create:

* Combined backup with different labels for data file backup and archive log backup
* Data-files-only backup of all the data files along with the control files
* Partial data-files-only backup of selected data files or tablespaces along with the control files
* Archive-logs-only backup

|===

== What naming conventions should be used for Snapshot copies?

Snapshot copies created by backups can follow a custom naming convention. Custom text or built-in variables such as the profile name, the database name, and the database SID provided by SnapManager can be used to create the naming convention. You can create the naming convention while creating the policy.

NOTE: You must include the smid variable in the naming format. The smid variable creates a unique Snapshot identifier.

The Snapshot copy naming convention can be changed during or after the creation of a profile. The updated pattern applies only to Snapshot copies that have not yet been created; existing Snapshot copies retain the previous pattern.

== How long do you want to retain backup copies on the primary storage system and the secondary storage system?

A backup retention policy specifies the number of successful backups to retain. You can specify the retention policy while creating the policy.

You can select hourly, daily, weekly, monthly, or unlimited as the retention class. For each retention class, you can specify the retention count and retention duration, either together or individually.

* Retention count determines the minimum number of backups of a particular retention class that should be retained.
+
For example, if backup schedule is _daily_ and retention count is _10_, then 10 daily backups are retained.
+
NOTE: The maximum number of Snapshot copies that Data ONTAP allows you can retain is 255. After it reaches the maximum limit, by default the creation of new Snapshot copies fail. However, you can configure the rotation policy in Data ONTAP to delete older Snapshot copies.

* Retention duration determines the minimum number of days for which the backup should be retained.
+
For example, if backup schedule is _daily_ and retention duration is _10_, then 10 days of daily backups are retained.

If you set up SnapMirror replication, the retention policy is mirrored on the destination volume.

NOTE: For long-term retention of backup copies, you should use SnapVault.

== Do you want to verify backup copies using the source volume or a destination volume?

If you use SnapMirror or SnapVault, you can verify backup copies using the Snapshot copy on the SnapMirror or SnapVault destination volume rather than the Snapshot copy on the primary storage system. Using a destination volume for verification reduces the load on the primary storage system.

*Related information*

http://www.netapp.com/us/media/tr-3761.pdf[NetApp Technical Report 3761: SnapManager for Oracle: Best Practices]
