---
permalink: unix-installation-7mode/reference-smsap-isg-snapmanager-licensing.html
sidebar: sidebar
keywords: snapmanager, license, storage, system, require, enable, license, licensing, model, per-server, host, database
summary: "A SnapManager license and several storage system licenses are required to enable SnapManager operations. The SnapManager license is available in two licensing models: per-server licensing, in which the SnapManager license resides on each database host and per-storage system licensing, in which the SnapManager license resides on the storage system."
---
= SnapManager licensing
:icons: font
:imagesdir: ../media/

[.lead]
A SnapManager license and several storage system licenses are required to enable SnapManager operations. The SnapManager license is available in two licensing models: _per-server licensing_, in which the SnapManager license resides on each database host; and _per-storage system licensing_, in which the SnapManager license resides on the storage system.

The SnapManager license requirements are as follows:

[options="header"]
|===
| License| Description| Where required
a|
SnapManager per-server
a|
A host-side license for a specific database host.Licenses are required only for database hosts on which SnapManager is installed. No SnapManager license is required for the storage system.

a|
On the SnapManager host. A SnapManager license is not required on primary and secondary storage systems when using per-server licensing.
a|
SnapManager per-storage system
a|
A storage-side license that supports any number of database hosts. Required only if you are not using a per-server license on the database host.

a|
On primary and secondary storage systems.
a|
SnapRestore
a|
A required license that enables SnapManager to restore databases.
a|
On primary and secondary storage systems. Required on SnapVault destination systems to restore a file from a backup.

a|
FlexClone
a|
An optional license for cloning databases.
a|
On primary and secondary storage systems.Required on SnapVault destination systems when creating clones from a backup.

a|
SnapMirror
a|
An optional license for mirroring backups to a destination storage system.
a|
On primary and secondary storage systems.
a|
SnapVault
a|
An optional license for archiving backups to a destination storage system.
a|
On primary and secondary storage systems.
a|
Protocols
a|
NFS, iSCSI, or FC license is required depending on the protocol used.
a|
On primary and secondary storage systems. Required on SnapMirror destination systems to serve data if a source volume is unavailable.

|===
