---
permalink: unix-installation-7mode/reference-smsap-isg-product-overview.html
sidebar: sidebar
keywords: snapmanager, sap, automate, complex, manual, time-consuming, associate, backup, recovery, cloning, clone, database, ontap, technology, copies, copy, disk, product, overview
summary: "SnapManager for SAP automates and simplifies the complex, manual, and time-consuming processes associated with the backup, recovery, and cloning of databases. You can use SnapManager with ONTAP SnapMirror technology to create copies of backups on another volume and with ONTAP SnapVault technology to archive backups efficiently to disk."
---
= Product overview
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager for SAP automates and simplifies the complex, manual, and time-consuming processes associated with the backup, recovery, and cloning of databases. You can use SnapManager with ONTAP SnapMirror technology to create copies of backups on another volume and with ONTAP SnapVault technology to archive backups efficiently to disk.

SnapManager provides the tools required, such as OnCommand Unified Manager and integration with SAP's BR* Tools, to perform policy-driven data management, schedule and create regular database backups, and restore data from these backups in the event of data loss or disaster.

SnapManager also integrates with native Oracle technologies, such as Oracle Real Application Clusters (Oracle RAC) and Oracle Recovery Manager (RMAN) to preserve backup information. These backups can be used later in block-level restore or tablespace point-in-time recovery operations.

== SnapManager highlights

SnapManager features seamless integration with databases on the UNIX host and with Snapshot, SnapRestore, and FlexClone technologies on the back end. It offers an easy-to-use user interface (UI) as well as command-line interface (CLI) for administrative functions.

SnapManager enables you to perform the following database operations and manage data efficiently:

* Creating space-efficient backups on primary or secondary storage
+
SnapManager enables you to back up the data files and archive log files separately.

* Scheduling backups
* Restoring full or partial databases by using a file-based or volume-based restore operation
* Recovering databases by discovering, mounting, and applying archive log files from backups
* Pruning archive log files from archive log destinations when creating backups of only the archive logs
* Retaining a minimum number of archive log backups automatically by retaining only the backups that contain unique archive log files
* Tracking operation details and generating reports
* Verifying backups to ensure that backups are in a valid block format and that none of the backed-up files are corrupted
* Maintaining a history of operations performed on the database profile
+
A profile contains information about the database to be managed by SnapManager.

* Protecting backups on the secondary and tertiary storage systems.
* Creating space-efficient clones of backups on primary or secondary storage
+
SnapManager enables you to split a clone of a database.
