---
permalink: unix-installation-7mode/task-smsap-isg-verify-database-backups.html
sidebar: sidebar
keywords: verify, backup, database, ensure, backed-up, file, corrupt
summary: "You can verify the backup of your database to ensure that the backed-up files are not corrupted."
---
= Verify database backups
:icons: font
:imagesdir: ../media/

[.lead]
You can verify the backup of your database to ensure that the backed-up files are not corrupted.

*About this task*

If you did not select the *Verify backup using the Oracle DBVERIFY utility* check box while creating a backup, you must perform these steps manually to verify the backup. However, if you selected the check box, SnapManager automatically verifies the backup.

.Steps

. From the *Repositories* tree, select the profile.
. Right-click the backup that you want to verify, and select *Verify*.
. Click *Finish*.
+
If the operation fails, click *Operation Details* to view what caused the operation to fail.
+
In the *Repository* tree, right-click the backup, and then click *Properties* to view the results of the verify operation.

*After you finish*

You can use backed-up files to perform restore operations. For information about how to perform restore operations using the SnapManager user interface (UI), see the _Online Help_. If you want to use the command-line interface (CLI) to perform restore operations, see the _SnapManager for SAP Administration guide for UNIX_.

*Related information*

https://library.netapp.com/ecm/ecm_download_file/ECMP12481453[SnapManager 3.4.1 for SAP Administration Guide for UNIX^]
