---
permalink: unix-installation-7mode/task_prepare_storage_systems_for_snapvault_replication_7_mode.html
sidebar: sidebar
keywords: snapmanager, integrate, snapvault, technology, archive, snapshot, copies, copy, disk, configure, intialize, data-protection, relationship, source, volume, destination, volume, initialization, data, block, preparing, prepare, storage, system, replication
summary: "Before you can use SnapManager’s integrated SnapVault technology to archive Snapshot copies to disk, you must configure and initialize a data-protection relationship between the source and destination volumes. On initialization, SnapVault makes a Snapshot copy of the source volume, then transfers the copy and all the data blocks it references to the destination volume."
---
= Prepare storage systems for SnapVault replication
:icons: font
:imagesdir: ../media/

[.lead]
Before you can use SnapManager's integrated SnapVault technology to archive Snapshot copies to disk, you must configure and initialize a _data-protection relationship_ between the source and destination volumes. On initialization, SnapVault makes a Snapshot copy of the source volume, then transfers the copy and all the data blocks it references to the destination volume.

*What you'll need*

* You must have configured a dataset for the primary storage location in the SnapManager Configuration wizard.
* All LUNs must be in qtrees, with one LUN per qtree.

IMPORTANT: If you are storing database files and transaction logs on different volumes, you must create relationships between the source and destination volumes for the database files and between the source and destination volumes for the transaction logs.

.Steps

. On both the source and destination system consoles, enable SnapVault:
+
*Example*
+
----
options snapvault.enable on
----

. On the source system console, use the `options snapvault.access` command to specify the host names of systems that are allowed to copy data directly from the source system.
+
*Example*
+
The following command allows replication to destination_systemB:
+
----
options snapvault.access host=destination_systemB
----

. On the destination system console, use the `options snapvault.access` command to specify the host names of systems to which copied data can be restored.
+
*Example*
+
The following command allows copied data to be restored to source_systemA:
+
----
options snapvault.access host=destination_systemA
----

. On the source system console, use the ndmpd on command to enable NDMP.
+
*Example*
+
The following command enables NDMP:
+
----
ndmpd on
----

. On the destination system console, use the vol create command to create a SnapMirror destination volume that is the same or greater in size than the source volume.
+
*Example*
+
The following command creates a 2-GB destination volume named vol2 on the aggregate aggr1:
+
----
vol create vol2 aggr1 2g
----

. In the OnCommand Unified Manager (UM) NetApp Management Console, add the resource pool for the destination volume:
 .. Click *Data* > *Resource Pools* to open the *Resource Pools* page.
 .. On the Resource Pools page, click *Add* to start the *Add Resource Pool* wizard.
 .. Follow the prompts in the wizard to specify the aggregate for the destination volume.
 .. Click *Finish* to exit the wizard.
. In the UM NetApp Management Console, assign the resource pool to the dataset you created in the SnapManager Configuration wizard:
 .. Click *Data* > *Datasets* to open the Datasets page.
 .. On the *Datasets* page, select the dataset you created and click *Edit*.
 .. On the *Edit Dataset* page, click *Backup* > *Provisioning/Resource Pools* to open the *Configure Dataset Node* wizard.
 .. Follow the prompts in the wizard to assign the resource pool to the dataset.
+
Resource pool assignment specifies the data-protection relationship between the source and destination volumes.

 .. Click *Finish* to exit the wizard and initialize the data-protection relationship.
+
The initialization process performs a _baseline transfer_ to the destination volume. SnapVault makes a Snapshot copy of the source volume, then transfers the copy and all the data blocks it references to the destination volume.
